// Generated by pegainfer-k3/kernels/generate.py -- do not edit.
#include <cuda_runtime.h>

#if defined(_MSC_VER) && !defined(__clang__) && _MSC_VER < 1940
#define _tl_orig_alignas alignas
#define alignas(N) _tl_orig_alignas((N) <= 64 ? (N) : 64)
#include <cuda.h>
#undef alignas
#define alignas _tl_orig_alignas
#endif
#include <tl_templates/cuda/reduce.h>
#include <tl_templates/cuda/scan.h>
#include <tl_templates/cuda/ldsm.h>
#include <tl_templates/cuda/threadblock_swizzle.h>
#define debug_print_msg k3_add2_batched_debug_print_msg
#define debug_print_buffer_value k3_add2_batched_debug_print_buffer_value
#include <tl_templates/cuda/debug.h>
#undef debug_print_msg
#undef debug_print_buffer_value
#ifdef ENABLE_BF16
#include <tl_templates/cuda/cuda_bf16_fallbacks.cuh>
#endif

extern "C" __global__ void k3_add2_b1_n7168_kernel(const bfloat16_t* __restrict__ A, const bfloat16_t* __restrict__ Bt, bfloat16_t* __restrict__ O);
extern "C" __global__ void __launch_bounds__(256, 1) k3_add2_b1_n7168_kernel(const bfloat16_t* __restrict__ A, const bfloat16_t* __restrict__ Bt, bfloat16_t* __restrict__ O) {
  O[((((int)blockIdx.y) * 256) + ((int)threadIdx.x))] = (A[((((int)blockIdx.y) * 256) + ((int)threadIdx.x))] + Bt[((((int)blockIdx.y) * 256) + ((int)threadIdx.x))]);
}


extern "C" __global__ void k3_add2_b2_n7168_kernel(const bfloat16_t* __restrict__ A, const bfloat16_t* __restrict__ Bt, bfloat16_t* __restrict__ O);
extern "C" __global__ void __launch_bounds__(256, 1) k3_add2_b2_n7168_kernel(const bfloat16_t* __restrict__ A, const bfloat16_t* __restrict__ Bt, bfloat16_t* __restrict__ O) {
  O[(((((int)blockIdx.x) * 7168) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] = (A[(((((int)blockIdx.x) * 7168) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] + Bt[(((((int)blockIdx.x) * 7168) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]);
}


extern "C" __global__ void k3_add2_b4_n7168_kernel(const bfloat16_t* __restrict__ A, const bfloat16_t* __restrict__ Bt, bfloat16_t* __restrict__ O);
extern "C" __global__ void __launch_bounds__(256, 1) k3_add2_b4_n7168_kernel(const bfloat16_t* __restrict__ A, const bfloat16_t* __restrict__ Bt, bfloat16_t* __restrict__ O) {
  O[(((((int)blockIdx.x) * 7168) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] = (A[(((((int)blockIdx.x) * 7168) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] + Bt[(((((int)blockIdx.x) * 7168) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]);
}


extern "C" __global__ void k3_add2_b8_n7168_kernel(const bfloat16_t* __restrict__ A, const bfloat16_t* __restrict__ Bt, bfloat16_t* __restrict__ O);
extern "C" __global__ void __launch_bounds__(256, 1) k3_add2_b8_n7168_kernel(const bfloat16_t* __restrict__ A, const bfloat16_t* __restrict__ Bt, bfloat16_t* __restrict__ O) {
  O[(((((int)blockIdx.x) * 7168) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] = (A[(((((int)blockIdx.x) * 7168) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] + Bt[(((((int)blockIdx.x) * 7168) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]);
}


extern "C" __global__ void k3_add2_b16_n7168_kernel(const bfloat16_t* __restrict__ A, const bfloat16_t* __restrict__ Bt, bfloat16_t* __restrict__ O);
extern "C" __global__ void __launch_bounds__(256, 1) k3_add2_b16_n7168_kernel(const bfloat16_t* __restrict__ A, const bfloat16_t* __restrict__ Bt, bfloat16_t* __restrict__ O) {
  O[(((((int)blockIdx.x) * 7168) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] = (A[(((((int)blockIdx.x) * 7168) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] + Bt[(((((int)blockIdx.x) * 7168) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]);
}


extern "C" __global__ void k3_add2_b32_n7168_kernel(const bfloat16_t* __restrict__ A, const bfloat16_t* __restrict__ Bt, bfloat16_t* __restrict__ O);
extern "C" __global__ void __launch_bounds__(256, 1) k3_add2_b32_n7168_kernel(const bfloat16_t* __restrict__ A, const bfloat16_t* __restrict__ Bt, bfloat16_t* __restrict__ O) {
  O[(((((int)blockIdx.x) * 7168) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] = (A[(((((int)blockIdx.x) * 7168) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] + Bt[(((((int)blockIdx.x) * 7168) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]);
}


extern "C" __global__ void k3_add2_b48_n7168_kernel(const bfloat16_t* __restrict__ A, const bfloat16_t* __restrict__ Bt, bfloat16_t* __restrict__ O);
extern "C" __global__ void __launch_bounds__(256, 1) k3_add2_b48_n7168_kernel(const bfloat16_t* __restrict__ A, const bfloat16_t* __restrict__ Bt, bfloat16_t* __restrict__ O) {
  O[(((((int)blockIdx.x) * 7168) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] = (A[(((((int)blockIdx.x) * 7168) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] + Bt[(((((int)blockIdx.x) * 7168) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]);
}


extern "C" __global__ void k3_add2_b64_n7168_kernel(const bfloat16_t* __restrict__ A, const bfloat16_t* __restrict__ Bt, bfloat16_t* __restrict__ O);
extern "C" __global__ void __launch_bounds__(256, 1) k3_add2_b64_n7168_kernel(const bfloat16_t* __restrict__ A, const bfloat16_t* __restrict__ Bt, bfloat16_t* __restrict__ O) {
  O[(((((int)blockIdx.x) * 7168) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] = (A[(((((int)blockIdx.x) * 7168) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] + Bt[(((((int)blockIdx.x) * 7168) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]);
}


extern "C" __global__ void k3_add2_b96_n7168_kernel(const bfloat16_t* __restrict__ A, const bfloat16_t* __restrict__ Bt, bfloat16_t* __restrict__ O);
extern "C" __global__ void __launch_bounds__(256, 1) k3_add2_b96_n7168_kernel(const bfloat16_t* __restrict__ A, const bfloat16_t* __restrict__ Bt, bfloat16_t* __restrict__ O) {
  O[(((((int)blockIdx.x) * 7168) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] = (A[(((((int)blockIdx.x) * 7168) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] + Bt[(((((int)blockIdx.x) * 7168) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]);
}


extern "C" __global__ void k3_add2_b128_n7168_kernel(const bfloat16_t* __restrict__ A, const bfloat16_t* __restrict__ Bt, bfloat16_t* __restrict__ O);
extern "C" __global__ void __launch_bounds__(256, 1) k3_add2_b128_n7168_kernel(const bfloat16_t* __restrict__ A, const bfloat16_t* __restrict__ Bt, bfloat16_t* __restrict__ O) {
  O[(((((int)blockIdx.x) * 7168) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] = (A[(((((int)blockIdx.x) * 7168) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] + Bt[(((((int)blockIdx.x) * 7168) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]);
}



// O = A + B in bf16 addition (the residual adds, and routed + shared).
// One block per (row, column segment).
extern "C" int k3_add2_batched(
    const void* A,
    const void* Bt,
    void* O,
    int b,
    int n,
    cudaStream_t stream) {
  if (b == 1 && n == 7168) {
    k3_add2_b1_n7168_kernel<<<dim3(1, 28, 1), 256, 0, stream>>>(
        reinterpret_cast<const bfloat16_t*>(A),
        reinterpret_cast<const bfloat16_t*>(Bt),
        reinterpret_cast<bfloat16_t*>(O));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 2 && n == 7168) {
    k3_add2_b2_n7168_kernel<<<dim3(2, 28, 1), 256, 0, stream>>>(
        reinterpret_cast<const bfloat16_t*>(A),
        reinterpret_cast<const bfloat16_t*>(Bt),
        reinterpret_cast<bfloat16_t*>(O));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 4 && n == 7168) {
    k3_add2_b4_n7168_kernel<<<dim3(4, 28, 1), 256, 0, stream>>>(
        reinterpret_cast<const bfloat16_t*>(A),
        reinterpret_cast<const bfloat16_t*>(Bt),
        reinterpret_cast<bfloat16_t*>(O));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 8 && n == 7168) {
    k3_add2_b8_n7168_kernel<<<dim3(8, 28, 1), 256, 0, stream>>>(
        reinterpret_cast<const bfloat16_t*>(A),
        reinterpret_cast<const bfloat16_t*>(Bt),
        reinterpret_cast<bfloat16_t*>(O));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 16 && n == 7168) {
    k3_add2_b16_n7168_kernel<<<dim3(16, 28, 1), 256, 0, stream>>>(
        reinterpret_cast<const bfloat16_t*>(A),
        reinterpret_cast<const bfloat16_t*>(Bt),
        reinterpret_cast<bfloat16_t*>(O));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 32 && n == 7168) {
    k3_add2_b32_n7168_kernel<<<dim3(32, 28, 1), 256, 0, stream>>>(
        reinterpret_cast<const bfloat16_t*>(A),
        reinterpret_cast<const bfloat16_t*>(Bt),
        reinterpret_cast<bfloat16_t*>(O));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 48 && n == 7168) {
    k3_add2_b48_n7168_kernel<<<dim3(48, 28, 1), 256, 0, stream>>>(
        reinterpret_cast<const bfloat16_t*>(A),
        reinterpret_cast<const bfloat16_t*>(Bt),
        reinterpret_cast<bfloat16_t*>(O));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 64 && n == 7168) {
    k3_add2_b64_n7168_kernel<<<dim3(64, 28, 1), 256, 0, stream>>>(
        reinterpret_cast<const bfloat16_t*>(A),
        reinterpret_cast<const bfloat16_t*>(Bt),
        reinterpret_cast<bfloat16_t*>(O));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 96 && n == 7168) {
    k3_add2_b96_n7168_kernel<<<dim3(96, 28, 1), 256, 0, stream>>>(
        reinterpret_cast<const bfloat16_t*>(A),
        reinterpret_cast<const bfloat16_t*>(Bt),
        reinterpret_cast<bfloat16_t*>(O));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 128 && n == 7168) {
    k3_add2_b128_n7168_kernel<<<dim3(128, 28, 1), 256, 0, stream>>>(
        reinterpret_cast<const bfloat16_t*>(A),
        reinterpret_cast<const bfloat16_t*>(Bt),
        reinterpret_cast<bfloat16_t*>(O));
    return static_cast<int>(cudaGetLastError());
  }
  return static_cast<int>(cudaErrorInvalidValue);
}
