// Generated by pegainfer-k3/kernels/generate.py -- do not edit.
#include <cuda_runtime.h>

#if defined(_MSC_VER) && !defined(__clang__) && _MSC_VER < 1940
#define _tl_orig_alignas alignas
#define alignas(N) _tl_orig_alignas((N) <= 64 ? (N) : 64)
#include <cuda.h>
#undef alignas
#define alignas _tl_orig_alignas
#endif
#include <tl_templates/cuda/reduce.h>
#include <tl_templates/cuda/scan.h>
#include <tl_templates/cuda/ldsm.h>
#include <tl_templates/cuda/threadblock_swizzle.h>
#define debug_print_msg k3_conv_silu_batched_debug_print_msg
#define debug_print_buffer_value k3_conv_silu_batched_debug_print_buffer_value
#include <tl_templates/cuda/debug.h>
#undef debug_print_msg
#undef debug_print_buffer_value
#ifdef ENABLE_BF16
#include <tl_templates/cuda/cuda_bf16_fallbacks.cuh>
#endif

extern "C" __global__ void k3_conv_silu_b1_kp12288_w4_sk1_kernel(const bfloat16_t* __restrict__ Cs, const float* __restrict__ Cw, const float* __restrict__ P, bfloat16_t* __restrict__ Sn, bfloat16_t* __restrict__ X, bfloat16_t* __restrict__ Y);
extern "C" __global__ void __launch_bounds__(256, 1) k3_conv_silu_b1_kp12288_w4_sk1_kernel(const bfloat16_t* __restrict__ Cs, const float* __restrict__ Cw, const float* __restrict__ P, bfloat16_t* __restrict__ Sn, bfloat16_t* __restrict__ X, bfloat16_t* __restrict__ Y) {
  float xa[1];
  float ca[1];
  xa[0] = 0x0p+0f/*0.000000e+00*/;
  xa[0] = (xa[0] + P[((((int)blockIdx.y) * 256) + ((int)threadIdx.x))]);
  ca[0] = 0x0p+0f/*0.000000e+00*/;
  bfloat16_t xb = ((bfloat16_t)xa[0]);
  X[((((int)blockIdx.y) * 256) + ((int)threadIdx.x))] = xb;
  for (int t = 0; t < 3; ++t) {
    ca[0] = (ca[0] + (((float)Cs[(((t * 12288) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]) * Cw[(((t * 12288) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]));
    bfloat16_t condval;
    if ((t < 2)) {
      condval = Cs[((((t * 12288) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x)) + 12288)];
    } else {
      condval = xb;
    }
    Sn[(((t * 12288) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] = condval;
  }
  ca[0] = (ca[0] + (((float)xb) * Cw[(((((int)blockIdx.y) * 256) + ((int)threadIdx.x)) + 36864)]));
  float sb = ((float)((bfloat16_t)ca[0]));
  Y[((((int)blockIdx.y) * 256) + ((int)threadIdx.x))] = ((bfloat16_t)(sb * (0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - sb))))));
}


extern "C" __global__ void k3_conv_silu_b2_kp12288_w4_sk1_kernel(const bfloat16_t* __restrict__ Cs, const float* __restrict__ Cw, const float* __restrict__ P, bfloat16_t* __restrict__ Sn, bfloat16_t* __restrict__ X, bfloat16_t* __restrict__ Y);
extern "C" __global__ void __launch_bounds__(256, 1) k3_conv_silu_b2_kp12288_w4_sk1_kernel(const bfloat16_t* __restrict__ Cs, const float* __restrict__ Cw, const float* __restrict__ P, bfloat16_t* __restrict__ Sn, bfloat16_t* __restrict__ X, bfloat16_t* __restrict__ Y) {
  float xa[1];
  float ca[1];
  xa[0] = 0x0p+0f/*0.000000e+00*/;
  xa[0] = (xa[0] + P[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]);
  ca[0] = 0x0p+0f/*0.000000e+00*/;
  bfloat16_t xb = ((bfloat16_t)xa[0]);
  X[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] = xb;
  for (int t = 0; t < 3; ++t) {
    ca[0] = (ca[0] + (((float)Cs[((((((int)blockIdx.x) * 36864) + (t * 12288)) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]) * Cw[(((t * 12288) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]));
    bfloat16_t condval;
    if ((t < 2)) {
      condval = Cs[(((((((int)blockIdx.x) * 36864) + (t * 12288)) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x)) + 12288)];
    } else {
      condval = xb;
    }
    Sn[((((((int)blockIdx.x) * 36864) + (t * 12288)) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] = condval;
  }
  ca[0] = (ca[0] + (((float)xb) * Cw[(((((int)blockIdx.y) * 256) + ((int)threadIdx.x)) + 36864)]));
  float sb = ((float)((bfloat16_t)ca[0]));
  Y[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] = ((bfloat16_t)(sb * (0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - sb))))));
}


extern "C" __global__ void k3_conv_silu_b4_kp12288_w4_sk1_kernel(const bfloat16_t* __restrict__ Cs, const float* __restrict__ Cw, const float* __restrict__ P, bfloat16_t* __restrict__ Sn, bfloat16_t* __restrict__ X, bfloat16_t* __restrict__ Y);
extern "C" __global__ void __launch_bounds__(256, 1) k3_conv_silu_b4_kp12288_w4_sk1_kernel(const bfloat16_t* __restrict__ Cs, const float* __restrict__ Cw, const float* __restrict__ P, bfloat16_t* __restrict__ Sn, bfloat16_t* __restrict__ X, bfloat16_t* __restrict__ Y) {
  float xa[1];
  float ca[1];
  xa[0] = 0x0p+0f/*0.000000e+00*/;
  xa[0] = (xa[0] + P[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]);
  ca[0] = 0x0p+0f/*0.000000e+00*/;
  bfloat16_t xb = ((bfloat16_t)xa[0]);
  X[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] = xb;
  for (int t = 0; t < 3; ++t) {
    ca[0] = (ca[0] + (((float)Cs[((((((int)blockIdx.x) * 36864) + (t * 12288)) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]) * Cw[(((t * 12288) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]));
    bfloat16_t condval;
    if ((t < 2)) {
      condval = Cs[(((((((int)blockIdx.x) * 36864) + (t * 12288)) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x)) + 12288)];
    } else {
      condval = xb;
    }
    Sn[((((((int)blockIdx.x) * 36864) + (t * 12288)) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] = condval;
  }
  ca[0] = (ca[0] + (((float)xb) * Cw[(((((int)blockIdx.y) * 256) + ((int)threadIdx.x)) + 36864)]));
  float sb = ((float)((bfloat16_t)ca[0]));
  Y[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] = ((bfloat16_t)(sb * (0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - sb))))));
}


extern "C" __global__ void k3_conv_silu_b8_kp12288_w4_sk1_kernel(const bfloat16_t* __restrict__ Cs, const float* __restrict__ Cw, const float* __restrict__ P, bfloat16_t* __restrict__ Sn, bfloat16_t* __restrict__ X, bfloat16_t* __restrict__ Y);
extern "C" __global__ void __launch_bounds__(256, 1) k3_conv_silu_b8_kp12288_w4_sk1_kernel(const bfloat16_t* __restrict__ Cs, const float* __restrict__ Cw, const float* __restrict__ P, bfloat16_t* __restrict__ Sn, bfloat16_t* __restrict__ X, bfloat16_t* __restrict__ Y) {
  float xa[1];
  float ca[1];
  xa[0] = 0x0p+0f/*0.000000e+00*/;
  xa[0] = (xa[0] + P[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]);
  ca[0] = 0x0p+0f/*0.000000e+00*/;
  bfloat16_t xb = ((bfloat16_t)xa[0]);
  X[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] = xb;
  for (int t = 0; t < 3; ++t) {
    ca[0] = (ca[0] + (((float)Cs[((((((int)blockIdx.x) * 36864) + (t * 12288)) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]) * Cw[(((t * 12288) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]));
    bfloat16_t condval;
    if ((t < 2)) {
      condval = Cs[(((((((int)blockIdx.x) * 36864) + (t * 12288)) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x)) + 12288)];
    } else {
      condval = xb;
    }
    Sn[((((((int)blockIdx.x) * 36864) + (t * 12288)) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] = condval;
  }
  ca[0] = (ca[0] + (((float)xb) * Cw[(((((int)blockIdx.y) * 256) + ((int)threadIdx.x)) + 36864)]));
  float sb = ((float)((bfloat16_t)ca[0]));
  Y[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] = ((bfloat16_t)(sb * (0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - sb))))));
}


extern "C" __global__ void k3_conv_silu_b16_kp12288_w4_sk1_kernel(const bfloat16_t* __restrict__ Cs, const float* __restrict__ Cw, const float* __restrict__ P, bfloat16_t* __restrict__ Sn, bfloat16_t* __restrict__ X, bfloat16_t* __restrict__ Y);
extern "C" __global__ void __launch_bounds__(256, 1) k3_conv_silu_b16_kp12288_w4_sk1_kernel(const bfloat16_t* __restrict__ Cs, const float* __restrict__ Cw, const float* __restrict__ P, bfloat16_t* __restrict__ Sn, bfloat16_t* __restrict__ X, bfloat16_t* __restrict__ Y) {
  float xa[1];
  float ca[1];
  xa[0] = 0x0p+0f/*0.000000e+00*/;
  xa[0] = (xa[0] + P[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]);
  ca[0] = 0x0p+0f/*0.000000e+00*/;
  bfloat16_t xb = ((bfloat16_t)xa[0]);
  X[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] = xb;
  for (int t = 0; t < 3; ++t) {
    ca[0] = (ca[0] + (((float)Cs[((((((int)blockIdx.x) * 36864) + (t * 12288)) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]) * Cw[(((t * 12288) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]));
    bfloat16_t condval;
    if ((t < 2)) {
      condval = Cs[(((((((int)blockIdx.x) * 36864) + (t * 12288)) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x)) + 12288)];
    } else {
      condval = xb;
    }
    Sn[((((((int)blockIdx.x) * 36864) + (t * 12288)) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] = condval;
  }
  ca[0] = (ca[0] + (((float)xb) * Cw[(((((int)blockIdx.y) * 256) + ((int)threadIdx.x)) + 36864)]));
  float sb = ((float)((bfloat16_t)ca[0]));
  Y[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] = ((bfloat16_t)(sb * (0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - sb))))));
}


extern "C" __global__ void k3_conv_silu_b32_kp12288_w4_sk1_kernel(const bfloat16_t* __restrict__ Cs, const float* __restrict__ Cw, const float* __restrict__ P, bfloat16_t* __restrict__ Sn, bfloat16_t* __restrict__ X, bfloat16_t* __restrict__ Y);
extern "C" __global__ void __launch_bounds__(256, 1) k3_conv_silu_b32_kp12288_w4_sk1_kernel(const bfloat16_t* __restrict__ Cs, const float* __restrict__ Cw, const float* __restrict__ P, bfloat16_t* __restrict__ Sn, bfloat16_t* __restrict__ X, bfloat16_t* __restrict__ Y) {
  float xa[1];
  float ca[1];
  xa[0] = 0x0p+0f/*0.000000e+00*/;
  xa[0] = (xa[0] + P[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]);
  ca[0] = 0x0p+0f/*0.000000e+00*/;
  bfloat16_t xb = ((bfloat16_t)xa[0]);
  X[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] = xb;
  for (int t = 0; t < 3; ++t) {
    ca[0] = (ca[0] + (((float)Cs[((((((int)blockIdx.x) * 36864) + (t * 12288)) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]) * Cw[(((t * 12288) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]));
    bfloat16_t condval;
    if ((t < 2)) {
      condval = Cs[(((((((int)blockIdx.x) * 36864) + (t * 12288)) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x)) + 12288)];
    } else {
      condval = xb;
    }
    Sn[((((((int)blockIdx.x) * 36864) + (t * 12288)) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] = condval;
  }
  ca[0] = (ca[0] + (((float)xb) * Cw[(((((int)blockIdx.y) * 256) + ((int)threadIdx.x)) + 36864)]));
  float sb = ((float)((bfloat16_t)ca[0]));
  Y[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] = ((bfloat16_t)(sb * (0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - sb))))));
}


extern "C" __global__ void k3_conv_silu_b48_kp12288_w4_sk1_kernel(const bfloat16_t* __restrict__ Cs, const float* __restrict__ Cw, const float* __restrict__ P, bfloat16_t* __restrict__ Sn, bfloat16_t* __restrict__ X, bfloat16_t* __restrict__ Y);
extern "C" __global__ void __launch_bounds__(256, 1) k3_conv_silu_b48_kp12288_w4_sk1_kernel(const bfloat16_t* __restrict__ Cs, const float* __restrict__ Cw, const float* __restrict__ P, bfloat16_t* __restrict__ Sn, bfloat16_t* __restrict__ X, bfloat16_t* __restrict__ Y) {
  float xa[1];
  float ca[1];
  xa[0] = 0x0p+0f/*0.000000e+00*/;
  xa[0] = (xa[0] + P[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]);
  ca[0] = 0x0p+0f/*0.000000e+00*/;
  bfloat16_t xb = ((bfloat16_t)xa[0]);
  X[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] = xb;
  for (int t = 0; t < 3; ++t) {
    ca[0] = (ca[0] + (((float)Cs[((((((int)blockIdx.x) * 36864) + (t * 12288)) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]) * Cw[(((t * 12288) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]));
    bfloat16_t condval;
    if ((t < 2)) {
      condval = Cs[(((((((int)blockIdx.x) * 36864) + (t * 12288)) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x)) + 12288)];
    } else {
      condval = xb;
    }
    Sn[((((((int)blockIdx.x) * 36864) + (t * 12288)) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] = condval;
  }
  ca[0] = (ca[0] + (((float)xb) * Cw[(((((int)blockIdx.y) * 256) + ((int)threadIdx.x)) + 36864)]));
  float sb = ((float)((bfloat16_t)ca[0]));
  Y[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] = ((bfloat16_t)(sb * (0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - sb))))));
}


extern "C" __global__ void k3_conv_silu_b64_kp12288_w4_sk1_kernel(const bfloat16_t* __restrict__ Cs, const float* __restrict__ Cw, const float* __restrict__ P, bfloat16_t* __restrict__ Sn, bfloat16_t* __restrict__ X, bfloat16_t* __restrict__ Y);
extern "C" __global__ void __launch_bounds__(256, 1) k3_conv_silu_b64_kp12288_w4_sk1_kernel(const bfloat16_t* __restrict__ Cs, const float* __restrict__ Cw, const float* __restrict__ P, bfloat16_t* __restrict__ Sn, bfloat16_t* __restrict__ X, bfloat16_t* __restrict__ Y) {
  float xa[1];
  float ca[1];
  xa[0] = 0x0p+0f/*0.000000e+00*/;
  xa[0] = (xa[0] + P[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]);
  ca[0] = 0x0p+0f/*0.000000e+00*/;
  bfloat16_t xb = ((bfloat16_t)xa[0]);
  X[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] = xb;
  for (int t = 0; t < 3; ++t) {
    ca[0] = (ca[0] + (((float)Cs[((((((int)blockIdx.x) * 36864) + (t * 12288)) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]) * Cw[(((t * 12288) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]));
    bfloat16_t condval;
    if ((t < 2)) {
      condval = Cs[(((((((int)blockIdx.x) * 36864) + (t * 12288)) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x)) + 12288)];
    } else {
      condval = xb;
    }
    Sn[((((((int)blockIdx.x) * 36864) + (t * 12288)) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] = condval;
  }
  ca[0] = (ca[0] + (((float)xb) * Cw[(((((int)blockIdx.y) * 256) + ((int)threadIdx.x)) + 36864)]));
  float sb = ((float)((bfloat16_t)ca[0]));
  Y[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] = ((bfloat16_t)(sb * (0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - sb))))));
}


extern "C" __global__ void k3_conv_silu_b96_kp12288_w4_sk1_kernel(const bfloat16_t* __restrict__ Cs, const float* __restrict__ Cw, const float* __restrict__ P, bfloat16_t* __restrict__ Sn, bfloat16_t* __restrict__ X, bfloat16_t* __restrict__ Y);
extern "C" __global__ void __launch_bounds__(256, 1) k3_conv_silu_b96_kp12288_w4_sk1_kernel(const bfloat16_t* __restrict__ Cs, const float* __restrict__ Cw, const float* __restrict__ P, bfloat16_t* __restrict__ Sn, bfloat16_t* __restrict__ X, bfloat16_t* __restrict__ Y) {
  float xa[1];
  float ca[1];
  xa[0] = 0x0p+0f/*0.000000e+00*/;
  xa[0] = (xa[0] + P[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]);
  ca[0] = 0x0p+0f/*0.000000e+00*/;
  bfloat16_t xb = ((bfloat16_t)xa[0]);
  X[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] = xb;
  for (int t = 0; t < 3; ++t) {
    ca[0] = (ca[0] + (((float)Cs[((((((int)blockIdx.x) * 36864) + (t * 12288)) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]) * Cw[(((t * 12288) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]));
    bfloat16_t condval;
    if ((t < 2)) {
      condval = Cs[(((((((int)blockIdx.x) * 36864) + (t * 12288)) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x)) + 12288)];
    } else {
      condval = xb;
    }
    Sn[((((((int)blockIdx.x) * 36864) + (t * 12288)) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] = condval;
  }
  ca[0] = (ca[0] + (((float)xb) * Cw[(((((int)blockIdx.y) * 256) + ((int)threadIdx.x)) + 36864)]));
  float sb = ((float)((bfloat16_t)ca[0]));
  Y[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] = ((bfloat16_t)(sb * (0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - sb))))));
}


extern "C" __global__ void k3_conv_silu_b128_kp12288_w4_sk1_kernel(const bfloat16_t* __restrict__ Cs, const float* __restrict__ Cw, const float* __restrict__ P, bfloat16_t* __restrict__ Sn, bfloat16_t* __restrict__ X, bfloat16_t* __restrict__ Y);
extern "C" __global__ void __launch_bounds__(256, 1) k3_conv_silu_b128_kp12288_w4_sk1_kernel(const bfloat16_t* __restrict__ Cs, const float* __restrict__ Cw, const float* __restrict__ P, bfloat16_t* __restrict__ Sn, bfloat16_t* __restrict__ X, bfloat16_t* __restrict__ Y) {
  float xa[1];
  float ca[1];
  xa[0] = 0x0p+0f/*0.000000e+00*/;
  xa[0] = (xa[0] + P[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]);
  ca[0] = 0x0p+0f/*0.000000e+00*/;
  bfloat16_t xb = ((bfloat16_t)xa[0]);
  X[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] = xb;
  for (int t = 0; t < 3; ++t) {
    ca[0] = (ca[0] + (((float)Cs[((((((int)blockIdx.x) * 36864) + (t * 12288)) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]) * Cw[(((t * 12288) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]));
    bfloat16_t condval;
    if ((t < 2)) {
      condval = Cs[(((((((int)blockIdx.x) * 36864) + (t * 12288)) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x)) + 12288)];
    } else {
      condval = xb;
    }
    Sn[((((((int)blockIdx.x) * 36864) + (t * 12288)) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] = condval;
  }
  ca[0] = (ca[0] + (((float)xb) * Cw[(((((int)blockIdx.y) * 256) + ((int)threadIdx.x)) + 36864)]));
  float sb = ((float)((bfloat16_t)ca[0]));
  Y[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] = ((bfloat16_t)(sb * (0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - sb))))));
}



// Causal depthwise convolution over the `width`-slot window plus silu,
// one token per row. The projection partial's bf16 landing is written to
// X and is also the newest window slot; Sn is the shifted window the
// caller carries. Conv weights Cw are f32 and have no batch axis; the
// window state is [b, width-1, kp], one independent window per row.
extern "C" int k3_conv_silu_batched(
    const float* P,
    const float* Cw,
    const void* Cs,
    void* X,
    void* Y,
    void* Sn,
    int b,
    int kp,
    int width,
    int split_k,
    cudaStream_t stream) {
  if (b == 1 && kp == 12288 && width == 4 && split_k == 1) {
    k3_conv_silu_b1_kp12288_w4_sk1_kernel<<<dim3(1, 48, 1), 256, 0, stream>>>(
        reinterpret_cast<const bfloat16_t*>(Cs),
        Cw,
        P,
        reinterpret_cast<bfloat16_t*>(Sn),
        reinterpret_cast<bfloat16_t*>(X),
        reinterpret_cast<bfloat16_t*>(Y));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 2 && kp == 12288 && width == 4 && split_k == 1) {
    k3_conv_silu_b2_kp12288_w4_sk1_kernel<<<dim3(2, 48, 1), 256, 0, stream>>>(
        reinterpret_cast<const bfloat16_t*>(Cs),
        Cw,
        P,
        reinterpret_cast<bfloat16_t*>(Sn),
        reinterpret_cast<bfloat16_t*>(X),
        reinterpret_cast<bfloat16_t*>(Y));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 4 && kp == 12288 && width == 4 && split_k == 1) {
    k3_conv_silu_b4_kp12288_w4_sk1_kernel<<<dim3(4, 48, 1), 256, 0, stream>>>(
        reinterpret_cast<const bfloat16_t*>(Cs),
        Cw,
        P,
        reinterpret_cast<bfloat16_t*>(Sn),
        reinterpret_cast<bfloat16_t*>(X),
        reinterpret_cast<bfloat16_t*>(Y));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 8 && kp == 12288 && width == 4 && split_k == 1) {
    k3_conv_silu_b8_kp12288_w4_sk1_kernel<<<dim3(8, 48, 1), 256, 0, stream>>>(
        reinterpret_cast<const bfloat16_t*>(Cs),
        Cw,
        P,
        reinterpret_cast<bfloat16_t*>(Sn),
        reinterpret_cast<bfloat16_t*>(X),
        reinterpret_cast<bfloat16_t*>(Y));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 16 && kp == 12288 && width == 4 && split_k == 1) {
    k3_conv_silu_b16_kp12288_w4_sk1_kernel<<<dim3(16, 48, 1), 256, 0, stream>>>(
        reinterpret_cast<const bfloat16_t*>(Cs),
        Cw,
        P,
        reinterpret_cast<bfloat16_t*>(Sn),
        reinterpret_cast<bfloat16_t*>(X),
        reinterpret_cast<bfloat16_t*>(Y));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 32 && kp == 12288 && width == 4 && split_k == 1) {
    k3_conv_silu_b32_kp12288_w4_sk1_kernel<<<dim3(32, 48, 1), 256, 0, stream>>>(
        reinterpret_cast<const bfloat16_t*>(Cs),
        Cw,
        P,
        reinterpret_cast<bfloat16_t*>(Sn),
        reinterpret_cast<bfloat16_t*>(X),
        reinterpret_cast<bfloat16_t*>(Y));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 48 && kp == 12288 && width == 4 && split_k == 1) {
    k3_conv_silu_b48_kp12288_w4_sk1_kernel<<<dim3(48, 48, 1), 256, 0, stream>>>(
        reinterpret_cast<const bfloat16_t*>(Cs),
        Cw,
        P,
        reinterpret_cast<bfloat16_t*>(Sn),
        reinterpret_cast<bfloat16_t*>(X),
        reinterpret_cast<bfloat16_t*>(Y));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 64 && kp == 12288 && width == 4 && split_k == 1) {
    k3_conv_silu_b64_kp12288_w4_sk1_kernel<<<dim3(64, 48, 1), 256, 0, stream>>>(
        reinterpret_cast<const bfloat16_t*>(Cs),
        Cw,
        P,
        reinterpret_cast<bfloat16_t*>(Sn),
        reinterpret_cast<bfloat16_t*>(X),
        reinterpret_cast<bfloat16_t*>(Y));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 96 && kp == 12288 && width == 4 && split_k == 1) {
    k3_conv_silu_b96_kp12288_w4_sk1_kernel<<<dim3(96, 48, 1), 256, 0, stream>>>(
        reinterpret_cast<const bfloat16_t*>(Cs),
        Cw,
        P,
        reinterpret_cast<bfloat16_t*>(Sn),
        reinterpret_cast<bfloat16_t*>(X),
        reinterpret_cast<bfloat16_t*>(Y));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 128 && kp == 12288 && width == 4 && split_k == 1) {
    k3_conv_silu_b128_kp12288_w4_sk1_kernel<<<dim3(128, 48, 1), 256, 0, stream>>>(
        reinterpret_cast<const bfloat16_t*>(Cs),
        Cw,
        P,
        reinterpret_cast<bfloat16_t*>(Sn),
        reinterpret_cast<bfloat16_t*>(X),
        reinterpret_cast<bfloat16_t*>(Y));
    return static_cast<int>(cudaGetLastError());
  }
  return static_cast<int>(cudaErrorInvalidValue);
}
