// Generated by pegainfer-k3/kernels/generate.py -- do not edit.
#include <cuda_runtime.h>

#if defined(_MSC_VER) && !defined(__clang__) && _MSC_VER < 1940
#define _tl_orig_alignas alignas
#define alignas(N) _tl_orig_alignas((N) <= 64 ? (N) : 64)
#include <cuda.h>
#undef alignas
#define alignas _tl_orig_alignas
#endif
#include <tl_templates/cuda/reduce.h>
#include <tl_templates/cuda/scan.h>
#include <tl_templates/cuda/ldsm.h>
#include <tl_templates/cuda/threadblock_swizzle.h>
#define debug_print_msg k3_kda_core_batched_debug_print_msg
#define debug_print_buffer_value k3_kda_core_batched_debug_print_buffer_value
#include <tl_templates/cuda/debug.h>
#undef debug_print_msg
#undef debug_print_buffer_value
#ifdef ENABLE_BF16
#include <tl_templates/cuda/cuda_bf16_fallbacks.cuh>
#endif

extern "C" __global__ void k3_kda_core_b1_kh96_kd128_kernel(const float* __restrict__ Alog, const bfloat16_t* __restrict__ Bt, const float* __restrict__ Dt, const bfloat16_t* __restrict__ G2, const float* __restrict__ GP, const float* __restrict__ Go, const bfloat16_t* __restrict__ K, bfloat16_t* __restrict__ Out, const bfloat16_t* __restrict__ Q, const float* __restrict__ State, float* __restrict__ StateN, const bfloat16_t* __restrict__ V);
extern "C" __global__ void __launch_bounds__(128, 1) k3_kda_core_b1_kh96_kd128_kernel(const float* __restrict__ Alog, const bfloat16_t* __restrict__ Bt, const float* __restrict__ Dt, const bfloat16_t* __restrict__ G2, const float* __restrict__ GP, const float* __restrict__ Go, const bfloat16_t* __restrict__ K, bfloat16_t* __restrict__ Out, const bfloat16_t* __restrict__ Q, const float* __restrict__ State, float* __restrict__ StateN, const bfloat16_t* __restrict__ V) {
  extern __shared__ __align__(1024) uchar buf_dyn_shmem[];
  void* attnb = ((void*)((char*)buf_dyn_shmem + 0));
  void* qss = ((void*)((char*)buf_dyn_shmem + 0));
  void* workspace = ((void*)((char*)buf_dyn_shmem + 0));
  void* workspace_1 = ((void*)((char*)buf_dyn_shmem + 0));
  void* workspace_2 = ((void*)((char*)buf_dyn_shmem + 256));
  void* kns = ((void*)((char*)buf_dyn_shmem + 512));
  void* decs = ((void*)((char*)buf_dyn_shmem + 1024));
  float qsq[1];
  float ksq[1];
  float qtot[1];
  float ktot[1];
  float ga[1];
  float mfr[1];
  float afr[1];
  float dfr[1];
  float asq[1];
  float atot[1];
  qsq[0] = ((float)(Q[((((int)blockIdx.y) * 128) + ((int)threadIdx.x))] * Q[((((int)blockIdx.y) * 128) + ((int)threadIdx.x))]));
  ksq[0] = ((float)(K[((((int)blockIdx.y) * 128) + ((int)threadIdx.x))] * K[((((int)blockIdx.y) * 128) + ((int)threadIdx.x))]));
  qtot[0] = 0x0p+0f/*0.000000e+00*/;
  qtot[0] = (qtot[0] + qsq[0]);
  qtot[0] = tl::AllReduce<tl::SumOp, 128, 1, 0, tl::NamedBarrier<128>>::run(qtot[0], (&(((float*)workspace_1)[0])));
  ktot[0] = 0x0p+0f/*0.000000e+00*/;
  ktot[0] = (ktot[0] + ksq[0]);
  __syncthreads();
  ktot[0] = tl::AllReduce<tl::SumOp, 128, 1, 0, tl::NamedBarrier<128>>::run(ktot[0], (&(((float*)workspace)[0])));
  ga[0] = 0x0p+0f/*0.000000e+00*/;
  bfloat16_t qr = ((bfloat16_t)rsqrtf((((float)((bfloat16_t)qtot[0])) + 0x1.0c6f7a0b5ed8dp-20f/*1.000000e-06*/)));
  bfloat16_t kr = ((bfloat16_t)rsqrtf((((float)((bfloat16_t)ktot[0])) + 0x1.0c6f7a0b5ed8dp-20f/*1.000000e-06*/)));
  __syncthreads();
  ((float*)qss)[((int)threadIdx.x)] = (((float)(Q[((((int)blockIdx.y) * 128) + ((int)threadIdx.x))] * qr)) * 0x1.6a09e667f3bcdp-4f/*8.838835e-02*/);
  ((float*)kns)[((int)threadIdx.x)] = ((float)(K[((((int)blockIdx.y) * 128) + ((int)threadIdx.x))] * kr));
  ga[0] = (ga[0] + GP[((((int)blockIdx.y) * 128) + ((int)threadIdx.x))]);
  float raw = (((float)((bfloat16_t)ga[0])) + Dt[((((int)blockIdx.y) * 128) + ((int)threadIdx.x))]);
  ((float*)decs)[((int)threadIdx.x)] = expf((-0x1.4p+2f/*-5.000000e+00*/ * (0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - (expf(Alog[((int)blockIdx.y)]) * raw)))))));
  __syncthreads();
  mfr[0] = 0x0p+0f/*0.000000e+00*/;
  afr[0] = 0x0p+0f/*0.000000e+00*/;
  for (int k = 0; k < 128; ++k) {
    mfr[0] = (mfr[0] + ((State[(((((int)blockIdx.y) * 16384) + (((int)threadIdx.x) * 128)) + k)] * ((float*)decs)[k]) * ((float*)kns)[k]));
  }
  dfr[0] = ((((float)V[((((int)blockIdx.y) * 128) + ((int)threadIdx.x))]) - mfr[0]) * (0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - ((float)Bt[((int)blockIdx.y)]))))));
  for (int k_1 = 0; k_1 < 128; ++k_1) {
    StateN[(((((int)blockIdx.y) * 16384) + (((int)threadIdx.x) * 128)) + k_1)] = ((State[(((((int)blockIdx.y) * 16384) + (((int)threadIdx.x) * 128)) + k_1)] * ((float*)decs)[k_1]) + (dfr[0] * ((float*)kns)[k_1]));
    afr[0] = (afr[0] + (StateN[(((((int)blockIdx.y) * 16384) + (((int)threadIdx.x) * 128)) + k_1)] * ((float*)qss)[k_1]));
  }
  __syncthreads();
  ((bfloat16_t*)attnb)[((int)threadIdx.x)] = ((bfloat16_t)afr[0]);
  __syncthreads();
  asq[0] = (((float)((bfloat16_t*)attnb)[((int)threadIdx.x)]) * ((float)((bfloat16_t*)attnb)[((int)threadIdx.x)]));
  atot[0] = 0x0p+0f/*0.000000e+00*/;
  atot[0] = (atot[0] + asq[0]);
  __syncthreads();
  atot[0] = tl::AllReduce<tl::SumOp, 128, 1, 0, tl::NamedBarrier<128>>::run(atot[0], (&(((float*)workspace_2)[0])));
  __syncthreads();
  Out[((((int)blockIdx.y) * 128) + ((int)threadIdx.x))] = (((bfloat16_t)((((float)((bfloat16_t*)attnb)[((int)threadIdx.x)]) * rsqrtf(((atot[0] / 0x1p+7f/*1.280000e+02*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/))) * Go[((int)threadIdx.x)])) * ((bfloat16_t)(0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - ((float)G2[((((int)blockIdx.y) * 128) + ((int)threadIdx.x))])))))));
}


extern "C" __global__ void k3_kda_core_b2_kh96_kd128_kernel(const float* __restrict__ Alog, const bfloat16_t* __restrict__ Bt, const float* __restrict__ Dt, const bfloat16_t* __restrict__ G2, const float* __restrict__ GP, const float* __restrict__ Go, const bfloat16_t* __restrict__ K, bfloat16_t* __restrict__ Out, const bfloat16_t* __restrict__ Q, const float* __restrict__ State, float* __restrict__ StateN, const bfloat16_t* __restrict__ V);
extern "C" __global__ void __launch_bounds__(128, 1) k3_kda_core_b2_kh96_kd128_kernel(const float* __restrict__ Alog, const bfloat16_t* __restrict__ Bt, const float* __restrict__ Dt, const bfloat16_t* __restrict__ G2, const float* __restrict__ GP, const float* __restrict__ Go, const bfloat16_t* __restrict__ K, bfloat16_t* __restrict__ Out, const bfloat16_t* __restrict__ Q, const float* __restrict__ State, float* __restrict__ StateN, const bfloat16_t* __restrict__ V) {
  extern __shared__ __align__(1024) uchar buf_dyn_shmem[];
  void* attnb = ((void*)((char*)buf_dyn_shmem + 0));
  void* qss = ((void*)((char*)buf_dyn_shmem + 0));
  void* workspace = ((void*)((char*)buf_dyn_shmem + 0));
  void* workspace_1 = ((void*)((char*)buf_dyn_shmem + 0));
  void* workspace_2 = ((void*)((char*)buf_dyn_shmem + 256));
  void* kns = ((void*)((char*)buf_dyn_shmem + 512));
  void* decs = ((void*)((char*)buf_dyn_shmem + 1024));
  float qsq[1];
  float ksq[1];
  float qtot[1];
  float ktot[1];
  float ga[1];
  float mfr[1];
  float afr[1];
  float dfr[1];
  float asq[1];
  float atot[1];
  qsq[0] = ((float)(Q[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))] * Q[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))]));
  ksq[0] = ((float)(K[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))] * K[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))]));
  qtot[0] = 0x0p+0f/*0.000000e+00*/;
  qtot[0] = (qtot[0] + qsq[0]);
  qtot[0] = tl::AllReduce<tl::SumOp, 128, 1, 0, tl::NamedBarrier<128>>::run(qtot[0], (&(((float*)workspace_1)[0])));
  ktot[0] = 0x0p+0f/*0.000000e+00*/;
  ktot[0] = (ktot[0] + ksq[0]);
  __syncthreads();
  ktot[0] = tl::AllReduce<tl::SumOp, 128, 1, 0, tl::NamedBarrier<128>>::run(ktot[0], (&(((float*)workspace)[0])));
  ga[0] = 0x0p+0f/*0.000000e+00*/;
  bfloat16_t qr = ((bfloat16_t)rsqrtf((((float)((bfloat16_t)qtot[0])) + 0x1.0c6f7a0b5ed8dp-20f/*1.000000e-06*/)));
  bfloat16_t kr = ((bfloat16_t)rsqrtf((((float)((bfloat16_t)ktot[0])) + 0x1.0c6f7a0b5ed8dp-20f/*1.000000e-06*/)));
  __syncthreads();
  ((float*)qss)[((int)threadIdx.x)] = (((float)(Q[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))] * qr)) * 0x1.6a09e667f3bcdp-4f/*8.838835e-02*/);
  ((float*)kns)[((int)threadIdx.x)] = ((float)(K[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))] * kr));
  ga[0] = (ga[0] + GP[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))]);
  float raw = (((float)((bfloat16_t)ga[0])) + Dt[((((int)blockIdx.y) * 128) + ((int)threadIdx.x))]);
  ((float*)decs)[((int)threadIdx.x)] = expf((-0x1.4p+2f/*-5.000000e+00*/ * (0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - (expf(Alog[((int)blockIdx.y)]) * raw)))))));
  __syncthreads();
  mfr[0] = 0x0p+0f/*0.000000e+00*/;
  afr[0] = 0x0p+0f/*0.000000e+00*/;
  for (int k = 0; k < 128; ++k) {
    mfr[0] = (mfr[0] + ((State[((((((int)blockIdx.x) * 1572864) + (((int)blockIdx.y) * 16384)) + (((int)threadIdx.x) * 128)) + k)] * ((float*)decs)[k]) * ((float*)kns)[k]));
  }
  dfr[0] = ((((float)V[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))]) - mfr[0]) * (0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - ((float)Bt[((((int)blockIdx.x) * 96) + ((int)blockIdx.y))]))))));
  for (int k_1 = 0; k_1 < 128; ++k_1) {
    StateN[((((((int)blockIdx.x) * 1572864) + (((int)blockIdx.y) * 16384)) + (((int)threadIdx.x) * 128)) + k_1)] = ((State[((((((int)blockIdx.x) * 1572864) + (((int)blockIdx.y) * 16384)) + (((int)threadIdx.x) * 128)) + k_1)] * ((float*)decs)[k_1]) + (dfr[0] * ((float*)kns)[k_1]));
    afr[0] = (afr[0] + (StateN[((((((int)blockIdx.x) * 1572864) + (((int)blockIdx.y) * 16384)) + (((int)threadIdx.x) * 128)) + k_1)] * ((float*)qss)[k_1]));
  }
  __syncthreads();
  ((bfloat16_t*)attnb)[((int)threadIdx.x)] = ((bfloat16_t)afr[0]);
  __syncthreads();
  asq[0] = (((float)((bfloat16_t*)attnb)[((int)threadIdx.x)]) * ((float)((bfloat16_t*)attnb)[((int)threadIdx.x)]));
  atot[0] = 0x0p+0f/*0.000000e+00*/;
  atot[0] = (atot[0] + asq[0]);
  __syncthreads();
  atot[0] = tl::AllReduce<tl::SumOp, 128, 1, 0, tl::NamedBarrier<128>>::run(atot[0], (&(((float*)workspace_2)[0])));
  __syncthreads();
  Out[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))] = (((bfloat16_t)((((float)((bfloat16_t*)attnb)[((int)threadIdx.x)]) * rsqrtf(((atot[0] / 0x1p+7f/*1.280000e+02*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/))) * Go[((int)threadIdx.x)])) * ((bfloat16_t)(0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - ((float)G2[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))])))))));
}


extern "C" __global__ void k3_kda_core_b4_kh96_kd128_kernel(const float* __restrict__ Alog, const bfloat16_t* __restrict__ Bt, const float* __restrict__ Dt, const bfloat16_t* __restrict__ G2, const float* __restrict__ GP, const float* __restrict__ Go, const bfloat16_t* __restrict__ K, bfloat16_t* __restrict__ Out, const bfloat16_t* __restrict__ Q, const float* __restrict__ State, float* __restrict__ StateN, const bfloat16_t* __restrict__ V);
extern "C" __global__ void __launch_bounds__(128, 1) k3_kda_core_b4_kh96_kd128_kernel(const float* __restrict__ Alog, const bfloat16_t* __restrict__ Bt, const float* __restrict__ Dt, const bfloat16_t* __restrict__ G2, const float* __restrict__ GP, const float* __restrict__ Go, const bfloat16_t* __restrict__ K, bfloat16_t* __restrict__ Out, const bfloat16_t* __restrict__ Q, const float* __restrict__ State, float* __restrict__ StateN, const bfloat16_t* __restrict__ V) {
  extern __shared__ __align__(1024) uchar buf_dyn_shmem[];
  void* attnb = ((void*)((char*)buf_dyn_shmem + 0));
  void* qss = ((void*)((char*)buf_dyn_shmem + 0));
  void* workspace = ((void*)((char*)buf_dyn_shmem + 0));
  void* workspace_1 = ((void*)((char*)buf_dyn_shmem + 0));
  void* workspace_2 = ((void*)((char*)buf_dyn_shmem + 256));
  void* kns = ((void*)((char*)buf_dyn_shmem + 512));
  void* decs = ((void*)((char*)buf_dyn_shmem + 1024));
  float qsq[1];
  float ksq[1];
  float qtot[1];
  float ktot[1];
  float ga[1];
  float mfr[1];
  float afr[1];
  float dfr[1];
  float asq[1];
  float atot[1];
  qsq[0] = ((float)(Q[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))] * Q[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))]));
  ksq[0] = ((float)(K[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))] * K[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))]));
  qtot[0] = 0x0p+0f/*0.000000e+00*/;
  qtot[0] = (qtot[0] + qsq[0]);
  qtot[0] = tl::AllReduce<tl::SumOp, 128, 1, 0, tl::NamedBarrier<128>>::run(qtot[0], (&(((float*)workspace_1)[0])));
  ktot[0] = 0x0p+0f/*0.000000e+00*/;
  ktot[0] = (ktot[0] + ksq[0]);
  __syncthreads();
  ktot[0] = tl::AllReduce<tl::SumOp, 128, 1, 0, tl::NamedBarrier<128>>::run(ktot[0], (&(((float*)workspace)[0])));
  ga[0] = 0x0p+0f/*0.000000e+00*/;
  bfloat16_t qr = ((bfloat16_t)rsqrtf((((float)((bfloat16_t)qtot[0])) + 0x1.0c6f7a0b5ed8dp-20f/*1.000000e-06*/)));
  bfloat16_t kr = ((bfloat16_t)rsqrtf((((float)((bfloat16_t)ktot[0])) + 0x1.0c6f7a0b5ed8dp-20f/*1.000000e-06*/)));
  __syncthreads();
  ((float*)qss)[((int)threadIdx.x)] = (((float)(Q[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))] * qr)) * 0x1.6a09e667f3bcdp-4f/*8.838835e-02*/);
  ((float*)kns)[((int)threadIdx.x)] = ((float)(K[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))] * kr));
  ga[0] = (ga[0] + GP[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))]);
  float raw = (((float)((bfloat16_t)ga[0])) + Dt[((((int)blockIdx.y) * 128) + ((int)threadIdx.x))]);
  ((float*)decs)[((int)threadIdx.x)] = expf((-0x1.4p+2f/*-5.000000e+00*/ * (0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - (expf(Alog[((int)blockIdx.y)]) * raw)))))));
  __syncthreads();
  mfr[0] = 0x0p+0f/*0.000000e+00*/;
  afr[0] = 0x0p+0f/*0.000000e+00*/;
  for (int k = 0; k < 128; ++k) {
    mfr[0] = (mfr[0] + ((State[((((((int)blockIdx.x) * 1572864) + (((int)blockIdx.y) * 16384)) + (((int)threadIdx.x) * 128)) + k)] * ((float*)decs)[k]) * ((float*)kns)[k]));
  }
  dfr[0] = ((((float)V[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))]) - mfr[0]) * (0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - ((float)Bt[((((int)blockIdx.x) * 96) + ((int)blockIdx.y))]))))));
  for (int k_1 = 0; k_1 < 128; ++k_1) {
    StateN[((((((int)blockIdx.x) * 1572864) + (((int)blockIdx.y) * 16384)) + (((int)threadIdx.x) * 128)) + k_1)] = ((State[((((((int)blockIdx.x) * 1572864) + (((int)blockIdx.y) * 16384)) + (((int)threadIdx.x) * 128)) + k_1)] * ((float*)decs)[k_1]) + (dfr[0] * ((float*)kns)[k_1]));
    afr[0] = (afr[0] + (StateN[((((((int)blockIdx.x) * 1572864) + (((int)blockIdx.y) * 16384)) + (((int)threadIdx.x) * 128)) + k_1)] * ((float*)qss)[k_1]));
  }
  __syncthreads();
  ((bfloat16_t*)attnb)[((int)threadIdx.x)] = ((bfloat16_t)afr[0]);
  __syncthreads();
  asq[0] = (((float)((bfloat16_t*)attnb)[((int)threadIdx.x)]) * ((float)((bfloat16_t*)attnb)[((int)threadIdx.x)]));
  atot[0] = 0x0p+0f/*0.000000e+00*/;
  atot[0] = (atot[0] + asq[0]);
  __syncthreads();
  atot[0] = tl::AllReduce<tl::SumOp, 128, 1, 0, tl::NamedBarrier<128>>::run(atot[0], (&(((float*)workspace_2)[0])));
  __syncthreads();
  Out[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))] = (((bfloat16_t)((((float)((bfloat16_t*)attnb)[((int)threadIdx.x)]) * rsqrtf(((atot[0] / 0x1p+7f/*1.280000e+02*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/))) * Go[((int)threadIdx.x)])) * ((bfloat16_t)(0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - ((float)G2[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))])))))));
}


extern "C" __global__ void k3_kda_core_b8_kh96_kd128_kernel(const float* __restrict__ Alog, const bfloat16_t* __restrict__ Bt, const float* __restrict__ Dt, const bfloat16_t* __restrict__ G2, const float* __restrict__ GP, const float* __restrict__ Go, const bfloat16_t* __restrict__ K, bfloat16_t* __restrict__ Out, const bfloat16_t* __restrict__ Q, const float* __restrict__ State, float* __restrict__ StateN, const bfloat16_t* __restrict__ V);
extern "C" __global__ void __launch_bounds__(128, 1) k3_kda_core_b8_kh96_kd128_kernel(const float* __restrict__ Alog, const bfloat16_t* __restrict__ Bt, const float* __restrict__ Dt, const bfloat16_t* __restrict__ G2, const float* __restrict__ GP, const float* __restrict__ Go, const bfloat16_t* __restrict__ K, bfloat16_t* __restrict__ Out, const bfloat16_t* __restrict__ Q, const float* __restrict__ State, float* __restrict__ StateN, const bfloat16_t* __restrict__ V) {
  extern __shared__ __align__(1024) uchar buf_dyn_shmem[];
  void* attnb = ((void*)((char*)buf_dyn_shmem + 0));
  void* qss = ((void*)((char*)buf_dyn_shmem + 0));
  void* workspace = ((void*)((char*)buf_dyn_shmem + 0));
  void* workspace_1 = ((void*)((char*)buf_dyn_shmem + 0));
  void* workspace_2 = ((void*)((char*)buf_dyn_shmem + 256));
  void* kns = ((void*)((char*)buf_dyn_shmem + 512));
  void* decs = ((void*)((char*)buf_dyn_shmem + 1024));
  float qsq[1];
  float ksq[1];
  float qtot[1];
  float ktot[1];
  float ga[1];
  float mfr[1];
  float afr[1];
  float dfr[1];
  float asq[1];
  float atot[1];
  qsq[0] = ((float)(Q[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))] * Q[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))]));
  ksq[0] = ((float)(K[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))] * K[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))]));
  qtot[0] = 0x0p+0f/*0.000000e+00*/;
  qtot[0] = (qtot[0] + qsq[0]);
  qtot[0] = tl::AllReduce<tl::SumOp, 128, 1, 0, tl::NamedBarrier<128>>::run(qtot[0], (&(((float*)workspace_1)[0])));
  ktot[0] = 0x0p+0f/*0.000000e+00*/;
  ktot[0] = (ktot[0] + ksq[0]);
  __syncthreads();
  ktot[0] = tl::AllReduce<tl::SumOp, 128, 1, 0, tl::NamedBarrier<128>>::run(ktot[0], (&(((float*)workspace)[0])));
  ga[0] = 0x0p+0f/*0.000000e+00*/;
  bfloat16_t qr = ((bfloat16_t)rsqrtf((((float)((bfloat16_t)qtot[0])) + 0x1.0c6f7a0b5ed8dp-20f/*1.000000e-06*/)));
  bfloat16_t kr = ((bfloat16_t)rsqrtf((((float)((bfloat16_t)ktot[0])) + 0x1.0c6f7a0b5ed8dp-20f/*1.000000e-06*/)));
  __syncthreads();
  ((float*)qss)[((int)threadIdx.x)] = (((float)(Q[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))] * qr)) * 0x1.6a09e667f3bcdp-4f/*8.838835e-02*/);
  ((float*)kns)[((int)threadIdx.x)] = ((float)(K[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))] * kr));
  ga[0] = (ga[0] + GP[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))]);
  float raw = (((float)((bfloat16_t)ga[0])) + Dt[((((int)blockIdx.y) * 128) + ((int)threadIdx.x))]);
  ((float*)decs)[((int)threadIdx.x)] = expf((-0x1.4p+2f/*-5.000000e+00*/ * (0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - (expf(Alog[((int)blockIdx.y)]) * raw)))))));
  __syncthreads();
  mfr[0] = 0x0p+0f/*0.000000e+00*/;
  afr[0] = 0x0p+0f/*0.000000e+00*/;
  for (int k = 0; k < 128; ++k) {
    mfr[0] = (mfr[0] + ((State[((((((int)blockIdx.x) * 1572864) + (((int)blockIdx.y) * 16384)) + (((int)threadIdx.x) * 128)) + k)] * ((float*)decs)[k]) * ((float*)kns)[k]));
  }
  dfr[0] = ((((float)V[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))]) - mfr[0]) * (0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - ((float)Bt[((((int)blockIdx.x) * 96) + ((int)blockIdx.y))]))))));
  for (int k_1 = 0; k_1 < 128; ++k_1) {
    StateN[((((((int)blockIdx.x) * 1572864) + (((int)blockIdx.y) * 16384)) + (((int)threadIdx.x) * 128)) + k_1)] = ((State[((((((int)blockIdx.x) * 1572864) + (((int)blockIdx.y) * 16384)) + (((int)threadIdx.x) * 128)) + k_1)] * ((float*)decs)[k_1]) + (dfr[0] * ((float*)kns)[k_1]));
    afr[0] = (afr[0] + (StateN[((((((int)blockIdx.x) * 1572864) + (((int)blockIdx.y) * 16384)) + (((int)threadIdx.x) * 128)) + k_1)] * ((float*)qss)[k_1]));
  }
  __syncthreads();
  ((bfloat16_t*)attnb)[((int)threadIdx.x)] = ((bfloat16_t)afr[0]);
  __syncthreads();
  asq[0] = (((float)((bfloat16_t*)attnb)[((int)threadIdx.x)]) * ((float)((bfloat16_t*)attnb)[((int)threadIdx.x)]));
  atot[0] = 0x0p+0f/*0.000000e+00*/;
  atot[0] = (atot[0] + asq[0]);
  __syncthreads();
  atot[0] = tl::AllReduce<tl::SumOp, 128, 1, 0, tl::NamedBarrier<128>>::run(atot[0], (&(((float*)workspace_2)[0])));
  __syncthreads();
  Out[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))] = (((bfloat16_t)((((float)((bfloat16_t*)attnb)[((int)threadIdx.x)]) * rsqrtf(((atot[0] / 0x1p+7f/*1.280000e+02*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/))) * Go[((int)threadIdx.x)])) * ((bfloat16_t)(0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - ((float)G2[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))])))))));
}


extern "C" __global__ void k3_kda_core_b16_kh96_kd128_kernel(const float* __restrict__ Alog, const bfloat16_t* __restrict__ Bt, const float* __restrict__ Dt, const bfloat16_t* __restrict__ G2, const float* __restrict__ GP, const float* __restrict__ Go, const bfloat16_t* __restrict__ K, bfloat16_t* __restrict__ Out, const bfloat16_t* __restrict__ Q, const float* __restrict__ State, float* __restrict__ StateN, const bfloat16_t* __restrict__ V);
extern "C" __global__ void __launch_bounds__(128, 1) k3_kda_core_b16_kh96_kd128_kernel(const float* __restrict__ Alog, const bfloat16_t* __restrict__ Bt, const float* __restrict__ Dt, const bfloat16_t* __restrict__ G2, const float* __restrict__ GP, const float* __restrict__ Go, const bfloat16_t* __restrict__ K, bfloat16_t* __restrict__ Out, const bfloat16_t* __restrict__ Q, const float* __restrict__ State, float* __restrict__ StateN, const bfloat16_t* __restrict__ V) {
  extern __shared__ __align__(1024) uchar buf_dyn_shmem[];
  void* attnb = ((void*)((char*)buf_dyn_shmem + 0));
  void* qss = ((void*)((char*)buf_dyn_shmem + 0));
  void* workspace = ((void*)((char*)buf_dyn_shmem + 0));
  void* workspace_1 = ((void*)((char*)buf_dyn_shmem + 0));
  void* workspace_2 = ((void*)((char*)buf_dyn_shmem + 256));
  void* kns = ((void*)((char*)buf_dyn_shmem + 512));
  void* decs = ((void*)((char*)buf_dyn_shmem + 1024));
  float qsq[1];
  float ksq[1];
  float qtot[1];
  float ktot[1];
  float ga[1];
  float mfr[1];
  float afr[1];
  float dfr[1];
  float asq[1];
  float atot[1];
  qsq[0] = ((float)(Q[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))] * Q[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))]));
  ksq[0] = ((float)(K[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))] * K[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))]));
  qtot[0] = 0x0p+0f/*0.000000e+00*/;
  qtot[0] = (qtot[0] + qsq[0]);
  qtot[0] = tl::AllReduce<tl::SumOp, 128, 1, 0, tl::NamedBarrier<128>>::run(qtot[0], (&(((float*)workspace_1)[0])));
  ktot[0] = 0x0p+0f/*0.000000e+00*/;
  ktot[0] = (ktot[0] + ksq[0]);
  __syncthreads();
  ktot[0] = tl::AllReduce<tl::SumOp, 128, 1, 0, tl::NamedBarrier<128>>::run(ktot[0], (&(((float*)workspace)[0])));
  ga[0] = 0x0p+0f/*0.000000e+00*/;
  bfloat16_t qr = ((bfloat16_t)rsqrtf((((float)((bfloat16_t)qtot[0])) + 0x1.0c6f7a0b5ed8dp-20f/*1.000000e-06*/)));
  bfloat16_t kr = ((bfloat16_t)rsqrtf((((float)((bfloat16_t)ktot[0])) + 0x1.0c6f7a0b5ed8dp-20f/*1.000000e-06*/)));
  __syncthreads();
  ((float*)qss)[((int)threadIdx.x)] = (((float)(Q[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))] * qr)) * 0x1.6a09e667f3bcdp-4f/*8.838835e-02*/);
  ((float*)kns)[((int)threadIdx.x)] = ((float)(K[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))] * kr));
  ga[0] = (ga[0] + GP[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))]);
  float raw = (((float)((bfloat16_t)ga[0])) + Dt[((((int)blockIdx.y) * 128) + ((int)threadIdx.x))]);
  ((float*)decs)[((int)threadIdx.x)] = expf((-0x1.4p+2f/*-5.000000e+00*/ * (0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - (expf(Alog[((int)blockIdx.y)]) * raw)))))));
  __syncthreads();
  mfr[0] = 0x0p+0f/*0.000000e+00*/;
  afr[0] = 0x0p+0f/*0.000000e+00*/;
  for (int k = 0; k < 128; ++k) {
    mfr[0] = (mfr[0] + ((State[((((((int)blockIdx.x) * 1572864) + (((int)blockIdx.y) * 16384)) + (((int)threadIdx.x) * 128)) + k)] * ((float*)decs)[k]) * ((float*)kns)[k]));
  }
  dfr[0] = ((((float)V[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))]) - mfr[0]) * (0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - ((float)Bt[((((int)blockIdx.x) * 96) + ((int)blockIdx.y))]))))));
  for (int k_1 = 0; k_1 < 128; ++k_1) {
    StateN[((((((int)blockIdx.x) * 1572864) + (((int)blockIdx.y) * 16384)) + (((int)threadIdx.x) * 128)) + k_1)] = ((State[((((((int)blockIdx.x) * 1572864) + (((int)blockIdx.y) * 16384)) + (((int)threadIdx.x) * 128)) + k_1)] * ((float*)decs)[k_1]) + (dfr[0] * ((float*)kns)[k_1]));
    afr[0] = (afr[0] + (StateN[((((((int)blockIdx.x) * 1572864) + (((int)blockIdx.y) * 16384)) + (((int)threadIdx.x) * 128)) + k_1)] * ((float*)qss)[k_1]));
  }
  __syncthreads();
  ((bfloat16_t*)attnb)[((int)threadIdx.x)] = ((bfloat16_t)afr[0]);
  __syncthreads();
  asq[0] = (((float)((bfloat16_t*)attnb)[((int)threadIdx.x)]) * ((float)((bfloat16_t*)attnb)[((int)threadIdx.x)]));
  atot[0] = 0x0p+0f/*0.000000e+00*/;
  atot[0] = (atot[0] + asq[0]);
  __syncthreads();
  atot[0] = tl::AllReduce<tl::SumOp, 128, 1, 0, tl::NamedBarrier<128>>::run(atot[0], (&(((float*)workspace_2)[0])));
  __syncthreads();
  Out[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))] = (((bfloat16_t)((((float)((bfloat16_t*)attnb)[((int)threadIdx.x)]) * rsqrtf(((atot[0] / 0x1p+7f/*1.280000e+02*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/))) * Go[((int)threadIdx.x)])) * ((bfloat16_t)(0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - ((float)G2[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))])))))));
}


extern "C" __global__ void k3_kda_core_b32_kh96_kd128_kernel(const float* __restrict__ Alog, const bfloat16_t* __restrict__ Bt, const float* __restrict__ Dt, const bfloat16_t* __restrict__ G2, const float* __restrict__ GP, const float* __restrict__ Go, const bfloat16_t* __restrict__ K, bfloat16_t* __restrict__ Out, const bfloat16_t* __restrict__ Q, const float* __restrict__ State, float* __restrict__ StateN, const bfloat16_t* __restrict__ V);
extern "C" __global__ void __launch_bounds__(128, 1) k3_kda_core_b32_kh96_kd128_kernel(const float* __restrict__ Alog, const bfloat16_t* __restrict__ Bt, const float* __restrict__ Dt, const bfloat16_t* __restrict__ G2, const float* __restrict__ GP, const float* __restrict__ Go, const bfloat16_t* __restrict__ K, bfloat16_t* __restrict__ Out, const bfloat16_t* __restrict__ Q, const float* __restrict__ State, float* __restrict__ StateN, const bfloat16_t* __restrict__ V) {
  extern __shared__ __align__(1024) uchar buf_dyn_shmem[];
  void* attnb = ((void*)((char*)buf_dyn_shmem + 0));
  void* qss = ((void*)((char*)buf_dyn_shmem + 0));
  void* workspace = ((void*)((char*)buf_dyn_shmem + 0));
  void* workspace_1 = ((void*)((char*)buf_dyn_shmem + 0));
  void* workspace_2 = ((void*)((char*)buf_dyn_shmem + 256));
  void* kns = ((void*)((char*)buf_dyn_shmem + 512));
  void* decs = ((void*)((char*)buf_dyn_shmem + 1024));
  float qsq[1];
  float ksq[1];
  float qtot[1];
  float ktot[1];
  float ga[1];
  float mfr[1];
  float afr[1];
  float dfr[1];
  float asq[1];
  float atot[1];
  qsq[0] = ((float)(Q[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))] * Q[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))]));
  ksq[0] = ((float)(K[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))] * K[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))]));
  qtot[0] = 0x0p+0f/*0.000000e+00*/;
  qtot[0] = (qtot[0] + qsq[0]);
  qtot[0] = tl::AllReduce<tl::SumOp, 128, 1, 0, tl::NamedBarrier<128>>::run(qtot[0], (&(((float*)workspace_1)[0])));
  ktot[0] = 0x0p+0f/*0.000000e+00*/;
  ktot[0] = (ktot[0] + ksq[0]);
  __syncthreads();
  ktot[0] = tl::AllReduce<tl::SumOp, 128, 1, 0, tl::NamedBarrier<128>>::run(ktot[0], (&(((float*)workspace)[0])));
  ga[0] = 0x0p+0f/*0.000000e+00*/;
  bfloat16_t qr = ((bfloat16_t)rsqrtf((((float)((bfloat16_t)qtot[0])) + 0x1.0c6f7a0b5ed8dp-20f/*1.000000e-06*/)));
  bfloat16_t kr = ((bfloat16_t)rsqrtf((((float)((bfloat16_t)ktot[0])) + 0x1.0c6f7a0b5ed8dp-20f/*1.000000e-06*/)));
  __syncthreads();
  ((float*)qss)[((int)threadIdx.x)] = (((float)(Q[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))] * qr)) * 0x1.6a09e667f3bcdp-4f/*8.838835e-02*/);
  ((float*)kns)[((int)threadIdx.x)] = ((float)(K[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))] * kr));
  ga[0] = (ga[0] + GP[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))]);
  float raw = (((float)((bfloat16_t)ga[0])) + Dt[((((int)blockIdx.y) * 128) + ((int)threadIdx.x))]);
  ((float*)decs)[((int)threadIdx.x)] = expf((-0x1.4p+2f/*-5.000000e+00*/ * (0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - (expf(Alog[((int)blockIdx.y)]) * raw)))))));
  __syncthreads();
  mfr[0] = 0x0p+0f/*0.000000e+00*/;
  afr[0] = 0x0p+0f/*0.000000e+00*/;
  for (int k = 0; k < 128; ++k) {
    mfr[0] = (mfr[0] + ((State[((((((int)blockIdx.x) * 1572864) + (((int)blockIdx.y) * 16384)) + (((int)threadIdx.x) * 128)) + k)] * ((float*)decs)[k]) * ((float*)kns)[k]));
  }
  dfr[0] = ((((float)V[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))]) - mfr[0]) * (0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - ((float)Bt[((((int)blockIdx.x) * 96) + ((int)blockIdx.y))]))))));
  for (int k_1 = 0; k_1 < 128; ++k_1) {
    StateN[((((((int)blockIdx.x) * 1572864) + (((int)blockIdx.y) * 16384)) + (((int)threadIdx.x) * 128)) + k_1)] = ((State[((((((int)blockIdx.x) * 1572864) + (((int)blockIdx.y) * 16384)) + (((int)threadIdx.x) * 128)) + k_1)] * ((float*)decs)[k_1]) + (dfr[0] * ((float*)kns)[k_1]));
    afr[0] = (afr[0] + (StateN[((((((int)blockIdx.x) * 1572864) + (((int)blockIdx.y) * 16384)) + (((int)threadIdx.x) * 128)) + k_1)] * ((float*)qss)[k_1]));
  }
  __syncthreads();
  ((bfloat16_t*)attnb)[((int)threadIdx.x)] = ((bfloat16_t)afr[0]);
  __syncthreads();
  asq[0] = (((float)((bfloat16_t*)attnb)[((int)threadIdx.x)]) * ((float)((bfloat16_t*)attnb)[((int)threadIdx.x)]));
  atot[0] = 0x0p+0f/*0.000000e+00*/;
  atot[0] = (atot[0] + asq[0]);
  __syncthreads();
  atot[0] = tl::AllReduce<tl::SumOp, 128, 1, 0, tl::NamedBarrier<128>>::run(atot[0], (&(((float*)workspace_2)[0])));
  __syncthreads();
  Out[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))] = (((bfloat16_t)((((float)((bfloat16_t*)attnb)[((int)threadIdx.x)]) * rsqrtf(((atot[0] / 0x1p+7f/*1.280000e+02*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/))) * Go[((int)threadIdx.x)])) * ((bfloat16_t)(0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - ((float)G2[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))])))))));
}


extern "C" __global__ void k3_kda_core_b48_kh96_kd128_kernel(const float* __restrict__ Alog, const bfloat16_t* __restrict__ Bt, const float* __restrict__ Dt, const bfloat16_t* __restrict__ G2, const float* __restrict__ GP, const float* __restrict__ Go, const bfloat16_t* __restrict__ K, bfloat16_t* __restrict__ Out, const bfloat16_t* __restrict__ Q, const float* __restrict__ State, float* __restrict__ StateN, const bfloat16_t* __restrict__ V);
extern "C" __global__ void __launch_bounds__(128, 1) k3_kda_core_b48_kh96_kd128_kernel(const float* __restrict__ Alog, const bfloat16_t* __restrict__ Bt, const float* __restrict__ Dt, const bfloat16_t* __restrict__ G2, const float* __restrict__ GP, const float* __restrict__ Go, const bfloat16_t* __restrict__ K, bfloat16_t* __restrict__ Out, const bfloat16_t* __restrict__ Q, const float* __restrict__ State, float* __restrict__ StateN, const bfloat16_t* __restrict__ V) {
  extern __shared__ __align__(1024) uchar buf_dyn_shmem[];
  void* attnb = ((void*)((char*)buf_dyn_shmem + 0));
  void* qss = ((void*)((char*)buf_dyn_shmem + 0));
  void* workspace = ((void*)((char*)buf_dyn_shmem + 0));
  void* workspace_1 = ((void*)((char*)buf_dyn_shmem + 0));
  void* workspace_2 = ((void*)((char*)buf_dyn_shmem + 256));
  void* kns = ((void*)((char*)buf_dyn_shmem + 512));
  void* decs = ((void*)((char*)buf_dyn_shmem + 1024));
  float qsq[1];
  float ksq[1];
  float qtot[1];
  float ktot[1];
  float ga[1];
  float mfr[1];
  float afr[1];
  float dfr[1];
  float asq[1];
  float atot[1];
  qsq[0] = ((float)(Q[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))] * Q[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))]));
  ksq[0] = ((float)(K[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))] * K[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))]));
  qtot[0] = 0x0p+0f/*0.000000e+00*/;
  qtot[0] = (qtot[0] + qsq[0]);
  qtot[0] = tl::AllReduce<tl::SumOp, 128, 1, 0, tl::NamedBarrier<128>>::run(qtot[0], (&(((float*)workspace_1)[0])));
  ktot[0] = 0x0p+0f/*0.000000e+00*/;
  ktot[0] = (ktot[0] + ksq[0]);
  __syncthreads();
  ktot[0] = tl::AllReduce<tl::SumOp, 128, 1, 0, tl::NamedBarrier<128>>::run(ktot[0], (&(((float*)workspace)[0])));
  ga[0] = 0x0p+0f/*0.000000e+00*/;
  bfloat16_t qr = ((bfloat16_t)rsqrtf((((float)((bfloat16_t)qtot[0])) + 0x1.0c6f7a0b5ed8dp-20f/*1.000000e-06*/)));
  bfloat16_t kr = ((bfloat16_t)rsqrtf((((float)((bfloat16_t)ktot[0])) + 0x1.0c6f7a0b5ed8dp-20f/*1.000000e-06*/)));
  __syncthreads();
  ((float*)qss)[((int)threadIdx.x)] = (((float)(Q[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))] * qr)) * 0x1.6a09e667f3bcdp-4f/*8.838835e-02*/);
  ((float*)kns)[((int)threadIdx.x)] = ((float)(K[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))] * kr));
  ga[0] = (ga[0] + GP[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))]);
  float raw = (((float)((bfloat16_t)ga[0])) + Dt[((((int)blockIdx.y) * 128) + ((int)threadIdx.x))]);
  ((float*)decs)[((int)threadIdx.x)] = expf((-0x1.4p+2f/*-5.000000e+00*/ * (0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - (expf(Alog[((int)blockIdx.y)]) * raw)))))));
  __syncthreads();
  mfr[0] = 0x0p+0f/*0.000000e+00*/;
  afr[0] = 0x0p+0f/*0.000000e+00*/;
  for (int k = 0; k < 128; ++k) {
    mfr[0] = (mfr[0] + ((State[((((((int)blockIdx.x) * 1572864) + (((int)blockIdx.y) * 16384)) + (((int)threadIdx.x) * 128)) + k)] * ((float*)decs)[k]) * ((float*)kns)[k]));
  }
  dfr[0] = ((((float)V[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))]) - mfr[0]) * (0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - ((float)Bt[((((int)blockIdx.x) * 96) + ((int)blockIdx.y))]))))));
  for (int k_1 = 0; k_1 < 128; ++k_1) {
    StateN[((((((int)blockIdx.x) * 1572864) + (((int)blockIdx.y) * 16384)) + (((int)threadIdx.x) * 128)) + k_1)] = ((State[((((((int)blockIdx.x) * 1572864) + (((int)blockIdx.y) * 16384)) + (((int)threadIdx.x) * 128)) + k_1)] * ((float*)decs)[k_1]) + (dfr[0] * ((float*)kns)[k_1]));
    afr[0] = (afr[0] + (StateN[((((((int)blockIdx.x) * 1572864) + (((int)blockIdx.y) * 16384)) + (((int)threadIdx.x) * 128)) + k_1)] * ((float*)qss)[k_1]));
  }
  __syncthreads();
  ((bfloat16_t*)attnb)[((int)threadIdx.x)] = ((bfloat16_t)afr[0]);
  __syncthreads();
  asq[0] = (((float)((bfloat16_t*)attnb)[((int)threadIdx.x)]) * ((float)((bfloat16_t*)attnb)[((int)threadIdx.x)]));
  atot[0] = 0x0p+0f/*0.000000e+00*/;
  atot[0] = (atot[0] + asq[0]);
  __syncthreads();
  atot[0] = tl::AllReduce<tl::SumOp, 128, 1, 0, tl::NamedBarrier<128>>::run(atot[0], (&(((float*)workspace_2)[0])));
  __syncthreads();
  Out[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))] = (((bfloat16_t)((((float)((bfloat16_t*)attnb)[((int)threadIdx.x)]) * rsqrtf(((atot[0] / 0x1p+7f/*1.280000e+02*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/))) * Go[((int)threadIdx.x)])) * ((bfloat16_t)(0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - ((float)G2[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))])))))));
}


extern "C" __global__ void k3_kda_core_b64_kh96_kd128_kernel(const float* __restrict__ Alog, const bfloat16_t* __restrict__ Bt, const float* __restrict__ Dt, const bfloat16_t* __restrict__ G2, const float* __restrict__ GP, const float* __restrict__ Go, const bfloat16_t* __restrict__ K, bfloat16_t* __restrict__ Out, const bfloat16_t* __restrict__ Q, const float* __restrict__ State, float* __restrict__ StateN, const bfloat16_t* __restrict__ V);
extern "C" __global__ void __launch_bounds__(128, 1) k3_kda_core_b64_kh96_kd128_kernel(const float* __restrict__ Alog, const bfloat16_t* __restrict__ Bt, const float* __restrict__ Dt, const bfloat16_t* __restrict__ G2, const float* __restrict__ GP, const float* __restrict__ Go, const bfloat16_t* __restrict__ K, bfloat16_t* __restrict__ Out, const bfloat16_t* __restrict__ Q, const float* __restrict__ State, float* __restrict__ StateN, const bfloat16_t* __restrict__ V) {
  extern __shared__ __align__(1024) uchar buf_dyn_shmem[];
  void* attnb = ((void*)((char*)buf_dyn_shmem + 0));
  void* qss = ((void*)((char*)buf_dyn_shmem + 0));
  void* workspace = ((void*)((char*)buf_dyn_shmem + 0));
  void* workspace_1 = ((void*)((char*)buf_dyn_shmem + 0));
  void* workspace_2 = ((void*)((char*)buf_dyn_shmem + 256));
  void* kns = ((void*)((char*)buf_dyn_shmem + 512));
  void* decs = ((void*)((char*)buf_dyn_shmem + 1024));
  float qsq[1];
  float ksq[1];
  float qtot[1];
  float ktot[1];
  float ga[1];
  float mfr[1];
  float afr[1];
  float dfr[1];
  float asq[1];
  float atot[1];
  qsq[0] = ((float)(Q[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))] * Q[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))]));
  ksq[0] = ((float)(K[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))] * K[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))]));
  qtot[0] = 0x0p+0f/*0.000000e+00*/;
  qtot[0] = (qtot[0] + qsq[0]);
  qtot[0] = tl::AllReduce<tl::SumOp, 128, 1, 0, tl::NamedBarrier<128>>::run(qtot[0], (&(((float*)workspace_1)[0])));
  ktot[0] = 0x0p+0f/*0.000000e+00*/;
  ktot[0] = (ktot[0] + ksq[0]);
  __syncthreads();
  ktot[0] = tl::AllReduce<tl::SumOp, 128, 1, 0, tl::NamedBarrier<128>>::run(ktot[0], (&(((float*)workspace)[0])));
  ga[0] = 0x0p+0f/*0.000000e+00*/;
  bfloat16_t qr = ((bfloat16_t)rsqrtf((((float)((bfloat16_t)qtot[0])) + 0x1.0c6f7a0b5ed8dp-20f/*1.000000e-06*/)));
  bfloat16_t kr = ((bfloat16_t)rsqrtf((((float)((bfloat16_t)ktot[0])) + 0x1.0c6f7a0b5ed8dp-20f/*1.000000e-06*/)));
  __syncthreads();
  ((float*)qss)[((int)threadIdx.x)] = (((float)(Q[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))] * qr)) * 0x1.6a09e667f3bcdp-4f/*8.838835e-02*/);
  ((float*)kns)[((int)threadIdx.x)] = ((float)(K[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))] * kr));
  ga[0] = (ga[0] + GP[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))]);
  float raw = (((float)((bfloat16_t)ga[0])) + Dt[((((int)blockIdx.y) * 128) + ((int)threadIdx.x))]);
  ((float*)decs)[((int)threadIdx.x)] = expf((-0x1.4p+2f/*-5.000000e+00*/ * (0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - (expf(Alog[((int)blockIdx.y)]) * raw)))))));
  __syncthreads();
  mfr[0] = 0x0p+0f/*0.000000e+00*/;
  afr[0] = 0x0p+0f/*0.000000e+00*/;
  for (int k = 0; k < 128; ++k) {
    mfr[0] = (mfr[0] + ((State[((((((int)blockIdx.x) * 1572864) + (((int)blockIdx.y) * 16384)) + (((int)threadIdx.x) * 128)) + k)] * ((float*)decs)[k]) * ((float*)kns)[k]));
  }
  dfr[0] = ((((float)V[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))]) - mfr[0]) * (0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - ((float)Bt[((((int)blockIdx.x) * 96) + ((int)blockIdx.y))]))))));
  for (int k_1 = 0; k_1 < 128; ++k_1) {
    StateN[((((((int)blockIdx.x) * 1572864) + (((int)blockIdx.y) * 16384)) + (((int)threadIdx.x) * 128)) + k_1)] = ((State[((((((int)blockIdx.x) * 1572864) + (((int)blockIdx.y) * 16384)) + (((int)threadIdx.x) * 128)) + k_1)] * ((float*)decs)[k_1]) + (dfr[0] * ((float*)kns)[k_1]));
    afr[0] = (afr[0] + (StateN[((((((int)blockIdx.x) * 1572864) + (((int)blockIdx.y) * 16384)) + (((int)threadIdx.x) * 128)) + k_1)] * ((float*)qss)[k_1]));
  }
  __syncthreads();
  ((bfloat16_t*)attnb)[((int)threadIdx.x)] = ((bfloat16_t)afr[0]);
  __syncthreads();
  asq[0] = (((float)((bfloat16_t*)attnb)[((int)threadIdx.x)]) * ((float)((bfloat16_t*)attnb)[((int)threadIdx.x)]));
  atot[0] = 0x0p+0f/*0.000000e+00*/;
  atot[0] = (atot[0] + asq[0]);
  __syncthreads();
  atot[0] = tl::AllReduce<tl::SumOp, 128, 1, 0, tl::NamedBarrier<128>>::run(atot[0], (&(((float*)workspace_2)[0])));
  __syncthreads();
  Out[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))] = (((bfloat16_t)((((float)((bfloat16_t*)attnb)[((int)threadIdx.x)]) * rsqrtf(((atot[0] / 0x1p+7f/*1.280000e+02*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/))) * Go[((int)threadIdx.x)])) * ((bfloat16_t)(0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - ((float)G2[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))])))))));
}


extern "C" __global__ void k3_kda_core_b96_kh96_kd128_kernel(const float* __restrict__ Alog, const bfloat16_t* __restrict__ Bt, const float* __restrict__ Dt, const bfloat16_t* __restrict__ G2, const float* __restrict__ GP, const float* __restrict__ Go, const bfloat16_t* __restrict__ K, bfloat16_t* __restrict__ Out, const bfloat16_t* __restrict__ Q, const float* __restrict__ State, float* __restrict__ StateN, const bfloat16_t* __restrict__ V);
extern "C" __global__ void __launch_bounds__(128, 1) k3_kda_core_b96_kh96_kd128_kernel(const float* __restrict__ Alog, const bfloat16_t* __restrict__ Bt, const float* __restrict__ Dt, const bfloat16_t* __restrict__ G2, const float* __restrict__ GP, const float* __restrict__ Go, const bfloat16_t* __restrict__ K, bfloat16_t* __restrict__ Out, const bfloat16_t* __restrict__ Q, const float* __restrict__ State, float* __restrict__ StateN, const bfloat16_t* __restrict__ V) {
  extern __shared__ __align__(1024) uchar buf_dyn_shmem[];
  void* attnb = ((void*)((char*)buf_dyn_shmem + 0));
  void* qss = ((void*)((char*)buf_dyn_shmem + 0));
  void* workspace = ((void*)((char*)buf_dyn_shmem + 0));
  void* workspace_1 = ((void*)((char*)buf_dyn_shmem + 0));
  void* workspace_2 = ((void*)((char*)buf_dyn_shmem + 256));
  void* kns = ((void*)((char*)buf_dyn_shmem + 512));
  void* decs = ((void*)((char*)buf_dyn_shmem + 1024));
  float qsq[1];
  float ksq[1];
  float qtot[1];
  float ktot[1];
  float ga[1];
  float mfr[1];
  float afr[1];
  float dfr[1];
  float asq[1];
  float atot[1];
  qsq[0] = ((float)(Q[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))] * Q[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))]));
  ksq[0] = ((float)(K[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))] * K[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))]));
  qtot[0] = 0x0p+0f/*0.000000e+00*/;
  qtot[0] = (qtot[0] + qsq[0]);
  qtot[0] = tl::AllReduce<tl::SumOp, 128, 1, 0, tl::NamedBarrier<128>>::run(qtot[0], (&(((float*)workspace_1)[0])));
  ktot[0] = 0x0p+0f/*0.000000e+00*/;
  ktot[0] = (ktot[0] + ksq[0]);
  __syncthreads();
  ktot[0] = tl::AllReduce<tl::SumOp, 128, 1, 0, tl::NamedBarrier<128>>::run(ktot[0], (&(((float*)workspace)[0])));
  ga[0] = 0x0p+0f/*0.000000e+00*/;
  bfloat16_t qr = ((bfloat16_t)rsqrtf((((float)((bfloat16_t)qtot[0])) + 0x1.0c6f7a0b5ed8dp-20f/*1.000000e-06*/)));
  bfloat16_t kr = ((bfloat16_t)rsqrtf((((float)((bfloat16_t)ktot[0])) + 0x1.0c6f7a0b5ed8dp-20f/*1.000000e-06*/)));
  __syncthreads();
  ((float*)qss)[((int)threadIdx.x)] = (((float)(Q[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))] * qr)) * 0x1.6a09e667f3bcdp-4f/*8.838835e-02*/);
  ((float*)kns)[((int)threadIdx.x)] = ((float)(K[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))] * kr));
  ga[0] = (ga[0] + GP[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))]);
  float raw = (((float)((bfloat16_t)ga[0])) + Dt[((((int)blockIdx.y) * 128) + ((int)threadIdx.x))]);
  ((float*)decs)[((int)threadIdx.x)] = expf((-0x1.4p+2f/*-5.000000e+00*/ * (0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - (expf(Alog[((int)blockIdx.y)]) * raw)))))));
  __syncthreads();
  mfr[0] = 0x0p+0f/*0.000000e+00*/;
  afr[0] = 0x0p+0f/*0.000000e+00*/;
  for (int k = 0; k < 128; ++k) {
    mfr[0] = (mfr[0] + ((State[((((((int)blockIdx.x) * 1572864) + (((int)blockIdx.y) * 16384)) + (((int)threadIdx.x) * 128)) + k)] * ((float*)decs)[k]) * ((float*)kns)[k]));
  }
  dfr[0] = ((((float)V[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))]) - mfr[0]) * (0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - ((float)Bt[((((int)blockIdx.x) * 96) + ((int)blockIdx.y))]))))));
  for (int k_1 = 0; k_1 < 128; ++k_1) {
    StateN[((((((int)blockIdx.x) * 1572864) + (((int)blockIdx.y) * 16384)) + (((int)threadIdx.x) * 128)) + k_1)] = ((State[((((((int)blockIdx.x) * 1572864) + (((int)blockIdx.y) * 16384)) + (((int)threadIdx.x) * 128)) + k_1)] * ((float*)decs)[k_1]) + (dfr[0] * ((float*)kns)[k_1]));
    afr[0] = (afr[0] + (StateN[((((((int)blockIdx.x) * 1572864) + (((int)blockIdx.y) * 16384)) + (((int)threadIdx.x) * 128)) + k_1)] * ((float*)qss)[k_1]));
  }
  __syncthreads();
  ((bfloat16_t*)attnb)[((int)threadIdx.x)] = ((bfloat16_t)afr[0]);
  __syncthreads();
  asq[0] = (((float)((bfloat16_t*)attnb)[((int)threadIdx.x)]) * ((float)((bfloat16_t*)attnb)[((int)threadIdx.x)]));
  atot[0] = 0x0p+0f/*0.000000e+00*/;
  atot[0] = (atot[0] + asq[0]);
  __syncthreads();
  atot[0] = tl::AllReduce<tl::SumOp, 128, 1, 0, tl::NamedBarrier<128>>::run(atot[0], (&(((float*)workspace_2)[0])));
  __syncthreads();
  Out[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))] = (((bfloat16_t)((((float)((bfloat16_t*)attnb)[((int)threadIdx.x)]) * rsqrtf(((atot[0] / 0x1p+7f/*1.280000e+02*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/))) * Go[((int)threadIdx.x)])) * ((bfloat16_t)(0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - ((float)G2[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))])))))));
}


extern "C" __global__ void k3_kda_core_b128_kh96_kd128_kernel(const float* __restrict__ Alog, const bfloat16_t* __restrict__ Bt, const float* __restrict__ Dt, const bfloat16_t* __restrict__ G2, const float* __restrict__ GP, const float* __restrict__ Go, const bfloat16_t* __restrict__ K, bfloat16_t* __restrict__ Out, const bfloat16_t* __restrict__ Q, const float* __restrict__ State, float* __restrict__ StateN, const bfloat16_t* __restrict__ V);
extern "C" __global__ void __launch_bounds__(128, 1) k3_kda_core_b128_kh96_kd128_kernel(const float* __restrict__ Alog, const bfloat16_t* __restrict__ Bt, const float* __restrict__ Dt, const bfloat16_t* __restrict__ G2, const float* __restrict__ GP, const float* __restrict__ Go, const bfloat16_t* __restrict__ K, bfloat16_t* __restrict__ Out, const bfloat16_t* __restrict__ Q, const float* __restrict__ State, float* __restrict__ StateN, const bfloat16_t* __restrict__ V) {
  extern __shared__ __align__(1024) uchar buf_dyn_shmem[];
  void* attnb = ((void*)((char*)buf_dyn_shmem + 0));
  void* qss = ((void*)((char*)buf_dyn_shmem + 0));
  void* workspace = ((void*)((char*)buf_dyn_shmem + 0));
  void* workspace_1 = ((void*)((char*)buf_dyn_shmem + 0));
  void* workspace_2 = ((void*)((char*)buf_dyn_shmem + 256));
  void* kns = ((void*)((char*)buf_dyn_shmem + 512));
  void* decs = ((void*)((char*)buf_dyn_shmem + 1024));
  float qsq[1];
  float ksq[1];
  float qtot[1];
  float ktot[1];
  float ga[1];
  float mfr[1];
  float afr[1];
  float dfr[1];
  float asq[1];
  float atot[1];
  qsq[0] = ((float)(Q[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))] * Q[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))]));
  ksq[0] = ((float)(K[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))] * K[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))]));
  qtot[0] = 0x0p+0f/*0.000000e+00*/;
  qtot[0] = (qtot[0] + qsq[0]);
  qtot[0] = tl::AllReduce<tl::SumOp, 128, 1, 0, tl::NamedBarrier<128>>::run(qtot[0], (&(((float*)workspace_1)[0])));
  ktot[0] = 0x0p+0f/*0.000000e+00*/;
  ktot[0] = (ktot[0] + ksq[0]);
  __syncthreads();
  ktot[0] = tl::AllReduce<tl::SumOp, 128, 1, 0, tl::NamedBarrier<128>>::run(ktot[0], (&(((float*)workspace)[0])));
  ga[0] = 0x0p+0f/*0.000000e+00*/;
  bfloat16_t qr = ((bfloat16_t)rsqrtf((((float)((bfloat16_t)qtot[0])) + 0x1.0c6f7a0b5ed8dp-20f/*1.000000e-06*/)));
  bfloat16_t kr = ((bfloat16_t)rsqrtf((((float)((bfloat16_t)ktot[0])) + 0x1.0c6f7a0b5ed8dp-20f/*1.000000e-06*/)));
  __syncthreads();
  ((float*)qss)[((int)threadIdx.x)] = (((float)(Q[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))] * qr)) * 0x1.6a09e667f3bcdp-4f/*8.838835e-02*/);
  ((float*)kns)[((int)threadIdx.x)] = ((float)(K[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))] * kr));
  ga[0] = (ga[0] + GP[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))]);
  float raw = (((float)((bfloat16_t)ga[0])) + Dt[((((int)blockIdx.y) * 128) + ((int)threadIdx.x))]);
  ((float*)decs)[((int)threadIdx.x)] = expf((-0x1.4p+2f/*-5.000000e+00*/ * (0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - (expf(Alog[((int)blockIdx.y)]) * raw)))))));
  __syncthreads();
  mfr[0] = 0x0p+0f/*0.000000e+00*/;
  afr[0] = 0x0p+0f/*0.000000e+00*/;
  for (int k = 0; k < 128; ++k) {
    mfr[0] = (mfr[0] + ((State[((((((int)blockIdx.x) * 1572864) + (((int)blockIdx.y) * 16384)) + (((int)threadIdx.x) * 128)) + k)] * ((float*)decs)[k]) * ((float*)kns)[k]));
  }
  dfr[0] = ((((float)V[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))]) - mfr[0]) * (0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - ((float)Bt[((((int)blockIdx.x) * 96) + ((int)blockIdx.y))]))))));
  for (int k_1 = 0; k_1 < 128; ++k_1) {
    StateN[((((((int)blockIdx.x) * 1572864) + (((int)blockIdx.y) * 16384)) + (((int)threadIdx.x) * 128)) + k_1)] = ((State[((((((int)blockIdx.x) * 1572864) + (((int)blockIdx.y) * 16384)) + (((int)threadIdx.x) * 128)) + k_1)] * ((float*)decs)[k_1]) + (dfr[0] * ((float*)kns)[k_1]));
    afr[0] = (afr[0] + (StateN[((((((int)blockIdx.x) * 1572864) + (((int)blockIdx.y) * 16384)) + (((int)threadIdx.x) * 128)) + k_1)] * ((float*)qss)[k_1]));
  }
  __syncthreads();
  ((bfloat16_t*)attnb)[((int)threadIdx.x)] = ((bfloat16_t)afr[0]);
  __syncthreads();
  asq[0] = (((float)((bfloat16_t*)attnb)[((int)threadIdx.x)]) * ((float)((bfloat16_t*)attnb)[((int)threadIdx.x)]));
  atot[0] = 0x0p+0f/*0.000000e+00*/;
  atot[0] = (atot[0] + asq[0]);
  __syncthreads();
  atot[0] = tl::AllReduce<tl::SumOp, 128, 1, 0, tl::NamedBarrier<128>>::run(atot[0], (&(((float*)workspace_2)[0])));
  __syncthreads();
  Out[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))] = (((bfloat16_t)((((float)((bfloat16_t*)attnb)[((int)threadIdx.x)]) * rsqrtf(((atot[0] / 0x1p+7f/*1.280000e+02*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/))) * Go[((int)threadIdx.x)])) * ((bfloat16_t)(0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - ((float)G2[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 128)) + ((int)threadIdx.x))])))))));
}



// One delta-rule step per row, one (row, head) per block, with
// threads = head_dim. The recurrent state is
// [b, head, v_dim, k_dim] f32 with decay along k, so a row's state is
// the contiguous single-row block; State and StateN must not alias.
// Dt, Alog and Go are weights and carry no batch axis; the gate lower
// bound and eps are compiled in.
extern "C" int k3_kda_core_batched(
    const void* Q,
    const void* K,
    const void* V,
    const float* GP,
    const float* Dt,
    const float* Alog,
    const void* Bt,
    const void* G2,
    const float* Go,
    const float* State,
    float* StateN,
    void* Out,
    int b,
    int num_heads,
    int head_dim,
    int split_k_gate,
    cudaStream_t stream) {
  if (b == 1 && num_heads == 96 && head_dim == 128 && split_k_gate == 1) {
    k3_kda_core_b1_kh96_kd128_kernel<<<dim3(1, 96, 1), 128, 1536, stream>>>(
        Alog,
        reinterpret_cast<const bfloat16_t*>(Bt),
        Dt,
        reinterpret_cast<const bfloat16_t*>(G2),
        GP,
        Go,
        reinterpret_cast<const bfloat16_t*>(K),
        reinterpret_cast<bfloat16_t*>(Out),
        reinterpret_cast<const bfloat16_t*>(Q),
        State,
        StateN,
        reinterpret_cast<const bfloat16_t*>(V));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 2 && num_heads == 96 && head_dim == 128 && split_k_gate == 1) {
    k3_kda_core_b2_kh96_kd128_kernel<<<dim3(2, 96, 1), 128, 1536, stream>>>(
        Alog,
        reinterpret_cast<const bfloat16_t*>(Bt),
        Dt,
        reinterpret_cast<const bfloat16_t*>(G2),
        GP,
        Go,
        reinterpret_cast<const bfloat16_t*>(K),
        reinterpret_cast<bfloat16_t*>(Out),
        reinterpret_cast<const bfloat16_t*>(Q),
        State,
        StateN,
        reinterpret_cast<const bfloat16_t*>(V));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 4 && num_heads == 96 && head_dim == 128 && split_k_gate == 1) {
    k3_kda_core_b4_kh96_kd128_kernel<<<dim3(4, 96, 1), 128, 1536, stream>>>(
        Alog,
        reinterpret_cast<const bfloat16_t*>(Bt),
        Dt,
        reinterpret_cast<const bfloat16_t*>(G2),
        GP,
        Go,
        reinterpret_cast<const bfloat16_t*>(K),
        reinterpret_cast<bfloat16_t*>(Out),
        reinterpret_cast<const bfloat16_t*>(Q),
        State,
        StateN,
        reinterpret_cast<const bfloat16_t*>(V));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 8 && num_heads == 96 && head_dim == 128 && split_k_gate == 1) {
    k3_kda_core_b8_kh96_kd128_kernel<<<dim3(8, 96, 1), 128, 1536, stream>>>(
        Alog,
        reinterpret_cast<const bfloat16_t*>(Bt),
        Dt,
        reinterpret_cast<const bfloat16_t*>(G2),
        GP,
        Go,
        reinterpret_cast<const bfloat16_t*>(K),
        reinterpret_cast<bfloat16_t*>(Out),
        reinterpret_cast<const bfloat16_t*>(Q),
        State,
        StateN,
        reinterpret_cast<const bfloat16_t*>(V));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 16 && num_heads == 96 && head_dim == 128 && split_k_gate == 1) {
    k3_kda_core_b16_kh96_kd128_kernel<<<dim3(16, 96, 1), 128, 1536, stream>>>(
        Alog,
        reinterpret_cast<const bfloat16_t*>(Bt),
        Dt,
        reinterpret_cast<const bfloat16_t*>(G2),
        GP,
        Go,
        reinterpret_cast<const bfloat16_t*>(K),
        reinterpret_cast<bfloat16_t*>(Out),
        reinterpret_cast<const bfloat16_t*>(Q),
        State,
        StateN,
        reinterpret_cast<const bfloat16_t*>(V));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 32 && num_heads == 96 && head_dim == 128 && split_k_gate == 1) {
    k3_kda_core_b32_kh96_kd128_kernel<<<dim3(32, 96, 1), 128, 1536, stream>>>(
        Alog,
        reinterpret_cast<const bfloat16_t*>(Bt),
        Dt,
        reinterpret_cast<const bfloat16_t*>(G2),
        GP,
        Go,
        reinterpret_cast<const bfloat16_t*>(K),
        reinterpret_cast<bfloat16_t*>(Out),
        reinterpret_cast<const bfloat16_t*>(Q),
        State,
        StateN,
        reinterpret_cast<const bfloat16_t*>(V));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 48 && num_heads == 96 && head_dim == 128 && split_k_gate == 1) {
    k3_kda_core_b48_kh96_kd128_kernel<<<dim3(48, 96, 1), 128, 1536, stream>>>(
        Alog,
        reinterpret_cast<const bfloat16_t*>(Bt),
        Dt,
        reinterpret_cast<const bfloat16_t*>(G2),
        GP,
        Go,
        reinterpret_cast<const bfloat16_t*>(K),
        reinterpret_cast<bfloat16_t*>(Out),
        reinterpret_cast<const bfloat16_t*>(Q),
        State,
        StateN,
        reinterpret_cast<const bfloat16_t*>(V));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 64 && num_heads == 96 && head_dim == 128 && split_k_gate == 1) {
    k3_kda_core_b64_kh96_kd128_kernel<<<dim3(64, 96, 1), 128, 1536, stream>>>(
        Alog,
        reinterpret_cast<const bfloat16_t*>(Bt),
        Dt,
        reinterpret_cast<const bfloat16_t*>(G2),
        GP,
        Go,
        reinterpret_cast<const bfloat16_t*>(K),
        reinterpret_cast<bfloat16_t*>(Out),
        reinterpret_cast<const bfloat16_t*>(Q),
        State,
        StateN,
        reinterpret_cast<const bfloat16_t*>(V));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 96 && num_heads == 96 && head_dim == 128 && split_k_gate == 1) {
    k3_kda_core_b96_kh96_kd128_kernel<<<dim3(96, 96, 1), 128, 1536, stream>>>(
        Alog,
        reinterpret_cast<const bfloat16_t*>(Bt),
        Dt,
        reinterpret_cast<const bfloat16_t*>(G2),
        GP,
        Go,
        reinterpret_cast<const bfloat16_t*>(K),
        reinterpret_cast<bfloat16_t*>(Out),
        reinterpret_cast<const bfloat16_t*>(Q),
        State,
        StateN,
        reinterpret_cast<const bfloat16_t*>(V));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 128 && num_heads == 96 && head_dim == 128 && split_k_gate == 1) {
    k3_kda_core_b128_kh96_kd128_kernel<<<dim3(128, 96, 1), 128, 1536, stream>>>(
        Alog,
        reinterpret_cast<const bfloat16_t*>(Bt),
        Dt,
        reinterpret_cast<const bfloat16_t*>(G2),
        GP,
        Go,
        reinterpret_cast<const bfloat16_t*>(K),
        reinterpret_cast<bfloat16_t*>(Out),
        reinterpret_cast<const bfloat16_t*>(Q),
        State,
        StateN,
        reinterpret_cast<const bfloat16_t*>(V));
    return static_cast<int>(cudaGetLastError());
  }
  return static_cast<int>(cudaErrorInvalidValue);
}
