// Generated by pegainfer-k3/kernels/generate.py -- do not edit.
#include <cuda_runtime.h>

#if defined(_MSC_VER) && !defined(__clang__) && _MSC_VER < 1940
#define _tl_orig_alignas alignas
#define alignas(N) _tl_orig_alignas((N) <= 64 ? (N) : 64)
#include <cuda.h>
#undef alignas
#define alignas _tl_orig_alignas
#endif
#include <tl_templates/cuda/reduce.h>
#include <tl_templates/cuda/scan.h>
#include <tl_templates/cuda/ldsm.h>
#include <tl_templates/cuda/threadblock_swizzle.h>
#define debug_print_msg k3_land_rms_norm_rbs_batched_debug_print_msg
#define debug_print_buffer_value k3_land_rms_norm_rbs_batched_debug_print_buffer_value
#include <tl_templates/cuda/debug.h>
#undef debug_print_msg
#undef debug_print_buffer_value
#ifdef ENABLE_BF16
#include <tl_templates/cuda/cuda_bf16_fallbacks.cuh>
#endif

extern "C" __global__ void k3_land_rms_norm_rbs_b1_nt14400_n1536_off0_sk1_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const float* __restrict__ P);
extern "C" __global__ void __launch_bounds__(256, 1) k3_land_rms_norm_rbs_b1_nt14400_n1536_off0_sk1_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const float* __restrict__ P) {
  float xs[6];
  float sq[6];
  float tot[1];
  extern __shared__ __align__(1024) float workspace[];
  #pragma unroll
  for (int i = 0; i < 3; ++i) {
    float broadcast_var = 0x0p+0f/*0.000000e+00*/;
    *(float2*)(xs + (i * 2)) = make_float2(broadcast_var, broadcast_var);
  }
  #pragma unroll
  for (int i_1 = 0; i_1 < 6; ++i_1) {
    xs[i_1] = (xs[i_1] + P[((i_1 * 256) + ((int)threadIdx.x))]);
  }
  #pragma unroll
  for (int i_2 = 0; i_2 < 3; ++i_2) {
    float2 __1;
    uint1 __2;
    float2 v_ = *(float2*)(xs + (i_2 * 2));
    (reinterpret_cast<__nv_bfloat162*>(&__2))[0] = __float22bfloat162_rn(((float2*)(&v_))[0]);
    ((float2*)(&__1))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&__2))[0]);
    *(float2*)(xs + (i_2 * 2)) = __1;
    float2 __3;
      *(float2*)(&(__3.x)) = tl::mul2(*(float2*)(&(v_.x)), *(float2*)(&(v_.x)));
    *(float2*)(sq + (i_2 * 2)) = __3;
  }
  tot[0] = 0x0p+0f/*0.000000e+00*/;
  #pragma unroll
  for (int rv = 0; rv < 6; ++rv) {
    tot[0] = (tot[0] + sq[rv]);
  }
  tot[0] = tl::AllReduce<tl::SumOp, 256, 1, 0, tl::NamedBarrier<256>>::run(tot[0], (&(workspace[0])));
  #pragma unroll
  for (int i_3 = 0; i_3 < 6; ++i_3) {
    O[((i_3 * 256) + ((int)threadIdx.x))] = (((bfloat16_t)(xs[i_3] * rsqrtf(((tot[0] / 0x1.8p+10f/*1.536000e+03*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)))) * G[((i_3 * 256) + ((int)threadIdx.x))]);
  }
}


extern "C" __global__ void k3_land_rms_norm_rbs_b2_nt14400_n1536_off0_sk1_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const float* __restrict__ P);
extern "C" __global__ void __launch_bounds__(256, 1) k3_land_rms_norm_rbs_b2_nt14400_n1536_off0_sk1_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const float* __restrict__ P) {
  float xs[6];
  float sq[6];
  float tot[1];
  extern __shared__ __align__(1024) float workspace[];
  #pragma unroll
  for (int i = 0; i < 3; ++i) {
    float broadcast_var = 0x0p+0f/*0.000000e+00*/;
    *(float2*)(xs + (i * 2)) = make_float2(broadcast_var, broadcast_var);
  }
  #pragma unroll
  for (int i_1 = 0; i_1 < 6; ++i_1) {
    xs[i_1] = (xs[i_1] + P[(((((int)blockIdx.x) * 14400) + (i_1 * 256)) + ((int)threadIdx.x))]);
  }
  #pragma unroll
  for (int i_2 = 0; i_2 < 3; ++i_2) {
    float2 __1;
    uint1 __2;
    float2 v_ = *(float2*)(xs + (i_2 * 2));
    (reinterpret_cast<__nv_bfloat162*>(&__2))[0] = __float22bfloat162_rn(((float2*)(&v_))[0]);
    ((float2*)(&__1))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&__2))[0]);
    *(float2*)(xs + (i_2 * 2)) = __1;
    float2 __3;
      *(float2*)(&(__3.x)) = tl::mul2(*(float2*)(&(v_.x)), *(float2*)(&(v_.x)));
    *(float2*)(sq + (i_2 * 2)) = __3;
  }
  tot[0] = 0x0p+0f/*0.000000e+00*/;
  #pragma unroll
  for (int rv = 0; rv < 6; ++rv) {
    tot[0] = (tot[0] + sq[rv]);
  }
  tot[0] = tl::AllReduce<tl::SumOp, 256, 1, 0, tl::NamedBarrier<256>>::run(tot[0], (&(workspace[0])));
  #pragma unroll
  for (int i_3 = 0; i_3 < 6; ++i_3) {
    O[(((((int)blockIdx.x) * 1536) + (i_3 * 256)) + ((int)threadIdx.x))] = (((bfloat16_t)(xs[i_3] * rsqrtf(((tot[0] / 0x1.8p+10f/*1.536000e+03*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)))) * G[((i_3 * 256) + ((int)threadIdx.x))]);
  }
}


extern "C" __global__ void k3_land_rms_norm_rbs_b4_nt14400_n1536_off0_sk1_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const float* __restrict__ P);
extern "C" __global__ void __launch_bounds__(256, 1) k3_land_rms_norm_rbs_b4_nt14400_n1536_off0_sk1_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const float* __restrict__ P) {
  float xs[6];
  float sq[6];
  float tot[1];
  extern __shared__ __align__(1024) float workspace[];
  #pragma unroll
  for (int i = 0; i < 3; ++i) {
    float broadcast_var = 0x0p+0f/*0.000000e+00*/;
    *(float2*)(xs + (i * 2)) = make_float2(broadcast_var, broadcast_var);
  }
  #pragma unroll
  for (int i_1 = 0; i_1 < 6; ++i_1) {
    xs[i_1] = (xs[i_1] + P[(((((int)blockIdx.x) * 14400) + (i_1 * 256)) + ((int)threadIdx.x))]);
  }
  #pragma unroll
  for (int i_2 = 0; i_2 < 3; ++i_2) {
    float2 __1;
    uint1 __2;
    float2 v_ = *(float2*)(xs + (i_2 * 2));
    (reinterpret_cast<__nv_bfloat162*>(&__2))[0] = __float22bfloat162_rn(((float2*)(&v_))[0]);
    ((float2*)(&__1))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&__2))[0]);
    *(float2*)(xs + (i_2 * 2)) = __1;
    float2 __3;
      *(float2*)(&(__3.x)) = tl::mul2(*(float2*)(&(v_.x)), *(float2*)(&(v_.x)));
    *(float2*)(sq + (i_2 * 2)) = __3;
  }
  tot[0] = 0x0p+0f/*0.000000e+00*/;
  #pragma unroll
  for (int rv = 0; rv < 6; ++rv) {
    tot[0] = (tot[0] + sq[rv]);
  }
  tot[0] = tl::AllReduce<tl::SumOp, 256, 1, 0, tl::NamedBarrier<256>>::run(tot[0], (&(workspace[0])));
  #pragma unroll
  for (int i_3 = 0; i_3 < 6; ++i_3) {
    O[(((((int)blockIdx.x) * 1536) + (i_3 * 256)) + ((int)threadIdx.x))] = (((bfloat16_t)(xs[i_3] * rsqrtf(((tot[0] / 0x1.8p+10f/*1.536000e+03*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)))) * G[((i_3 * 256) + ((int)threadIdx.x))]);
  }
}


extern "C" __global__ void k3_land_rms_norm_rbs_b8_nt14400_n1536_off0_sk1_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const float* __restrict__ P);
extern "C" __global__ void __launch_bounds__(256, 1) k3_land_rms_norm_rbs_b8_nt14400_n1536_off0_sk1_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const float* __restrict__ P) {
  float xs[6];
  float sq[6];
  float tot[1];
  extern __shared__ __align__(1024) float workspace[];
  #pragma unroll
  for (int i = 0; i < 3; ++i) {
    float broadcast_var = 0x0p+0f/*0.000000e+00*/;
    *(float2*)(xs + (i * 2)) = make_float2(broadcast_var, broadcast_var);
  }
  #pragma unroll
  for (int i_1 = 0; i_1 < 6; ++i_1) {
    xs[i_1] = (xs[i_1] + P[(((((int)blockIdx.x) * 14400) + (i_1 * 256)) + ((int)threadIdx.x))]);
  }
  #pragma unroll
  for (int i_2 = 0; i_2 < 3; ++i_2) {
    float2 __1;
    uint1 __2;
    float2 v_ = *(float2*)(xs + (i_2 * 2));
    (reinterpret_cast<__nv_bfloat162*>(&__2))[0] = __float22bfloat162_rn(((float2*)(&v_))[0]);
    ((float2*)(&__1))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&__2))[0]);
    *(float2*)(xs + (i_2 * 2)) = __1;
    float2 __3;
      *(float2*)(&(__3.x)) = tl::mul2(*(float2*)(&(v_.x)), *(float2*)(&(v_.x)));
    *(float2*)(sq + (i_2 * 2)) = __3;
  }
  tot[0] = 0x0p+0f/*0.000000e+00*/;
  #pragma unroll
  for (int rv = 0; rv < 6; ++rv) {
    tot[0] = (tot[0] + sq[rv]);
  }
  tot[0] = tl::AllReduce<tl::SumOp, 256, 1, 0, tl::NamedBarrier<256>>::run(tot[0], (&(workspace[0])));
  #pragma unroll
  for (int i_3 = 0; i_3 < 6; ++i_3) {
    O[(((((int)blockIdx.x) * 1536) + (i_3 * 256)) + ((int)threadIdx.x))] = (((bfloat16_t)(xs[i_3] * rsqrtf(((tot[0] / 0x1.8p+10f/*1.536000e+03*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)))) * G[((i_3 * 256) + ((int)threadIdx.x))]);
  }
}


extern "C" __global__ void k3_land_rms_norm_rbs_b16_nt14400_n1536_off0_sk1_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const float* __restrict__ P);
extern "C" __global__ void __launch_bounds__(256, 1) k3_land_rms_norm_rbs_b16_nt14400_n1536_off0_sk1_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const float* __restrict__ P) {
  float xs[6];
  float sq[6];
  float tot[1];
  extern __shared__ __align__(1024) float workspace[];
  #pragma unroll
  for (int i = 0; i < 3; ++i) {
    float broadcast_var = 0x0p+0f/*0.000000e+00*/;
    *(float2*)(xs + (i * 2)) = make_float2(broadcast_var, broadcast_var);
  }
  #pragma unroll
  for (int i_1 = 0; i_1 < 6; ++i_1) {
    xs[i_1] = (xs[i_1] + P[(((((int)blockIdx.x) * 14400) + (i_1 * 256)) + ((int)threadIdx.x))]);
  }
  #pragma unroll
  for (int i_2 = 0; i_2 < 3; ++i_2) {
    float2 __1;
    uint1 __2;
    float2 v_ = *(float2*)(xs + (i_2 * 2));
    (reinterpret_cast<__nv_bfloat162*>(&__2))[0] = __float22bfloat162_rn(((float2*)(&v_))[0]);
    ((float2*)(&__1))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&__2))[0]);
    *(float2*)(xs + (i_2 * 2)) = __1;
    float2 __3;
      *(float2*)(&(__3.x)) = tl::mul2(*(float2*)(&(v_.x)), *(float2*)(&(v_.x)));
    *(float2*)(sq + (i_2 * 2)) = __3;
  }
  tot[0] = 0x0p+0f/*0.000000e+00*/;
  #pragma unroll
  for (int rv = 0; rv < 6; ++rv) {
    tot[0] = (tot[0] + sq[rv]);
  }
  tot[0] = tl::AllReduce<tl::SumOp, 256, 1, 0, tl::NamedBarrier<256>>::run(tot[0], (&(workspace[0])));
  #pragma unroll
  for (int i_3 = 0; i_3 < 6; ++i_3) {
    O[(((((int)blockIdx.x) * 1536) + (i_3 * 256)) + ((int)threadIdx.x))] = (((bfloat16_t)(xs[i_3] * rsqrtf(((tot[0] / 0x1.8p+10f/*1.536000e+03*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)))) * G[((i_3 * 256) + ((int)threadIdx.x))]);
  }
}


extern "C" __global__ void k3_land_rms_norm_rbs_b32_nt14400_n1536_off0_sk1_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const float* __restrict__ P);
extern "C" __global__ void __launch_bounds__(256, 1) k3_land_rms_norm_rbs_b32_nt14400_n1536_off0_sk1_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const float* __restrict__ P) {
  float xs[6];
  float sq[6];
  float tot[1];
  extern __shared__ __align__(1024) float workspace[];
  #pragma unroll
  for (int i = 0; i < 3; ++i) {
    float broadcast_var = 0x0p+0f/*0.000000e+00*/;
    *(float2*)(xs + (i * 2)) = make_float2(broadcast_var, broadcast_var);
  }
  #pragma unroll
  for (int i_1 = 0; i_1 < 6; ++i_1) {
    xs[i_1] = (xs[i_1] + P[(((((int)blockIdx.x) * 14400) + (i_1 * 256)) + ((int)threadIdx.x))]);
  }
  #pragma unroll
  for (int i_2 = 0; i_2 < 3; ++i_2) {
    float2 __1;
    uint1 __2;
    float2 v_ = *(float2*)(xs + (i_2 * 2));
    (reinterpret_cast<__nv_bfloat162*>(&__2))[0] = __float22bfloat162_rn(((float2*)(&v_))[0]);
    ((float2*)(&__1))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&__2))[0]);
    *(float2*)(xs + (i_2 * 2)) = __1;
    float2 __3;
      *(float2*)(&(__3.x)) = tl::mul2(*(float2*)(&(v_.x)), *(float2*)(&(v_.x)));
    *(float2*)(sq + (i_2 * 2)) = __3;
  }
  tot[0] = 0x0p+0f/*0.000000e+00*/;
  #pragma unroll
  for (int rv = 0; rv < 6; ++rv) {
    tot[0] = (tot[0] + sq[rv]);
  }
  tot[0] = tl::AllReduce<tl::SumOp, 256, 1, 0, tl::NamedBarrier<256>>::run(tot[0], (&(workspace[0])));
  #pragma unroll
  for (int i_3 = 0; i_3 < 6; ++i_3) {
    O[(((((int)blockIdx.x) * 1536) + (i_3 * 256)) + ((int)threadIdx.x))] = (((bfloat16_t)(xs[i_3] * rsqrtf(((tot[0] / 0x1.8p+10f/*1.536000e+03*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)))) * G[((i_3 * 256) + ((int)threadIdx.x))]);
  }
}


extern "C" __global__ void k3_land_rms_norm_rbs_b48_nt14400_n1536_off0_sk1_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const float* __restrict__ P);
extern "C" __global__ void __launch_bounds__(256, 1) k3_land_rms_norm_rbs_b48_nt14400_n1536_off0_sk1_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const float* __restrict__ P) {
  float xs[6];
  float sq[6];
  float tot[1];
  extern __shared__ __align__(1024) float workspace[];
  #pragma unroll
  for (int i = 0; i < 3; ++i) {
    float broadcast_var = 0x0p+0f/*0.000000e+00*/;
    *(float2*)(xs + (i * 2)) = make_float2(broadcast_var, broadcast_var);
  }
  #pragma unroll
  for (int i_1 = 0; i_1 < 6; ++i_1) {
    xs[i_1] = (xs[i_1] + P[(((((int)blockIdx.x) * 14400) + (i_1 * 256)) + ((int)threadIdx.x))]);
  }
  #pragma unroll
  for (int i_2 = 0; i_2 < 3; ++i_2) {
    float2 __1;
    uint1 __2;
    float2 v_ = *(float2*)(xs + (i_2 * 2));
    (reinterpret_cast<__nv_bfloat162*>(&__2))[0] = __float22bfloat162_rn(((float2*)(&v_))[0]);
    ((float2*)(&__1))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&__2))[0]);
    *(float2*)(xs + (i_2 * 2)) = __1;
    float2 __3;
      *(float2*)(&(__3.x)) = tl::mul2(*(float2*)(&(v_.x)), *(float2*)(&(v_.x)));
    *(float2*)(sq + (i_2 * 2)) = __3;
  }
  tot[0] = 0x0p+0f/*0.000000e+00*/;
  #pragma unroll
  for (int rv = 0; rv < 6; ++rv) {
    tot[0] = (tot[0] + sq[rv]);
  }
  tot[0] = tl::AllReduce<tl::SumOp, 256, 1, 0, tl::NamedBarrier<256>>::run(tot[0], (&(workspace[0])));
  #pragma unroll
  for (int i_3 = 0; i_3 < 6; ++i_3) {
    O[(((((int)blockIdx.x) * 1536) + (i_3 * 256)) + ((int)threadIdx.x))] = (((bfloat16_t)(xs[i_3] * rsqrtf(((tot[0] / 0x1.8p+10f/*1.536000e+03*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)))) * G[((i_3 * 256) + ((int)threadIdx.x))]);
  }
}


extern "C" __global__ void k3_land_rms_norm_rbs_b64_nt14400_n1536_off0_sk1_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const float* __restrict__ P);
extern "C" __global__ void __launch_bounds__(256, 1) k3_land_rms_norm_rbs_b64_nt14400_n1536_off0_sk1_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const float* __restrict__ P) {
  float xs[6];
  float sq[6];
  float tot[1];
  extern __shared__ __align__(1024) float workspace[];
  #pragma unroll
  for (int i = 0; i < 3; ++i) {
    float broadcast_var = 0x0p+0f/*0.000000e+00*/;
    *(float2*)(xs + (i * 2)) = make_float2(broadcast_var, broadcast_var);
  }
  #pragma unroll
  for (int i_1 = 0; i_1 < 6; ++i_1) {
    xs[i_1] = (xs[i_1] + P[(((((int)blockIdx.x) * 14400) + (i_1 * 256)) + ((int)threadIdx.x))]);
  }
  #pragma unroll
  for (int i_2 = 0; i_2 < 3; ++i_2) {
    float2 __1;
    uint1 __2;
    float2 v_ = *(float2*)(xs + (i_2 * 2));
    (reinterpret_cast<__nv_bfloat162*>(&__2))[0] = __float22bfloat162_rn(((float2*)(&v_))[0]);
    ((float2*)(&__1))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&__2))[0]);
    *(float2*)(xs + (i_2 * 2)) = __1;
    float2 __3;
      *(float2*)(&(__3.x)) = tl::mul2(*(float2*)(&(v_.x)), *(float2*)(&(v_.x)));
    *(float2*)(sq + (i_2 * 2)) = __3;
  }
  tot[0] = 0x0p+0f/*0.000000e+00*/;
  #pragma unroll
  for (int rv = 0; rv < 6; ++rv) {
    tot[0] = (tot[0] + sq[rv]);
  }
  tot[0] = tl::AllReduce<tl::SumOp, 256, 1, 0, tl::NamedBarrier<256>>::run(tot[0], (&(workspace[0])));
  #pragma unroll
  for (int i_3 = 0; i_3 < 6; ++i_3) {
    O[(((((int)blockIdx.x) * 1536) + (i_3 * 256)) + ((int)threadIdx.x))] = (((bfloat16_t)(xs[i_3] * rsqrtf(((tot[0] / 0x1.8p+10f/*1.536000e+03*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)))) * G[((i_3 * 256) + ((int)threadIdx.x))]);
  }
}


extern "C" __global__ void k3_land_rms_norm_rbs_b96_nt14400_n1536_off0_sk1_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const float* __restrict__ P);
extern "C" __global__ void __launch_bounds__(256, 1) k3_land_rms_norm_rbs_b96_nt14400_n1536_off0_sk1_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const float* __restrict__ P) {
  float xs[6];
  float sq[6];
  float tot[1];
  extern __shared__ __align__(1024) float workspace[];
  #pragma unroll
  for (int i = 0; i < 3; ++i) {
    float broadcast_var = 0x0p+0f/*0.000000e+00*/;
    *(float2*)(xs + (i * 2)) = make_float2(broadcast_var, broadcast_var);
  }
  #pragma unroll
  for (int i_1 = 0; i_1 < 6; ++i_1) {
    xs[i_1] = (xs[i_1] + P[(((((int)blockIdx.x) * 14400) + (i_1 * 256)) + ((int)threadIdx.x))]);
  }
  #pragma unroll
  for (int i_2 = 0; i_2 < 3; ++i_2) {
    float2 __1;
    uint1 __2;
    float2 v_ = *(float2*)(xs + (i_2 * 2));
    (reinterpret_cast<__nv_bfloat162*>(&__2))[0] = __float22bfloat162_rn(((float2*)(&v_))[0]);
    ((float2*)(&__1))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&__2))[0]);
    *(float2*)(xs + (i_2 * 2)) = __1;
    float2 __3;
      *(float2*)(&(__3.x)) = tl::mul2(*(float2*)(&(v_.x)), *(float2*)(&(v_.x)));
    *(float2*)(sq + (i_2 * 2)) = __3;
  }
  tot[0] = 0x0p+0f/*0.000000e+00*/;
  #pragma unroll
  for (int rv = 0; rv < 6; ++rv) {
    tot[0] = (tot[0] + sq[rv]);
  }
  tot[0] = tl::AllReduce<tl::SumOp, 256, 1, 0, tl::NamedBarrier<256>>::run(tot[0], (&(workspace[0])));
  #pragma unroll
  for (int i_3 = 0; i_3 < 6; ++i_3) {
    O[(((((int)blockIdx.x) * 1536) + (i_3 * 256)) + ((int)threadIdx.x))] = (((bfloat16_t)(xs[i_3] * rsqrtf(((tot[0] / 0x1.8p+10f/*1.536000e+03*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)))) * G[((i_3 * 256) + ((int)threadIdx.x))]);
  }
}


extern "C" __global__ void k3_land_rms_norm_rbs_b128_nt14400_n1536_off0_sk1_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const float* __restrict__ P);
extern "C" __global__ void __launch_bounds__(256, 1) k3_land_rms_norm_rbs_b128_nt14400_n1536_off0_sk1_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const float* __restrict__ P) {
  float xs[6];
  float sq[6];
  float tot[1];
  extern __shared__ __align__(1024) float workspace[];
  #pragma unroll
  for (int i = 0; i < 3; ++i) {
    float broadcast_var = 0x0p+0f/*0.000000e+00*/;
    *(float2*)(xs + (i * 2)) = make_float2(broadcast_var, broadcast_var);
  }
  #pragma unroll
  for (int i_1 = 0; i_1 < 6; ++i_1) {
    xs[i_1] = (xs[i_1] + P[(((((int)blockIdx.x) * 14400) + (i_1 * 256)) + ((int)threadIdx.x))]);
  }
  #pragma unroll
  for (int i_2 = 0; i_2 < 3; ++i_2) {
    float2 __1;
    uint1 __2;
    float2 v_ = *(float2*)(xs + (i_2 * 2));
    (reinterpret_cast<__nv_bfloat162*>(&__2))[0] = __float22bfloat162_rn(((float2*)(&v_))[0]);
    ((float2*)(&__1))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&__2))[0]);
    *(float2*)(xs + (i_2 * 2)) = __1;
    float2 __3;
      *(float2*)(&(__3.x)) = tl::mul2(*(float2*)(&(v_.x)), *(float2*)(&(v_.x)));
    *(float2*)(sq + (i_2 * 2)) = __3;
  }
  tot[0] = 0x0p+0f/*0.000000e+00*/;
  #pragma unroll
  for (int rv = 0; rv < 6; ++rv) {
    tot[0] = (tot[0] + sq[rv]);
  }
  tot[0] = tl::AllReduce<tl::SumOp, 256, 1, 0, tl::NamedBarrier<256>>::run(tot[0], (&(workspace[0])));
  #pragma unroll
  for (int i_3 = 0; i_3 < 6; ++i_3) {
    O[(((((int)blockIdx.x) * 1536) + (i_3 * 256)) + ((int)threadIdx.x))] = (((bfloat16_t)(xs[i_3] * rsqrtf(((tot[0] / 0x1.8p+10f/*1.536000e+03*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)))) * G[((i_3 * 256) + ((int)threadIdx.x))]);
  }
}



// k3_land_batched fused with the round-before-scale norm: MLA's q_a,
// the one place the engine fuses a merge and a norm.
extern "C" int k3_land_rms_norm_rbs_batched(
    const float* P,
    const void* G,
    void* O,
    int b,
    int nt,
    int n,
    int off,
    int split_k,
    cudaStream_t stream) {
  if (b == 1 && nt == 14400 && n == 1536 && off == 0 && split_k == 1) {
    k3_land_rms_norm_rbs_b1_nt14400_n1536_off0_sk1_kernel<<<dim3(1, 1, 1), 256, 1024, stream>>>(
        reinterpret_cast<const bfloat16_t*>(G),
        reinterpret_cast<bfloat16_t*>(O),
        P);
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 2 && nt == 14400 && n == 1536 && off == 0 && split_k == 1) {
    k3_land_rms_norm_rbs_b2_nt14400_n1536_off0_sk1_kernel<<<dim3(2, 1, 1), 256, 1024, stream>>>(
        reinterpret_cast<const bfloat16_t*>(G),
        reinterpret_cast<bfloat16_t*>(O),
        P);
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 4 && nt == 14400 && n == 1536 && off == 0 && split_k == 1) {
    k3_land_rms_norm_rbs_b4_nt14400_n1536_off0_sk1_kernel<<<dim3(4, 1, 1), 256, 1024, stream>>>(
        reinterpret_cast<const bfloat16_t*>(G),
        reinterpret_cast<bfloat16_t*>(O),
        P);
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 8 && nt == 14400 && n == 1536 && off == 0 && split_k == 1) {
    k3_land_rms_norm_rbs_b8_nt14400_n1536_off0_sk1_kernel<<<dim3(8, 1, 1), 256, 1024, stream>>>(
        reinterpret_cast<const bfloat16_t*>(G),
        reinterpret_cast<bfloat16_t*>(O),
        P);
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 16 && nt == 14400 && n == 1536 && off == 0 && split_k == 1) {
    k3_land_rms_norm_rbs_b16_nt14400_n1536_off0_sk1_kernel<<<dim3(16, 1, 1), 256, 1024, stream>>>(
        reinterpret_cast<const bfloat16_t*>(G),
        reinterpret_cast<bfloat16_t*>(O),
        P);
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 32 && nt == 14400 && n == 1536 && off == 0 && split_k == 1) {
    k3_land_rms_norm_rbs_b32_nt14400_n1536_off0_sk1_kernel<<<dim3(32, 1, 1), 256, 1024, stream>>>(
        reinterpret_cast<const bfloat16_t*>(G),
        reinterpret_cast<bfloat16_t*>(O),
        P);
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 48 && nt == 14400 && n == 1536 && off == 0 && split_k == 1) {
    k3_land_rms_norm_rbs_b48_nt14400_n1536_off0_sk1_kernel<<<dim3(48, 1, 1), 256, 1024, stream>>>(
        reinterpret_cast<const bfloat16_t*>(G),
        reinterpret_cast<bfloat16_t*>(O),
        P);
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 64 && nt == 14400 && n == 1536 && off == 0 && split_k == 1) {
    k3_land_rms_norm_rbs_b64_nt14400_n1536_off0_sk1_kernel<<<dim3(64, 1, 1), 256, 1024, stream>>>(
        reinterpret_cast<const bfloat16_t*>(G),
        reinterpret_cast<bfloat16_t*>(O),
        P);
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 96 && nt == 14400 && n == 1536 && off == 0 && split_k == 1) {
    k3_land_rms_norm_rbs_b96_nt14400_n1536_off0_sk1_kernel<<<dim3(96, 1, 1), 256, 1024, stream>>>(
        reinterpret_cast<const bfloat16_t*>(G),
        reinterpret_cast<bfloat16_t*>(O),
        P);
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 128 && nt == 14400 && n == 1536 && off == 0 && split_k == 1) {
    k3_land_rms_norm_rbs_b128_nt14400_n1536_off0_sk1_kernel<<<dim3(128, 1, 1), 256, 1024, stream>>>(
        reinterpret_cast<const bfloat16_t*>(G),
        reinterpret_cast<bfloat16_t*>(O),
        P);
    return static_cast<int>(cudaGetLastError());
  }
  return static_cast<int>(cudaErrorInvalidValue);
}
