// Generated by pegainfer-k3/kernels/generate.py -- do not edit.
#include <cuda_runtime.h>

#if defined(_MSC_VER) && !defined(__clang__) && _MSC_VER < 1940
#define _tl_orig_alignas alignas
#define alignas(N) _tl_orig_alignas((N) <= 64 ? (N) : 64)
#include <cuda.h>
#undef alignas
#define alignas _tl_orig_alignas
#endif
#include <tl_templates/cuda/reduce.h>
#include <tl_templates/cuda/scan.h>
#include <tl_templates/cuda/ldsm.h>
#include <tl_templates/cuda/threadblock_swizzle.h>
#define debug_print_msg k3_mul_sigmoid_batched_debug_print_msg
#define debug_print_buffer_value k3_mul_sigmoid_batched_debug_print_buffer_value
#include <tl_templates/cuda/debug.h>
#undef debug_print_msg
#undef debug_print_buffer_value
#ifdef ENABLE_BF16
#include <tl_templates/cuda/cuda_bf16_fallbacks.cuh>
#endif

extern "C" __global__ void k3_mul_sigmoid_b1_n12288_kernel(const bfloat16_t* __restrict__ A, const bfloat16_t* __restrict__ Bt, bfloat16_t* __restrict__ O);
extern "C" __global__ void __launch_bounds__(256, 1) k3_mul_sigmoid_b1_n12288_kernel(const bfloat16_t* __restrict__ A, const bfloat16_t* __restrict__ Bt, bfloat16_t* __restrict__ O) {
  O[((((int)blockIdx.y) * 256) + ((int)threadIdx.x))] = (A[((((int)blockIdx.y) * 256) + ((int)threadIdx.x))] * ((bfloat16_t)(0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - ((float)Bt[((((int)blockIdx.y) * 256) + ((int)threadIdx.x))])))))));
}


extern "C" __global__ void k3_mul_sigmoid_b2_n12288_kernel(const bfloat16_t* __restrict__ A, const bfloat16_t* __restrict__ Bt, bfloat16_t* __restrict__ O);
extern "C" __global__ void __launch_bounds__(256, 1) k3_mul_sigmoid_b2_n12288_kernel(const bfloat16_t* __restrict__ A, const bfloat16_t* __restrict__ Bt, bfloat16_t* __restrict__ O) {
  O[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] = (A[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] * ((bfloat16_t)(0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - ((float)Bt[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))])))))));
}


extern "C" __global__ void k3_mul_sigmoid_b4_n12288_kernel(const bfloat16_t* __restrict__ A, const bfloat16_t* __restrict__ Bt, bfloat16_t* __restrict__ O);
extern "C" __global__ void __launch_bounds__(256, 1) k3_mul_sigmoid_b4_n12288_kernel(const bfloat16_t* __restrict__ A, const bfloat16_t* __restrict__ Bt, bfloat16_t* __restrict__ O) {
  O[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] = (A[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] * ((bfloat16_t)(0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - ((float)Bt[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))])))))));
}


extern "C" __global__ void k3_mul_sigmoid_b8_n12288_kernel(const bfloat16_t* __restrict__ A, const bfloat16_t* __restrict__ Bt, bfloat16_t* __restrict__ O);
extern "C" __global__ void __launch_bounds__(256, 1) k3_mul_sigmoid_b8_n12288_kernel(const bfloat16_t* __restrict__ A, const bfloat16_t* __restrict__ Bt, bfloat16_t* __restrict__ O) {
  O[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] = (A[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] * ((bfloat16_t)(0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - ((float)Bt[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))])))))));
}


extern "C" __global__ void k3_mul_sigmoid_b16_n12288_kernel(const bfloat16_t* __restrict__ A, const bfloat16_t* __restrict__ Bt, bfloat16_t* __restrict__ O);
extern "C" __global__ void __launch_bounds__(256, 1) k3_mul_sigmoid_b16_n12288_kernel(const bfloat16_t* __restrict__ A, const bfloat16_t* __restrict__ Bt, bfloat16_t* __restrict__ O) {
  O[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] = (A[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] * ((bfloat16_t)(0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - ((float)Bt[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))])))))));
}


extern "C" __global__ void k3_mul_sigmoid_b32_n12288_kernel(const bfloat16_t* __restrict__ A, const bfloat16_t* __restrict__ Bt, bfloat16_t* __restrict__ O);
extern "C" __global__ void __launch_bounds__(256, 1) k3_mul_sigmoid_b32_n12288_kernel(const bfloat16_t* __restrict__ A, const bfloat16_t* __restrict__ Bt, bfloat16_t* __restrict__ O) {
  O[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] = (A[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] * ((bfloat16_t)(0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - ((float)Bt[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))])))))));
}


extern "C" __global__ void k3_mul_sigmoid_b48_n12288_kernel(const bfloat16_t* __restrict__ A, const bfloat16_t* __restrict__ Bt, bfloat16_t* __restrict__ O);
extern "C" __global__ void __launch_bounds__(256, 1) k3_mul_sigmoid_b48_n12288_kernel(const bfloat16_t* __restrict__ A, const bfloat16_t* __restrict__ Bt, bfloat16_t* __restrict__ O) {
  O[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] = (A[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] * ((bfloat16_t)(0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - ((float)Bt[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))])))))));
}


extern "C" __global__ void k3_mul_sigmoid_b64_n12288_kernel(const bfloat16_t* __restrict__ A, const bfloat16_t* __restrict__ Bt, bfloat16_t* __restrict__ O);
extern "C" __global__ void __launch_bounds__(256, 1) k3_mul_sigmoid_b64_n12288_kernel(const bfloat16_t* __restrict__ A, const bfloat16_t* __restrict__ Bt, bfloat16_t* __restrict__ O) {
  O[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] = (A[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] * ((bfloat16_t)(0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - ((float)Bt[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))])))))));
}


extern "C" __global__ void k3_mul_sigmoid_b96_n12288_kernel(const bfloat16_t* __restrict__ A, const bfloat16_t* __restrict__ Bt, bfloat16_t* __restrict__ O);
extern "C" __global__ void __launch_bounds__(256, 1) k3_mul_sigmoid_b96_n12288_kernel(const bfloat16_t* __restrict__ A, const bfloat16_t* __restrict__ Bt, bfloat16_t* __restrict__ O) {
  O[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] = (A[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] * ((bfloat16_t)(0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - ((float)Bt[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))])))))));
}


extern "C" __global__ void k3_mul_sigmoid_b128_n12288_kernel(const bfloat16_t* __restrict__ A, const bfloat16_t* __restrict__ Bt, bfloat16_t* __restrict__ O);
extern "C" __global__ void __launch_bounds__(256, 1) k3_mul_sigmoid_b128_n12288_kernel(const bfloat16_t* __restrict__ A, const bfloat16_t* __restrict__ Bt, bfloat16_t* __restrict__ O) {
  O[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] = (A[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] * ((bfloat16_t)(0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - ((float)Bt[(((((int)blockIdx.x) * 12288) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))])))))));
}



// O = A * bf16(sigmoid(B)), the MLA sigmoid output gate. The sigmoid is
// taken in f32 and lands in bf16 before the product.
extern "C" int k3_mul_sigmoid_batched(
    const void* A,
    const void* Bt,
    void* O,
    int b,
    int n,
    cudaStream_t stream) {
  if (b == 1 && n == 12288) {
    k3_mul_sigmoid_b1_n12288_kernel<<<dim3(1, 48, 1), 256, 0, stream>>>(
        reinterpret_cast<const bfloat16_t*>(A),
        reinterpret_cast<const bfloat16_t*>(Bt),
        reinterpret_cast<bfloat16_t*>(O));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 2 && n == 12288) {
    k3_mul_sigmoid_b2_n12288_kernel<<<dim3(2, 48, 1), 256, 0, stream>>>(
        reinterpret_cast<const bfloat16_t*>(A),
        reinterpret_cast<const bfloat16_t*>(Bt),
        reinterpret_cast<bfloat16_t*>(O));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 4 && n == 12288) {
    k3_mul_sigmoid_b4_n12288_kernel<<<dim3(4, 48, 1), 256, 0, stream>>>(
        reinterpret_cast<const bfloat16_t*>(A),
        reinterpret_cast<const bfloat16_t*>(Bt),
        reinterpret_cast<bfloat16_t*>(O));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 8 && n == 12288) {
    k3_mul_sigmoid_b8_n12288_kernel<<<dim3(8, 48, 1), 256, 0, stream>>>(
        reinterpret_cast<const bfloat16_t*>(A),
        reinterpret_cast<const bfloat16_t*>(Bt),
        reinterpret_cast<bfloat16_t*>(O));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 16 && n == 12288) {
    k3_mul_sigmoid_b16_n12288_kernel<<<dim3(16, 48, 1), 256, 0, stream>>>(
        reinterpret_cast<const bfloat16_t*>(A),
        reinterpret_cast<const bfloat16_t*>(Bt),
        reinterpret_cast<bfloat16_t*>(O));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 32 && n == 12288) {
    k3_mul_sigmoid_b32_n12288_kernel<<<dim3(32, 48, 1), 256, 0, stream>>>(
        reinterpret_cast<const bfloat16_t*>(A),
        reinterpret_cast<const bfloat16_t*>(Bt),
        reinterpret_cast<bfloat16_t*>(O));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 48 && n == 12288) {
    k3_mul_sigmoid_b48_n12288_kernel<<<dim3(48, 48, 1), 256, 0, stream>>>(
        reinterpret_cast<const bfloat16_t*>(A),
        reinterpret_cast<const bfloat16_t*>(Bt),
        reinterpret_cast<bfloat16_t*>(O));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 64 && n == 12288) {
    k3_mul_sigmoid_b64_n12288_kernel<<<dim3(64, 48, 1), 256, 0, stream>>>(
        reinterpret_cast<const bfloat16_t*>(A),
        reinterpret_cast<const bfloat16_t*>(Bt),
        reinterpret_cast<bfloat16_t*>(O));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 96 && n == 12288) {
    k3_mul_sigmoid_b96_n12288_kernel<<<dim3(96, 48, 1), 256, 0, stream>>>(
        reinterpret_cast<const bfloat16_t*>(A),
        reinterpret_cast<const bfloat16_t*>(Bt),
        reinterpret_cast<bfloat16_t*>(O));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 128 && n == 12288) {
    k3_mul_sigmoid_b128_n12288_kernel<<<dim3(128, 48, 1), 256, 0, stream>>>(
        reinterpret_cast<const bfloat16_t*>(A),
        reinterpret_cast<const bfloat16_t*>(Bt),
        reinterpret_cast<bfloat16_t*>(O));
    return static_cast<int>(cudaGetLastError());
  }
  return static_cast<int>(cudaErrorInvalidValue);
}
