// Generated by pegainfer-k3/kernels/generate.py -- do not edit.
#include <cuda_runtime.h>

#if defined(_MSC_VER) && !defined(__clang__) && _MSC_VER < 1940
#define _tl_orig_alignas alignas
#define alignas(N) _tl_orig_alignas((N) <= 64 ? (N) : 64)
#include <cuda.h>
#undef alignas
#define alignas _tl_orig_alignas
#endif
#include <tl_templates/cuda/reduce.h>
#include <tl_templates/cuda/scan.h>
#include <tl_templates/cuda/ldsm.h>
#include <tl_templates/cuda/threadblock_swizzle.h>
#define debug_print_msg k3_rms_norm_rbs_batched_debug_print_msg
#define debug_print_buffer_value k3_rms_norm_rbs_batched_debug_print_buffer_value
#include <tl_templates/cuda/debug.h>
#undef debug_print_msg
#undef debug_print_buffer_value
#ifdef ENABLE_BF16
#include <tl_templates/cuda/cuda_bf16_fallbacks.cuh>
#endif

extern "C" __global__ void k3_rms_norm_rbs_b1_h7168_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ X);
extern "C" __global__ void __launch_bounds__(256, 1) k3_rms_norm_rbs_b1_h7168_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ X) {
  float xs[28];
  float sq[28];
  float tot[1];
  extern __shared__ __align__(1024) float workspace[];
  bfloat16_t G_local_cast_1[4];
  bfloat16_t O_local_cast[4];
  #pragma unroll
  for (int i = 0; i < 7; ++i) {
    float4 __1;
    uint2 v_ = *(uint2*)(X + ((i * 1024) + (((int)threadIdx.x) * 4)));
    ((float2*)(&__1))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v_))[0]);
    ((float2*)(&__1))[1] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v_))[1]);
    *(float4*)(xs + (i * 4)) = __1;
    float4 __2;
      float4 v__1 = *(float4*)(xs + (i * 4));
      *(float2*)(&(__2.x)) = tl::mul2(*(float2*)(&(v__1.x)), *(float2*)(&(v__1.x)));
      *(float2*)(&(__2.z)) = tl::mul2(*(float2*)(&(v__1.z)), *(float2*)(&(v__1.z)));
    *(float4*)(sq + (i * 4)) = __2;
  }
  tot[0] = 0x0p+0f/*0.000000e+00*/;
  #pragma unroll
  for (int rv = 0; rv < 28; ++rv) {
    tot[0] = (tot[0] + sq[(((rv % 7) * 4) + (rv / 7))]);
  }
  tot[0] = tl::AllReduce<tl::SumOp, 256, 1, 0, tl::NamedBarrier<256>>::run(tot[0], (&(workspace[0])));
  #pragma unroll
  for (int i_1 = 0; i_1 < 7; ++i_1) {
    *(uint2*)(G_local_cast_1 + 0) = *(uint2*)(G + ((i_1 * 1024) + (((int)threadIdx.x) * 4)));
    uint2 __3;
      uint2 __4;
      float4 __5;
        float4 v__2 = *(float4*)(xs + (i_1 * 4));
        float4 v__3 = make_float4(rsqrtf(((tot[0] / 0x1.cp+12f/*7.168000e+03*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)), rsqrtf(((tot[0] / 0x1.cp+12f/*7.168000e+03*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)), rsqrtf(((tot[0] / 0x1.cp+12f/*7.168000e+03*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)), rsqrtf(((tot[0] / 0x1.cp+12f/*7.168000e+03*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)));
        *(float2*)(&(__5.x)) = tl::mul2(*(float2*)(&(v__2.x)), *(float2*)(&(v__3.x)));
        *(float2*)(&(__5.z)) = tl::mul2(*(float2*)(&(v__2.z)), *(float2*)(&(v__3.z)));
      (reinterpret_cast<__nv_bfloat162*>(&__4))[0] = __float22bfloat162_rn(((float2*)(&__5))[0]);
      (reinterpret_cast<__nv_bfloat162*>(&__4))[1] = __float22bfloat162_rn(((float2*)(&__5))[1]);
      uint2 v__4 = *(uint2*)(G_local_cast_1 + 0);
      *(uint1*)(&(__3.x)) = tl::to_uint1(tl::mul2(tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(__4.x))), tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(v__4.x)))));
      *(uint1*)(&(__3.y)) = tl::to_uint1(tl::mul2(tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(__4.y))), tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(v__4.y)))));
    *(uint2*)(O_local_cast + 0) = __3;
    *(uint2*)(O + ((i_1 * 1024) + (((int)threadIdx.x) * 4))) = *(uint2*)(O_local_cast + 0);
  }
}


extern "C" __global__ void k3_rms_norm_rbs_b2_h7168_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ X);
extern "C" __global__ void __launch_bounds__(256, 1) k3_rms_norm_rbs_b2_h7168_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ X) {
  float xs[28];
  float sq[28];
  float tot[1];
  extern __shared__ __align__(1024) float workspace[];
  bfloat16_t G_local_cast_1[4];
  bfloat16_t O_local_cast[4];
  #pragma unroll
  for (int i = 0; i < 7; ++i) {
    float4 __1;
    uint2 v_ = *(uint2*)(X + (((((int)blockIdx.x) * 7168) + (i * 1024)) + (((int)threadIdx.x) * 4)));
    ((float2*)(&__1))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v_))[0]);
    ((float2*)(&__1))[1] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v_))[1]);
    *(float4*)(xs + (i * 4)) = __1;
    float4 __2;
      float4 v__1 = *(float4*)(xs + (i * 4));
      *(float2*)(&(__2.x)) = tl::mul2(*(float2*)(&(v__1.x)), *(float2*)(&(v__1.x)));
      *(float2*)(&(__2.z)) = tl::mul2(*(float2*)(&(v__1.z)), *(float2*)(&(v__1.z)));
    *(float4*)(sq + (i * 4)) = __2;
  }
  tot[0] = 0x0p+0f/*0.000000e+00*/;
  #pragma unroll
  for (int rv = 0; rv < 28; ++rv) {
    tot[0] = (tot[0] + sq[(((rv % 7) * 4) + (rv / 7))]);
  }
  tot[0] = tl::AllReduce<tl::SumOp, 256, 1, 0, tl::NamedBarrier<256>>::run(tot[0], (&(workspace[0])));
  #pragma unroll
  for (int i_1 = 0; i_1 < 7; ++i_1) {
    *(uint2*)(G_local_cast_1 + 0) = *(uint2*)(G + ((i_1 * 1024) + (((int)threadIdx.x) * 4)));
    uint2 __3;
      uint2 __4;
      float4 __5;
        float4 v__2 = *(float4*)(xs + (i_1 * 4));
        float4 v__3 = make_float4(rsqrtf(((tot[0] / 0x1.cp+12f/*7.168000e+03*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)), rsqrtf(((tot[0] / 0x1.cp+12f/*7.168000e+03*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)), rsqrtf(((tot[0] / 0x1.cp+12f/*7.168000e+03*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)), rsqrtf(((tot[0] / 0x1.cp+12f/*7.168000e+03*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)));
        *(float2*)(&(__5.x)) = tl::mul2(*(float2*)(&(v__2.x)), *(float2*)(&(v__3.x)));
        *(float2*)(&(__5.z)) = tl::mul2(*(float2*)(&(v__2.z)), *(float2*)(&(v__3.z)));
      (reinterpret_cast<__nv_bfloat162*>(&__4))[0] = __float22bfloat162_rn(((float2*)(&__5))[0]);
      (reinterpret_cast<__nv_bfloat162*>(&__4))[1] = __float22bfloat162_rn(((float2*)(&__5))[1]);
      uint2 v__4 = *(uint2*)(G_local_cast_1 + 0);
      *(uint1*)(&(__3.x)) = tl::to_uint1(tl::mul2(tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(__4.x))), tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(v__4.x)))));
      *(uint1*)(&(__3.y)) = tl::to_uint1(tl::mul2(tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(__4.y))), tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(v__4.y)))));
    *(uint2*)(O_local_cast + 0) = __3;
    *(uint2*)(O + (((((int)blockIdx.x) * 7168) + (i_1 * 1024)) + (((int)threadIdx.x) * 4))) = *(uint2*)(O_local_cast + 0);
  }
}


extern "C" __global__ void k3_rms_norm_rbs_b4_h7168_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ X);
extern "C" __global__ void __launch_bounds__(256, 1) k3_rms_norm_rbs_b4_h7168_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ X) {
  float xs[28];
  float sq[28];
  float tot[1];
  extern __shared__ __align__(1024) float workspace[];
  bfloat16_t G_local_cast_1[4];
  bfloat16_t O_local_cast[4];
  #pragma unroll
  for (int i = 0; i < 7; ++i) {
    float4 __1;
    uint2 v_ = *(uint2*)(X + (((((int)blockIdx.x) * 7168) + (i * 1024)) + (((int)threadIdx.x) * 4)));
    ((float2*)(&__1))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v_))[0]);
    ((float2*)(&__1))[1] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v_))[1]);
    *(float4*)(xs + (i * 4)) = __1;
    float4 __2;
      float4 v__1 = *(float4*)(xs + (i * 4));
      *(float2*)(&(__2.x)) = tl::mul2(*(float2*)(&(v__1.x)), *(float2*)(&(v__1.x)));
      *(float2*)(&(__2.z)) = tl::mul2(*(float2*)(&(v__1.z)), *(float2*)(&(v__1.z)));
    *(float4*)(sq + (i * 4)) = __2;
  }
  tot[0] = 0x0p+0f/*0.000000e+00*/;
  #pragma unroll
  for (int rv = 0; rv < 28; ++rv) {
    tot[0] = (tot[0] + sq[(((rv % 7) * 4) + (rv / 7))]);
  }
  tot[0] = tl::AllReduce<tl::SumOp, 256, 1, 0, tl::NamedBarrier<256>>::run(tot[0], (&(workspace[0])));
  #pragma unroll
  for (int i_1 = 0; i_1 < 7; ++i_1) {
    *(uint2*)(G_local_cast_1 + 0) = *(uint2*)(G + ((i_1 * 1024) + (((int)threadIdx.x) * 4)));
    uint2 __3;
      uint2 __4;
      float4 __5;
        float4 v__2 = *(float4*)(xs + (i_1 * 4));
        float4 v__3 = make_float4(rsqrtf(((tot[0] / 0x1.cp+12f/*7.168000e+03*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)), rsqrtf(((tot[0] / 0x1.cp+12f/*7.168000e+03*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)), rsqrtf(((tot[0] / 0x1.cp+12f/*7.168000e+03*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)), rsqrtf(((tot[0] / 0x1.cp+12f/*7.168000e+03*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)));
        *(float2*)(&(__5.x)) = tl::mul2(*(float2*)(&(v__2.x)), *(float2*)(&(v__3.x)));
        *(float2*)(&(__5.z)) = tl::mul2(*(float2*)(&(v__2.z)), *(float2*)(&(v__3.z)));
      (reinterpret_cast<__nv_bfloat162*>(&__4))[0] = __float22bfloat162_rn(((float2*)(&__5))[0]);
      (reinterpret_cast<__nv_bfloat162*>(&__4))[1] = __float22bfloat162_rn(((float2*)(&__5))[1]);
      uint2 v__4 = *(uint2*)(G_local_cast_1 + 0);
      *(uint1*)(&(__3.x)) = tl::to_uint1(tl::mul2(tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(__4.x))), tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(v__4.x)))));
      *(uint1*)(&(__3.y)) = tl::to_uint1(tl::mul2(tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(__4.y))), tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(v__4.y)))));
    *(uint2*)(O_local_cast + 0) = __3;
    *(uint2*)(O + (((((int)blockIdx.x) * 7168) + (i_1 * 1024)) + (((int)threadIdx.x) * 4))) = *(uint2*)(O_local_cast + 0);
  }
}


extern "C" __global__ void k3_rms_norm_rbs_b8_h7168_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ X);
extern "C" __global__ void __launch_bounds__(256, 1) k3_rms_norm_rbs_b8_h7168_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ X) {
  float xs[28];
  float sq[28];
  float tot[1];
  extern __shared__ __align__(1024) float workspace[];
  bfloat16_t G_local_cast_1[4];
  bfloat16_t O_local_cast[4];
  #pragma unroll
  for (int i = 0; i < 7; ++i) {
    float4 __1;
    uint2 v_ = *(uint2*)(X + (((((int)blockIdx.x) * 7168) + (i * 1024)) + (((int)threadIdx.x) * 4)));
    ((float2*)(&__1))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v_))[0]);
    ((float2*)(&__1))[1] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v_))[1]);
    *(float4*)(xs + (i * 4)) = __1;
    float4 __2;
      float4 v__1 = *(float4*)(xs + (i * 4));
      *(float2*)(&(__2.x)) = tl::mul2(*(float2*)(&(v__1.x)), *(float2*)(&(v__1.x)));
      *(float2*)(&(__2.z)) = tl::mul2(*(float2*)(&(v__1.z)), *(float2*)(&(v__1.z)));
    *(float4*)(sq + (i * 4)) = __2;
  }
  tot[0] = 0x0p+0f/*0.000000e+00*/;
  #pragma unroll
  for (int rv = 0; rv < 28; ++rv) {
    tot[0] = (tot[0] + sq[(((rv % 7) * 4) + (rv / 7))]);
  }
  tot[0] = tl::AllReduce<tl::SumOp, 256, 1, 0, tl::NamedBarrier<256>>::run(tot[0], (&(workspace[0])));
  #pragma unroll
  for (int i_1 = 0; i_1 < 7; ++i_1) {
    *(uint2*)(G_local_cast_1 + 0) = *(uint2*)(G + ((i_1 * 1024) + (((int)threadIdx.x) * 4)));
    uint2 __3;
      uint2 __4;
      float4 __5;
        float4 v__2 = *(float4*)(xs + (i_1 * 4));
        float4 v__3 = make_float4(rsqrtf(((tot[0] / 0x1.cp+12f/*7.168000e+03*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)), rsqrtf(((tot[0] / 0x1.cp+12f/*7.168000e+03*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)), rsqrtf(((tot[0] / 0x1.cp+12f/*7.168000e+03*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)), rsqrtf(((tot[0] / 0x1.cp+12f/*7.168000e+03*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)));
        *(float2*)(&(__5.x)) = tl::mul2(*(float2*)(&(v__2.x)), *(float2*)(&(v__3.x)));
        *(float2*)(&(__5.z)) = tl::mul2(*(float2*)(&(v__2.z)), *(float2*)(&(v__3.z)));
      (reinterpret_cast<__nv_bfloat162*>(&__4))[0] = __float22bfloat162_rn(((float2*)(&__5))[0]);
      (reinterpret_cast<__nv_bfloat162*>(&__4))[1] = __float22bfloat162_rn(((float2*)(&__5))[1]);
      uint2 v__4 = *(uint2*)(G_local_cast_1 + 0);
      *(uint1*)(&(__3.x)) = tl::to_uint1(tl::mul2(tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(__4.x))), tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(v__4.x)))));
      *(uint1*)(&(__3.y)) = tl::to_uint1(tl::mul2(tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(__4.y))), tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(v__4.y)))));
    *(uint2*)(O_local_cast + 0) = __3;
    *(uint2*)(O + (((((int)blockIdx.x) * 7168) + (i_1 * 1024)) + (((int)threadIdx.x) * 4))) = *(uint2*)(O_local_cast + 0);
  }
}


extern "C" __global__ void k3_rms_norm_rbs_b16_h7168_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ X);
extern "C" __global__ void __launch_bounds__(256, 1) k3_rms_norm_rbs_b16_h7168_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ X) {
  float xs[28];
  float sq[28];
  float tot[1];
  extern __shared__ __align__(1024) float workspace[];
  bfloat16_t G_local_cast_1[4];
  bfloat16_t O_local_cast[4];
  #pragma unroll
  for (int i = 0; i < 7; ++i) {
    float4 __1;
    uint2 v_ = *(uint2*)(X + (((((int)blockIdx.x) * 7168) + (i * 1024)) + (((int)threadIdx.x) * 4)));
    ((float2*)(&__1))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v_))[0]);
    ((float2*)(&__1))[1] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v_))[1]);
    *(float4*)(xs + (i * 4)) = __1;
    float4 __2;
      float4 v__1 = *(float4*)(xs + (i * 4));
      *(float2*)(&(__2.x)) = tl::mul2(*(float2*)(&(v__1.x)), *(float2*)(&(v__1.x)));
      *(float2*)(&(__2.z)) = tl::mul2(*(float2*)(&(v__1.z)), *(float2*)(&(v__1.z)));
    *(float4*)(sq + (i * 4)) = __2;
  }
  tot[0] = 0x0p+0f/*0.000000e+00*/;
  #pragma unroll
  for (int rv = 0; rv < 28; ++rv) {
    tot[0] = (tot[0] + sq[(((rv % 7) * 4) + (rv / 7))]);
  }
  tot[0] = tl::AllReduce<tl::SumOp, 256, 1, 0, tl::NamedBarrier<256>>::run(tot[0], (&(workspace[0])));
  #pragma unroll
  for (int i_1 = 0; i_1 < 7; ++i_1) {
    *(uint2*)(G_local_cast_1 + 0) = *(uint2*)(G + ((i_1 * 1024) + (((int)threadIdx.x) * 4)));
    uint2 __3;
      uint2 __4;
      float4 __5;
        float4 v__2 = *(float4*)(xs + (i_1 * 4));
        float4 v__3 = make_float4(rsqrtf(((tot[0] / 0x1.cp+12f/*7.168000e+03*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)), rsqrtf(((tot[0] / 0x1.cp+12f/*7.168000e+03*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)), rsqrtf(((tot[0] / 0x1.cp+12f/*7.168000e+03*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)), rsqrtf(((tot[0] / 0x1.cp+12f/*7.168000e+03*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)));
        *(float2*)(&(__5.x)) = tl::mul2(*(float2*)(&(v__2.x)), *(float2*)(&(v__3.x)));
        *(float2*)(&(__5.z)) = tl::mul2(*(float2*)(&(v__2.z)), *(float2*)(&(v__3.z)));
      (reinterpret_cast<__nv_bfloat162*>(&__4))[0] = __float22bfloat162_rn(((float2*)(&__5))[0]);
      (reinterpret_cast<__nv_bfloat162*>(&__4))[1] = __float22bfloat162_rn(((float2*)(&__5))[1]);
      uint2 v__4 = *(uint2*)(G_local_cast_1 + 0);
      *(uint1*)(&(__3.x)) = tl::to_uint1(tl::mul2(tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(__4.x))), tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(v__4.x)))));
      *(uint1*)(&(__3.y)) = tl::to_uint1(tl::mul2(tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(__4.y))), tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(v__4.y)))));
    *(uint2*)(O_local_cast + 0) = __3;
    *(uint2*)(O + (((((int)blockIdx.x) * 7168) + (i_1 * 1024)) + (((int)threadIdx.x) * 4))) = *(uint2*)(O_local_cast + 0);
  }
}


extern "C" __global__ void k3_rms_norm_rbs_b32_h7168_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ X);
extern "C" __global__ void __launch_bounds__(256, 1) k3_rms_norm_rbs_b32_h7168_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ X) {
  float xs[28];
  float sq[28];
  float tot[1];
  extern __shared__ __align__(1024) float workspace[];
  bfloat16_t G_local_cast_1[4];
  bfloat16_t O_local_cast[4];
  #pragma unroll
  for (int i = 0; i < 7; ++i) {
    float4 __1;
    uint2 v_ = *(uint2*)(X + (((((int)blockIdx.x) * 7168) + (i * 1024)) + (((int)threadIdx.x) * 4)));
    ((float2*)(&__1))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v_))[0]);
    ((float2*)(&__1))[1] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v_))[1]);
    *(float4*)(xs + (i * 4)) = __1;
    float4 __2;
      float4 v__1 = *(float4*)(xs + (i * 4));
      *(float2*)(&(__2.x)) = tl::mul2(*(float2*)(&(v__1.x)), *(float2*)(&(v__1.x)));
      *(float2*)(&(__2.z)) = tl::mul2(*(float2*)(&(v__1.z)), *(float2*)(&(v__1.z)));
    *(float4*)(sq + (i * 4)) = __2;
  }
  tot[0] = 0x0p+0f/*0.000000e+00*/;
  #pragma unroll
  for (int rv = 0; rv < 28; ++rv) {
    tot[0] = (tot[0] + sq[(((rv % 7) * 4) + (rv / 7))]);
  }
  tot[0] = tl::AllReduce<tl::SumOp, 256, 1, 0, tl::NamedBarrier<256>>::run(tot[0], (&(workspace[0])));
  #pragma unroll
  for (int i_1 = 0; i_1 < 7; ++i_1) {
    *(uint2*)(G_local_cast_1 + 0) = *(uint2*)(G + ((i_1 * 1024) + (((int)threadIdx.x) * 4)));
    uint2 __3;
      uint2 __4;
      float4 __5;
        float4 v__2 = *(float4*)(xs + (i_1 * 4));
        float4 v__3 = make_float4(rsqrtf(((tot[0] / 0x1.cp+12f/*7.168000e+03*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)), rsqrtf(((tot[0] / 0x1.cp+12f/*7.168000e+03*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)), rsqrtf(((tot[0] / 0x1.cp+12f/*7.168000e+03*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)), rsqrtf(((tot[0] / 0x1.cp+12f/*7.168000e+03*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)));
        *(float2*)(&(__5.x)) = tl::mul2(*(float2*)(&(v__2.x)), *(float2*)(&(v__3.x)));
        *(float2*)(&(__5.z)) = tl::mul2(*(float2*)(&(v__2.z)), *(float2*)(&(v__3.z)));
      (reinterpret_cast<__nv_bfloat162*>(&__4))[0] = __float22bfloat162_rn(((float2*)(&__5))[0]);
      (reinterpret_cast<__nv_bfloat162*>(&__4))[1] = __float22bfloat162_rn(((float2*)(&__5))[1]);
      uint2 v__4 = *(uint2*)(G_local_cast_1 + 0);
      *(uint1*)(&(__3.x)) = tl::to_uint1(tl::mul2(tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(__4.x))), tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(v__4.x)))));
      *(uint1*)(&(__3.y)) = tl::to_uint1(tl::mul2(tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(__4.y))), tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(v__4.y)))));
    *(uint2*)(O_local_cast + 0) = __3;
    *(uint2*)(O + (((((int)blockIdx.x) * 7168) + (i_1 * 1024)) + (((int)threadIdx.x) * 4))) = *(uint2*)(O_local_cast + 0);
  }
}


extern "C" __global__ void k3_rms_norm_rbs_b48_h7168_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ X);
extern "C" __global__ void __launch_bounds__(256, 1) k3_rms_norm_rbs_b48_h7168_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ X) {
  float xs[28];
  float sq[28];
  float tot[1];
  extern __shared__ __align__(1024) float workspace[];
  bfloat16_t G_local_cast_1[4];
  bfloat16_t O_local_cast[4];
  #pragma unroll
  for (int i = 0; i < 7; ++i) {
    float4 __1;
    uint2 v_ = *(uint2*)(X + (((((int)blockIdx.x) * 7168) + (i * 1024)) + (((int)threadIdx.x) * 4)));
    ((float2*)(&__1))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v_))[0]);
    ((float2*)(&__1))[1] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v_))[1]);
    *(float4*)(xs + (i * 4)) = __1;
    float4 __2;
      float4 v__1 = *(float4*)(xs + (i * 4));
      *(float2*)(&(__2.x)) = tl::mul2(*(float2*)(&(v__1.x)), *(float2*)(&(v__1.x)));
      *(float2*)(&(__2.z)) = tl::mul2(*(float2*)(&(v__1.z)), *(float2*)(&(v__1.z)));
    *(float4*)(sq + (i * 4)) = __2;
  }
  tot[0] = 0x0p+0f/*0.000000e+00*/;
  #pragma unroll
  for (int rv = 0; rv < 28; ++rv) {
    tot[0] = (tot[0] + sq[(((rv % 7) * 4) + (rv / 7))]);
  }
  tot[0] = tl::AllReduce<tl::SumOp, 256, 1, 0, tl::NamedBarrier<256>>::run(tot[0], (&(workspace[0])));
  #pragma unroll
  for (int i_1 = 0; i_1 < 7; ++i_1) {
    *(uint2*)(G_local_cast_1 + 0) = *(uint2*)(G + ((i_1 * 1024) + (((int)threadIdx.x) * 4)));
    uint2 __3;
      uint2 __4;
      float4 __5;
        float4 v__2 = *(float4*)(xs + (i_1 * 4));
        float4 v__3 = make_float4(rsqrtf(((tot[0] / 0x1.cp+12f/*7.168000e+03*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)), rsqrtf(((tot[0] / 0x1.cp+12f/*7.168000e+03*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)), rsqrtf(((tot[0] / 0x1.cp+12f/*7.168000e+03*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)), rsqrtf(((tot[0] / 0x1.cp+12f/*7.168000e+03*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)));
        *(float2*)(&(__5.x)) = tl::mul2(*(float2*)(&(v__2.x)), *(float2*)(&(v__3.x)));
        *(float2*)(&(__5.z)) = tl::mul2(*(float2*)(&(v__2.z)), *(float2*)(&(v__3.z)));
      (reinterpret_cast<__nv_bfloat162*>(&__4))[0] = __float22bfloat162_rn(((float2*)(&__5))[0]);
      (reinterpret_cast<__nv_bfloat162*>(&__4))[1] = __float22bfloat162_rn(((float2*)(&__5))[1]);
      uint2 v__4 = *(uint2*)(G_local_cast_1 + 0);
      *(uint1*)(&(__3.x)) = tl::to_uint1(tl::mul2(tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(__4.x))), tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(v__4.x)))));
      *(uint1*)(&(__3.y)) = tl::to_uint1(tl::mul2(tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(__4.y))), tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(v__4.y)))));
    *(uint2*)(O_local_cast + 0) = __3;
    *(uint2*)(O + (((((int)blockIdx.x) * 7168) + (i_1 * 1024)) + (((int)threadIdx.x) * 4))) = *(uint2*)(O_local_cast + 0);
  }
}


extern "C" __global__ void k3_rms_norm_rbs_b64_h7168_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ X);
extern "C" __global__ void __launch_bounds__(256, 1) k3_rms_norm_rbs_b64_h7168_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ X) {
  float xs[28];
  float sq[28];
  float tot[1];
  extern __shared__ __align__(1024) float workspace[];
  bfloat16_t G_local_cast_1[4];
  bfloat16_t O_local_cast[4];
  #pragma unroll
  for (int i = 0; i < 7; ++i) {
    float4 __1;
    uint2 v_ = *(uint2*)(X + (((((int)blockIdx.x) * 7168) + (i * 1024)) + (((int)threadIdx.x) * 4)));
    ((float2*)(&__1))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v_))[0]);
    ((float2*)(&__1))[1] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v_))[1]);
    *(float4*)(xs + (i * 4)) = __1;
    float4 __2;
      float4 v__1 = *(float4*)(xs + (i * 4));
      *(float2*)(&(__2.x)) = tl::mul2(*(float2*)(&(v__1.x)), *(float2*)(&(v__1.x)));
      *(float2*)(&(__2.z)) = tl::mul2(*(float2*)(&(v__1.z)), *(float2*)(&(v__1.z)));
    *(float4*)(sq + (i * 4)) = __2;
  }
  tot[0] = 0x0p+0f/*0.000000e+00*/;
  #pragma unroll
  for (int rv = 0; rv < 28; ++rv) {
    tot[0] = (tot[0] + sq[(((rv % 7) * 4) + (rv / 7))]);
  }
  tot[0] = tl::AllReduce<tl::SumOp, 256, 1, 0, tl::NamedBarrier<256>>::run(tot[0], (&(workspace[0])));
  #pragma unroll
  for (int i_1 = 0; i_1 < 7; ++i_1) {
    *(uint2*)(G_local_cast_1 + 0) = *(uint2*)(G + ((i_1 * 1024) + (((int)threadIdx.x) * 4)));
    uint2 __3;
      uint2 __4;
      float4 __5;
        float4 v__2 = *(float4*)(xs + (i_1 * 4));
        float4 v__3 = make_float4(rsqrtf(((tot[0] / 0x1.cp+12f/*7.168000e+03*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)), rsqrtf(((tot[0] / 0x1.cp+12f/*7.168000e+03*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)), rsqrtf(((tot[0] / 0x1.cp+12f/*7.168000e+03*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)), rsqrtf(((tot[0] / 0x1.cp+12f/*7.168000e+03*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)));
        *(float2*)(&(__5.x)) = tl::mul2(*(float2*)(&(v__2.x)), *(float2*)(&(v__3.x)));
        *(float2*)(&(__5.z)) = tl::mul2(*(float2*)(&(v__2.z)), *(float2*)(&(v__3.z)));
      (reinterpret_cast<__nv_bfloat162*>(&__4))[0] = __float22bfloat162_rn(((float2*)(&__5))[0]);
      (reinterpret_cast<__nv_bfloat162*>(&__4))[1] = __float22bfloat162_rn(((float2*)(&__5))[1]);
      uint2 v__4 = *(uint2*)(G_local_cast_1 + 0);
      *(uint1*)(&(__3.x)) = tl::to_uint1(tl::mul2(tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(__4.x))), tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(v__4.x)))));
      *(uint1*)(&(__3.y)) = tl::to_uint1(tl::mul2(tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(__4.y))), tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(v__4.y)))));
    *(uint2*)(O_local_cast + 0) = __3;
    *(uint2*)(O + (((((int)blockIdx.x) * 7168) + (i_1 * 1024)) + (((int)threadIdx.x) * 4))) = *(uint2*)(O_local_cast + 0);
  }
}


extern "C" __global__ void k3_rms_norm_rbs_b96_h7168_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ X);
extern "C" __global__ void __launch_bounds__(256, 1) k3_rms_norm_rbs_b96_h7168_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ X) {
  float xs[28];
  float sq[28];
  float tot[1];
  extern __shared__ __align__(1024) float workspace[];
  bfloat16_t G_local_cast_1[4];
  bfloat16_t O_local_cast[4];
  #pragma unroll
  for (int i = 0; i < 7; ++i) {
    float4 __1;
    uint2 v_ = *(uint2*)(X + (((((int)blockIdx.x) * 7168) + (i * 1024)) + (((int)threadIdx.x) * 4)));
    ((float2*)(&__1))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v_))[0]);
    ((float2*)(&__1))[1] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v_))[1]);
    *(float4*)(xs + (i * 4)) = __1;
    float4 __2;
      float4 v__1 = *(float4*)(xs + (i * 4));
      *(float2*)(&(__2.x)) = tl::mul2(*(float2*)(&(v__1.x)), *(float2*)(&(v__1.x)));
      *(float2*)(&(__2.z)) = tl::mul2(*(float2*)(&(v__1.z)), *(float2*)(&(v__1.z)));
    *(float4*)(sq + (i * 4)) = __2;
  }
  tot[0] = 0x0p+0f/*0.000000e+00*/;
  #pragma unroll
  for (int rv = 0; rv < 28; ++rv) {
    tot[0] = (tot[0] + sq[(((rv % 7) * 4) + (rv / 7))]);
  }
  tot[0] = tl::AllReduce<tl::SumOp, 256, 1, 0, tl::NamedBarrier<256>>::run(tot[0], (&(workspace[0])));
  #pragma unroll
  for (int i_1 = 0; i_1 < 7; ++i_1) {
    *(uint2*)(G_local_cast_1 + 0) = *(uint2*)(G + ((i_1 * 1024) + (((int)threadIdx.x) * 4)));
    uint2 __3;
      uint2 __4;
      float4 __5;
        float4 v__2 = *(float4*)(xs + (i_1 * 4));
        float4 v__3 = make_float4(rsqrtf(((tot[0] / 0x1.cp+12f/*7.168000e+03*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)), rsqrtf(((tot[0] / 0x1.cp+12f/*7.168000e+03*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)), rsqrtf(((tot[0] / 0x1.cp+12f/*7.168000e+03*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)), rsqrtf(((tot[0] / 0x1.cp+12f/*7.168000e+03*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)));
        *(float2*)(&(__5.x)) = tl::mul2(*(float2*)(&(v__2.x)), *(float2*)(&(v__3.x)));
        *(float2*)(&(__5.z)) = tl::mul2(*(float2*)(&(v__2.z)), *(float2*)(&(v__3.z)));
      (reinterpret_cast<__nv_bfloat162*>(&__4))[0] = __float22bfloat162_rn(((float2*)(&__5))[0]);
      (reinterpret_cast<__nv_bfloat162*>(&__4))[1] = __float22bfloat162_rn(((float2*)(&__5))[1]);
      uint2 v__4 = *(uint2*)(G_local_cast_1 + 0);
      *(uint1*)(&(__3.x)) = tl::to_uint1(tl::mul2(tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(__4.x))), tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(v__4.x)))));
      *(uint1*)(&(__3.y)) = tl::to_uint1(tl::mul2(tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(__4.y))), tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(v__4.y)))));
    *(uint2*)(O_local_cast + 0) = __3;
    *(uint2*)(O + (((((int)blockIdx.x) * 7168) + (i_1 * 1024)) + (((int)threadIdx.x) * 4))) = *(uint2*)(O_local_cast + 0);
  }
}


extern "C" __global__ void k3_rms_norm_rbs_b128_h7168_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ X);
extern "C" __global__ void __launch_bounds__(256, 1) k3_rms_norm_rbs_b128_h7168_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ X) {
  float xs[28];
  float sq[28];
  float tot[1];
  extern __shared__ __align__(1024) float workspace[];
  bfloat16_t G_local_cast_1[4];
  bfloat16_t O_local_cast[4];
  #pragma unroll
  for (int i = 0; i < 7; ++i) {
    float4 __1;
    uint2 v_ = *(uint2*)(X + (((((int)blockIdx.x) * 7168) + (i * 1024)) + (((int)threadIdx.x) * 4)));
    ((float2*)(&__1))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v_))[0]);
    ((float2*)(&__1))[1] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v_))[1]);
    *(float4*)(xs + (i * 4)) = __1;
    float4 __2;
      float4 v__1 = *(float4*)(xs + (i * 4));
      *(float2*)(&(__2.x)) = tl::mul2(*(float2*)(&(v__1.x)), *(float2*)(&(v__1.x)));
      *(float2*)(&(__2.z)) = tl::mul2(*(float2*)(&(v__1.z)), *(float2*)(&(v__1.z)));
    *(float4*)(sq + (i * 4)) = __2;
  }
  tot[0] = 0x0p+0f/*0.000000e+00*/;
  #pragma unroll
  for (int rv = 0; rv < 28; ++rv) {
    tot[0] = (tot[0] + sq[(((rv % 7) * 4) + (rv / 7))]);
  }
  tot[0] = tl::AllReduce<tl::SumOp, 256, 1, 0, tl::NamedBarrier<256>>::run(tot[0], (&(workspace[0])));
  #pragma unroll
  for (int i_1 = 0; i_1 < 7; ++i_1) {
    *(uint2*)(G_local_cast_1 + 0) = *(uint2*)(G + ((i_1 * 1024) + (((int)threadIdx.x) * 4)));
    uint2 __3;
      uint2 __4;
      float4 __5;
        float4 v__2 = *(float4*)(xs + (i_1 * 4));
        float4 v__3 = make_float4(rsqrtf(((tot[0] / 0x1.cp+12f/*7.168000e+03*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)), rsqrtf(((tot[0] / 0x1.cp+12f/*7.168000e+03*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)), rsqrtf(((tot[0] / 0x1.cp+12f/*7.168000e+03*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)), rsqrtf(((tot[0] / 0x1.cp+12f/*7.168000e+03*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)));
        *(float2*)(&(__5.x)) = tl::mul2(*(float2*)(&(v__2.x)), *(float2*)(&(v__3.x)));
        *(float2*)(&(__5.z)) = tl::mul2(*(float2*)(&(v__2.z)), *(float2*)(&(v__3.z)));
      (reinterpret_cast<__nv_bfloat162*>(&__4))[0] = __float22bfloat162_rn(((float2*)(&__5))[0]);
      (reinterpret_cast<__nv_bfloat162*>(&__4))[1] = __float22bfloat162_rn(((float2*)(&__5))[1]);
      uint2 v__4 = *(uint2*)(G_local_cast_1 + 0);
      *(uint1*)(&(__3.x)) = tl::to_uint1(tl::mul2(tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(__4.x))), tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(v__4.x)))));
      *(uint1*)(&(__3.y)) = tl::to_uint1(tl::mul2(tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(__4.y))), tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(v__4.y)))));
    *(uint2*)(O_local_cast + 0) = __3;
    *(uint2*)(O + (((((int)blockIdx.x) * 7168) + (i_1 * 1024)) + (((int)threadIdx.x) * 4))) = *(uint2*)(O_local_cast + 0);
  }
}


extern "C" __global__ void k3_rms_norm_rbs_b1_h512_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ X);
extern "C" __global__ void __launch_bounds__(256, 1) k3_rms_norm_rbs_b1_h512_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ X) {
  float xs[2];
  float sq[2];
  float tot[1];
  extern __shared__ __align__(1024) float workspace[];
  bfloat16_t G_local_cast_1[2];
  bfloat16_t O_local_cast[2];
  float2 __1;
  uint1 v_ = *(uint1*)(X + (((int)threadIdx.x) * 2));
  ((float2*)(&__1))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v_))[0]);
  *(float2*)(xs + 0) = __1;
  float2 __2;
    float2 v__1 = *(float2*)(xs + 0);
    *(float2*)(&(__2.x)) = tl::mul2(*(float2*)(&(v__1.x)), *(float2*)(&(v__1.x)));
  *(float2*)(sq + 0) = __2;
  tot[0] = 0x0p+0f/*0.000000e+00*/;
  #pragma unroll
  for (int rv = 0; rv < 2; ++rv) {
    tot[0] = (tot[0] + sq[rv]);
  }
  tot[0] = tl::AllReduce<tl::SumOp, 256, 1, 0, tl::NamedBarrier<256>>::run(tot[0], (&(workspace[0])));
  *(uint1*)(G_local_cast_1 + 0) = *(uint1*)(G + (((int)threadIdx.x) * 2));
  uint1 __3;
    uint1 __4;
    float2 __5;
      float2 v__2 = *(float2*)(xs + 0);
      float2 v__3 = make_float2(rsqrtf(((tot[0] / 0x1p+9f/*5.120000e+02*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)), rsqrtf(((tot[0] / 0x1p+9f/*5.120000e+02*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)));
      *(float2*)(&(__5.x)) = tl::mul2(*(float2*)(&(v__2.x)), *(float2*)(&(v__3.x)));
    (reinterpret_cast<__nv_bfloat162*>(&__4))[0] = __float22bfloat162_rn(((float2*)(&__5))[0]);
    uint1 v__4 = *(uint1*)(G_local_cast_1 + 0);
    *(uint1*)(&(__3.x)) = tl::to_uint1(tl::mul2(tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(__4.x))), tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(v__4.x)))));
  *(uint1*)(O_local_cast + 0) = __3;
  *(uint1*)(O + (((int)threadIdx.x) * 2)) = *(uint1*)(O_local_cast + 0);
}


extern "C" __global__ void k3_rms_norm_rbs_b2_h512_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ X);
extern "C" __global__ void __launch_bounds__(256, 1) k3_rms_norm_rbs_b2_h512_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ X) {
  float xs[2];
  float sq[2];
  float tot[1];
  extern __shared__ __align__(1024) float workspace[];
  bfloat16_t G_local_cast_1[2];
  bfloat16_t O_local_cast[2];
  float2 __1;
  uint1 v_ = *(uint1*)(X + ((((int)blockIdx.x) * 512) + (((int)threadIdx.x) * 2)));
  ((float2*)(&__1))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v_))[0]);
  *(float2*)(xs + 0) = __1;
  float2 __2;
    float2 v__1 = *(float2*)(xs + 0);
    *(float2*)(&(__2.x)) = tl::mul2(*(float2*)(&(v__1.x)), *(float2*)(&(v__1.x)));
  *(float2*)(sq + 0) = __2;
  tot[0] = 0x0p+0f/*0.000000e+00*/;
  #pragma unroll
  for (int rv = 0; rv < 2; ++rv) {
    tot[0] = (tot[0] + sq[rv]);
  }
  tot[0] = tl::AllReduce<tl::SumOp, 256, 1, 0, tl::NamedBarrier<256>>::run(tot[0], (&(workspace[0])));
  *(uint1*)(G_local_cast_1 + 0) = *(uint1*)(G + (((int)threadIdx.x) * 2));
  uint1 __3;
    uint1 __4;
    float2 __5;
      float2 v__2 = *(float2*)(xs + 0);
      float2 v__3 = make_float2(rsqrtf(((tot[0] / 0x1p+9f/*5.120000e+02*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)), rsqrtf(((tot[0] / 0x1p+9f/*5.120000e+02*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)));
      *(float2*)(&(__5.x)) = tl::mul2(*(float2*)(&(v__2.x)), *(float2*)(&(v__3.x)));
    (reinterpret_cast<__nv_bfloat162*>(&__4))[0] = __float22bfloat162_rn(((float2*)(&__5))[0]);
    uint1 v__4 = *(uint1*)(G_local_cast_1 + 0);
    *(uint1*)(&(__3.x)) = tl::to_uint1(tl::mul2(tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(__4.x))), tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(v__4.x)))));
  *(uint1*)(O_local_cast + 0) = __3;
  *(uint1*)(O + ((((int)blockIdx.x) * 512) + (((int)threadIdx.x) * 2))) = *(uint1*)(O_local_cast + 0);
}


extern "C" __global__ void k3_rms_norm_rbs_b4_h512_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ X);
extern "C" __global__ void __launch_bounds__(256, 1) k3_rms_norm_rbs_b4_h512_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ X) {
  float xs[2];
  float sq[2];
  float tot[1];
  extern __shared__ __align__(1024) float workspace[];
  bfloat16_t G_local_cast_1[2];
  bfloat16_t O_local_cast[2];
  float2 __1;
  uint1 v_ = *(uint1*)(X + ((((int)blockIdx.x) * 512) + (((int)threadIdx.x) * 2)));
  ((float2*)(&__1))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v_))[0]);
  *(float2*)(xs + 0) = __1;
  float2 __2;
    float2 v__1 = *(float2*)(xs + 0);
    *(float2*)(&(__2.x)) = tl::mul2(*(float2*)(&(v__1.x)), *(float2*)(&(v__1.x)));
  *(float2*)(sq + 0) = __2;
  tot[0] = 0x0p+0f/*0.000000e+00*/;
  #pragma unroll
  for (int rv = 0; rv < 2; ++rv) {
    tot[0] = (tot[0] + sq[rv]);
  }
  tot[0] = tl::AllReduce<tl::SumOp, 256, 1, 0, tl::NamedBarrier<256>>::run(tot[0], (&(workspace[0])));
  *(uint1*)(G_local_cast_1 + 0) = *(uint1*)(G + (((int)threadIdx.x) * 2));
  uint1 __3;
    uint1 __4;
    float2 __5;
      float2 v__2 = *(float2*)(xs + 0);
      float2 v__3 = make_float2(rsqrtf(((tot[0] / 0x1p+9f/*5.120000e+02*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)), rsqrtf(((tot[0] / 0x1p+9f/*5.120000e+02*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)));
      *(float2*)(&(__5.x)) = tl::mul2(*(float2*)(&(v__2.x)), *(float2*)(&(v__3.x)));
    (reinterpret_cast<__nv_bfloat162*>(&__4))[0] = __float22bfloat162_rn(((float2*)(&__5))[0]);
    uint1 v__4 = *(uint1*)(G_local_cast_1 + 0);
    *(uint1*)(&(__3.x)) = tl::to_uint1(tl::mul2(tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(__4.x))), tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(v__4.x)))));
  *(uint1*)(O_local_cast + 0) = __3;
  *(uint1*)(O + ((((int)blockIdx.x) * 512) + (((int)threadIdx.x) * 2))) = *(uint1*)(O_local_cast + 0);
}


extern "C" __global__ void k3_rms_norm_rbs_b8_h512_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ X);
extern "C" __global__ void __launch_bounds__(256, 1) k3_rms_norm_rbs_b8_h512_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ X) {
  float xs[2];
  float sq[2];
  float tot[1];
  extern __shared__ __align__(1024) float workspace[];
  bfloat16_t G_local_cast_1[2];
  bfloat16_t O_local_cast[2];
  float2 __1;
  uint1 v_ = *(uint1*)(X + ((((int)blockIdx.x) * 512) + (((int)threadIdx.x) * 2)));
  ((float2*)(&__1))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v_))[0]);
  *(float2*)(xs + 0) = __1;
  float2 __2;
    float2 v__1 = *(float2*)(xs + 0);
    *(float2*)(&(__2.x)) = tl::mul2(*(float2*)(&(v__1.x)), *(float2*)(&(v__1.x)));
  *(float2*)(sq + 0) = __2;
  tot[0] = 0x0p+0f/*0.000000e+00*/;
  #pragma unroll
  for (int rv = 0; rv < 2; ++rv) {
    tot[0] = (tot[0] + sq[rv]);
  }
  tot[0] = tl::AllReduce<tl::SumOp, 256, 1, 0, tl::NamedBarrier<256>>::run(tot[0], (&(workspace[0])));
  *(uint1*)(G_local_cast_1 + 0) = *(uint1*)(G + (((int)threadIdx.x) * 2));
  uint1 __3;
    uint1 __4;
    float2 __5;
      float2 v__2 = *(float2*)(xs + 0);
      float2 v__3 = make_float2(rsqrtf(((tot[0] / 0x1p+9f/*5.120000e+02*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)), rsqrtf(((tot[0] / 0x1p+9f/*5.120000e+02*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)));
      *(float2*)(&(__5.x)) = tl::mul2(*(float2*)(&(v__2.x)), *(float2*)(&(v__3.x)));
    (reinterpret_cast<__nv_bfloat162*>(&__4))[0] = __float22bfloat162_rn(((float2*)(&__5))[0]);
    uint1 v__4 = *(uint1*)(G_local_cast_1 + 0);
    *(uint1*)(&(__3.x)) = tl::to_uint1(tl::mul2(tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(__4.x))), tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(v__4.x)))));
  *(uint1*)(O_local_cast + 0) = __3;
  *(uint1*)(O + ((((int)blockIdx.x) * 512) + (((int)threadIdx.x) * 2))) = *(uint1*)(O_local_cast + 0);
}


extern "C" __global__ void k3_rms_norm_rbs_b16_h512_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ X);
extern "C" __global__ void __launch_bounds__(256, 1) k3_rms_norm_rbs_b16_h512_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ X) {
  float xs[2];
  float sq[2];
  float tot[1];
  extern __shared__ __align__(1024) float workspace[];
  bfloat16_t G_local_cast_1[2];
  bfloat16_t O_local_cast[2];
  float2 __1;
  uint1 v_ = *(uint1*)(X + ((((int)blockIdx.x) * 512) + (((int)threadIdx.x) * 2)));
  ((float2*)(&__1))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v_))[0]);
  *(float2*)(xs + 0) = __1;
  float2 __2;
    float2 v__1 = *(float2*)(xs + 0);
    *(float2*)(&(__2.x)) = tl::mul2(*(float2*)(&(v__1.x)), *(float2*)(&(v__1.x)));
  *(float2*)(sq + 0) = __2;
  tot[0] = 0x0p+0f/*0.000000e+00*/;
  #pragma unroll
  for (int rv = 0; rv < 2; ++rv) {
    tot[0] = (tot[0] + sq[rv]);
  }
  tot[0] = tl::AllReduce<tl::SumOp, 256, 1, 0, tl::NamedBarrier<256>>::run(tot[0], (&(workspace[0])));
  *(uint1*)(G_local_cast_1 + 0) = *(uint1*)(G + (((int)threadIdx.x) * 2));
  uint1 __3;
    uint1 __4;
    float2 __5;
      float2 v__2 = *(float2*)(xs + 0);
      float2 v__3 = make_float2(rsqrtf(((tot[0] / 0x1p+9f/*5.120000e+02*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)), rsqrtf(((tot[0] / 0x1p+9f/*5.120000e+02*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)));
      *(float2*)(&(__5.x)) = tl::mul2(*(float2*)(&(v__2.x)), *(float2*)(&(v__3.x)));
    (reinterpret_cast<__nv_bfloat162*>(&__4))[0] = __float22bfloat162_rn(((float2*)(&__5))[0]);
    uint1 v__4 = *(uint1*)(G_local_cast_1 + 0);
    *(uint1*)(&(__3.x)) = tl::to_uint1(tl::mul2(tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(__4.x))), tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(v__4.x)))));
  *(uint1*)(O_local_cast + 0) = __3;
  *(uint1*)(O + ((((int)blockIdx.x) * 512) + (((int)threadIdx.x) * 2))) = *(uint1*)(O_local_cast + 0);
}


extern "C" __global__ void k3_rms_norm_rbs_b32_h512_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ X);
extern "C" __global__ void __launch_bounds__(256, 1) k3_rms_norm_rbs_b32_h512_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ X) {
  float xs[2];
  float sq[2];
  float tot[1];
  extern __shared__ __align__(1024) float workspace[];
  bfloat16_t G_local_cast_1[2];
  bfloat16_t O_local_cast[2];
  float2 __1;
  uint1 v_ = *(uint1*)(X + ((((int)blockIdx.x) * 512) + (((int)threadIdx.x) * 2)));
  ((float2*)(&__1))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v_))[0]);
  *(float2*)(xs + 0) = __1;
  float2 __2;
    float2 v__1 = *(float2*)(xs + 0);
    *(float2*)(&(__2.x)) = tl::mul2(*(float2*)(&(v__1.x)), *(float2*)(&(v__1.x)));
  *(float2*)(sq + 0) = __2;
  tot[0] = 0x0p+0f/*0.000000e+00*/;
  #pragma unroll
  for (int rv = 0; rv < 2; ++rv) {
    tot[0] = (tot[0] + sq[rv]);
  }
  tot[0] = tl::AllReduce<tl::SumOp, 256, 1, 0, tl::NamedBarrier<256>>::run(tot[0], (&(workspace[0])));
  *(uint1*)(G_local_cast_1 + 0) = *(uint1*)(G + (((int)threadIdx.x) * 2));
  uint1 __3;
    uint1 __4;
    float2 __5;
      float2 v__2 = *(float2*)(xs + 0);
      float2 v__3 = make_float2(rsqrtf(((tot[0] / 0x1p+9f/*5.120000e+02*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)), rsqrtf(((tot[0] / 0x1p+9f/*5.120000e+02*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)));
      *(float2*)(&(__5.x)) = tl::mul2(*(float2*)(&(v__2.x)), *(float2*)(&(v__3.x)));
    (reinterpret_cast<__nv_bfloat162*>(&__4))[0] = __float22bfloat162_rn(((float2*)(&__5))[0]);
    uint1 v__4 = *(uint1*)(G_local_cast_1 + 0);
    *(uint1*)(&(__3.x)) = tl::to_uint1(tl::mul2(tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(__4.x))), tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(v__4.x)))));
  *(uint1*)(O_local_cast + 0) = __3;
  *(uint1*)(O + ((((int)blockIdx.x) * 512) + (((int)threadIdx.x) * 2))) = *(uint1*)(O_local_cast + 0);
}


extern "C" __global__ void k3_rms_norm_rbs_b48_h512_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ X);
extern "C" __global__ void __launch_bounds__(256, 1) k3_rms_norm_rbs_b48_h512_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ X) {
  float xs[2];
  float sq[2];
  float tot[1];
  extern __shared__ __align__(1024) float workspace[];
  bfloat16_t G_local_cast_1[2];
  bfloat16_t O_local_cast[2];
  float2 __1;
  uint1 v_ = *(uint1*)(X + ((((int)blockIdx.x) * 512) + (((int)threadIdx.x) * 2)));
  ((float2*)(&__1))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v_))[0]);
  *(float2*)(xs + 0) = __1;
  float2 __2;
    float2 v__1 = *(float2*)(xs + 0);
    *(float2*)(&(__2.x)) = tl::mul2(*(float2*)(&(v__1.x)), *(float2*)(&(v__1.x)));
  *(float2*)(sq + 0) = __2;
  tot[0] = 0x0p+0f/*0.000000e+00*/;
  #pragma unroll
  for (int rv = 0; rv < 2; ++rv) {
    tot[0] = (tot[0] + sq[rv]);
  }
  tot[0] = tl::AllReduce<tl::SumOp, 256, 1, 0, tl::NamedBarrier<256>>::run(tot[0], (&(workspace[0])));
  *(uint1*)(G_local_cast_1 + 0) = *(uint1*)(G + (((int)threadIdx.x) * 2));
  uint1 __3;
    uint1 __4;
    float2 __5;
      float2 v__2 = *(float2*)(xs + 0);
      float2 v__3 = make_float2(rsqrtf(((tot[0] / 0x1p+9f/*5.120000e+02*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)), rsqrtf(((tot[0] / 0x1p+9f/*5.120000e+02*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)));
      *(float2*)(&(__5.x)) = tl::mul2(*(float2*)(&(v__2.x)), *(float2*)(&(v__3.x)));
    (reinterpret_cast<__nv_bfloat162*>(&__4))[0] = __float22bfloat162_rn(((float2*)(&__5))[0]);
    uint1 v__4 = *(uint1*)(G_local_cast_1 + 0);
    *(uint1*)(&(__3.x)) = tl::to_uint1(tl::mul2(tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(__4.x))), tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(v__4.x)))));
  *(uint1*)(O_local_cast + 0) = __3;
  *(uint1*)(O + ((((int)blockIdx.x) * 512) + (((int)threadIdx.x) * 2))) = *(uint1*)(O_local_cast + 0);
}


extern "C" __global__ void k3_rms_norm_rbs_b64_h512_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ X);
extern "C" __global__ void __launch_bounds__(256, 1) k3_rms_norm_rbs_b64_h512_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ X) {
  float xs[2];
  float sq[2];
  float tot[1];
  extern __shared__ __align__(1024) float workspace[];
  bfloat16_t G_local_cast_1[2];
  bfloat16_t O_local_cast[2];
  float2 __1;
  uint1 v_ = *(uint1*)(X + ((((int)blockIdx.x) * 512) + (((int)threadIdx.x) * 2)));
  ((float2*)(&__1))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v_))[0]);
  *(float2*)(xs + 0) = __1;
  float2 __2;
    float2 v__1 = *(float2*)(xs + 0);
    *(float2*)(&(__2.x)) = tl::mul2(*(float2*)(&(v__1.x)), *(float2*)(&(v__1.x)));
  *(float2*)(sq + 0) = __2;
  tot[0] = 0x0p+0f/*0.000000e+00*/;
  #pragma unroll
  for (int rv = 0; rv < 2; ++rv) {
    tot[0] = (tot[0] + sq[rv]);
  }
  tot[0] = tl::AllReduce<tl::SumOp, 256, 1, 0, tl::NamedBarrier<256>>::run(tot[0], (&(workspace[0])));
  *(uint1*)(G_local_cast_1 + 0) = *(uint1*)(G + (((int)threadIdx.x) * 2));
  uint1 __3;
    uint1 __4;
    float2 __5;
      float2 v__2 = *(float2*)(xs + 0);
      float2 v__3 = make_float2(rsqrtf(((tot[0] / 0x1p+9f/*5.120000e+02*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)), rsqrtf(((tot[0] / 0x1p+9f/*5.120000e+02*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)));
      *(float2*)(&(__5.x)) = tl::mul2(*(float2*)(&(v__2.x)), *(float2*)(&(v__3.x)));
    (reinterpret_cast<__nv_bfloat162*>(&__4))[0] = __float22bfloat162_rn(((float2*)(&__5))[0]);
    uint1 v__4 = *(uint1*)(G_local_cast_1 + 0);
    *(uint1*)(&(__3.x)) = tl::to_uint1(tl::mul2(tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(__4.x))), tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(v__4.x)))));
  *(uint1*)(O_local_cast + 0) = __3;
  *(uint1*)(O + ((((int)blockIdx.x) * 512) + (((int)threadIdx.x) * 2))) = *(uint1*)(O_local_cast + 0);
}


extern "C" __global__ void k3_rms_norm_rbs_b96_h512_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ X);
extern "C" __global__ void __launch_bounds__(256, 1) k3_rms_norm_rbs_b96_h512_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ X) {
  float xs[2];
  float sq[2];
  float tot[1];
  extern __shared__ __align__(1024) float workspace[];
  bfloat16_t G_local_cast_1[2];
  bfloat16_t O_local_cast[2];
  float2 __1;
  uint1 v_ = *(uint1*)(X + ((((int)blockIdx.x) * 512) + (((int)threadIdx.x) * 2)));
  ((float2*)(&__1))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v_))[0]);
  *(float2*)(xs + 0) = __1;
  float2 __2;
    float2 v__1 = *(float2*)(xs + 0);
    *(float2*)(&(__2.x)) = tl::mul2(*(float2*)(&(v__1.x)), *(float2*)(&(v__1.x)));
  *(float2*)(sq + 0) = __2;
  tot[0] = 0x0p+0f/*0.000000e+00*/;
  #pragma unroll
  for (int rv = 0; rv < 2; ++rv) {
    tot[0] = (tot[0] + sq[rv]);
  }
  tot[0] = tl::AllReduce<tl::SumOp, 256, 1, 0, tl::NamedBarrier<256>>::run(tot[0], (&(workspace[0])));
  *(uint1*)(G_local_cast_1 + 0) = *(uint1*)(G + (((int)threadIdx.x) * 2));
  uint1 __3;
    uint1 __4;
    float2 __5;
      float2 v__2 = *(float2*)(xs + 0);
      float2 v__3 = make_float2(rsqrtf(((tot[0] / 0x1p+9f/*5.120000e+02*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)), rsqrtf(((tot[0] / 0x1p+9f/*5.120000e+02*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)));
      *(float2*)(&(__5.x)) = tl::mul2(*(float2*)(&(v__2.x)), *(float2*)(&(v__3.x)));
    (reinterpret_cast<__nv_bfloat162*>(&__4))[0] = __float22bfloat162_rn(((float2*)(&__5))[0]);
    uint1 v__4 = *(uint1*)(G_local_cast_1 + 0);
    *(uint1*)(&(__3.x)) = tl::to_uint1(tl::mul2(tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(__4.x))), tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(v__4.x)))));
  *(uint1*)(O_local_cast + 0) = __3;
  *(uint1*)(O + ((((int)blockIdx.x) * 512) + (((int)threadIdx.x) * 2))) = *(uint1*)(O_local_cast + 0);
}


extern "C" __global__ void k3_rms_norm_rbs_b128_h512_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ X);
extern "C" __global__ void __launch_bounds__(256, 1) k3_rms_norm_rbs_b128_h512_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ X) {
  float xs[2];
  float sq[2];
  float tot[1];
  extern __shared__ __align__(1024) float workspace[];
  bfloat16_t G_local_cast_1[2];
  bfloat16_t O_local_cast[2];
  float2 __1;
  uint1 v_ = *(uint1*)(X + ((((int)blockIdx.x) * 512) + (((int)threadIdx.x) * 2)));
  ((float2*)(&__1))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v_))[0]);
  *(float2*)(xs + 0) = __1;
  float2 __2;
    float2 v__1 = *(float2*)(xs + 0);
    *(float2*)(&(__2.x)) = tl::mul2(*(float2*)(&(v__1.x)), *(float2*)(&(v__1.x)));
  *(float2*)(sq + 0) = __2;
  tot[0] = 0x0p+0f/*0.000000e+00*/;
  #pragma unroll
  for (int rv = 0; rv < 2; ++rv) {
    tot[0] = (tot[0] + sq[rv]);
  }
  tot[0] = tl::AllReduce<tl::SumOp, 256, 1, 0, tl::NamedBarrier<256>>::run(tot[0], (&(workspace[0])));
  *(uint1*)(G_local_cast_1 + 0) = *(uint1*)(G + (((int)threadIdx.x) * 2));
  uint1 __3;
    uint1 __4;
    float2 __5;
      float2 v__2 = *(float2*)(xs + 0);
      float2 v__3 = make_float2(rsqrtf(((tot[0] / 0x1p+9f/*5.120000e+02*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)), rsqrtf(((tot[0] / 0x1p+9f/*5.120000e+02*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)));
      *(float2*)(&(__5.x)) = tl::mul2(*(float2*)(&(v__2.x)), *(float2*)(&(v__3.x)));
    (reinterpret_cast<__nv_bfloat162*>(&__4))[0] = __float22bfloat162_rn(((float2*)(&__5))[0]);
    uint1 v__4 = *(uint1*)(G_local_cast_1 + 0);
    *(uint1*)(&(__3.x)) = tl::to_uint1(tl::mul2(tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(__4.x))), tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(v__4.x)))));
  *(uint1*)(O_local_cast + 0) = __3;
  *(uint1*)(O + ((((int)blockIdx.x) * 512) + (((int)threadIdx.x) * 2))) = *(uint1*)(O_local_cast + 0);
}


extern "C" __global__ void k3_rms_norm_rbs_b1_h3584_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ X);
extern "C" __global__ void __launch_bounds__(256, 1) k3_rms_norm_rbs_b1_h3584_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ X) {
  float xs[14];
  float sq[14];
  float tot[1];
  extern __shared__ __align__(1024) float workspace[];
  bfloat16_t G_local_cast_1[2];
  bfloat16_t O_local_cast[2];
  #pragma unroll
  for (int i = 0; i < 7; ++i) {
    float2 __1;
    uint1 v_ = *(uint1*)(X + ((i * 512) + (((int)threadIdx.x) * 2)));
    ((float2*)(&__1))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v_))[0]);
    *(float2*)(xs + (i * 2)) = __1;
    float2 __2;
      float2 v__1 = *(float2*)(xs + (i * 2));
      *(float2*)(&(__2.x)) = tl::mul2(*(float2*)(&(v__1.x)), *(float2*)(&(v__1.x)));
    *(float2*)(sq + (i * 2)) = __2;
  }
  tot[0] = 0x0p+0f/*0.000000e+00*/;
  #pragma unroll
  for (int rv = 0; rv < 14; ++rv) {
    tot[0] = (tot[0] + sq[(((rv % 7) * 2) + (rv / 7))]);
  }
  tot[0] = tl::AllReduce<tl::SumOp, 256, 1, 0, tl::NamedBarrier<256>>::run(tot[0], (&(workspace[0])));
  #pragma unroll
  for (int i_1 = 0; i_1 < 7; ++i_1) {
    *(uint1*)(G_local_cast_1 + 0) = *(uint1*)(G + ((i_1 * 512) + (((int)threadIdx.x) * 2)));
    uint1 __3;
      uint1 __4;
      float2 __5;
        float2 v__2 = *(float2*)(xs + (i_1 * 2));
        float2 v__3 = make_float2(rsqrtf(((tot[0] / 0x1.cp+11f/*3.584000e+03*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)), rsqrtf(((tot[0] / 0x1.cp+11f/*3.584000e+03*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)));
        *(float2*)(&(__5.x)) = tl::mul2(*(float2*)(&(v__2.x)), *(float2*)(&(v__3.x)));
      (reinterpret_cast<__nv_bfloat162*>(&__4))[0] = __float22bfloat162_rn(((float2*)(&__5))[0]);
      uint1 v__4 = *(uint1*)(G_local_cast_1 + 0);
      *(uint1*)(&(__3.x)) = tl::to_uint1(tl::mul2(tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(__4.x))), tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(v__4.x)))));
    *(uint1*)(O_local_cast + 0) = __3;
    *(uint1*)(O + ((i_1 * 512) + (((int)threadIdx.x) * 2))) = *(uint1*)(O_local_cast + 0);
  }
}


extern "C" __global__ void k3_rms_norm_rbs_b2_h3584_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ X);
extern "C" __global__ void __launch_bounds__(256, 1) k3_rms_norm_rbs_b2_h3584_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ X) {
  float xs[14];
  float sq[14];
  float tot[1];
  extern __shared__ __align__(1024) float workspace[];
  bfloat16_t G_local_cast_1[2];
  bfloat16_t O_local_cast[2];
  #pragma unroll
  for (int i = 0; i < 7; ++i) {
    float2 __1;
    uint1 v_ = *(uint1*)(X + (((((int)blockIdx.x) * 3584) + (i * 512)) + (((int)threadIdx.x) * 2)));
    ((float2*)(&__1))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v_))[0]);
    *(float2*)(xs + (i * 2)) = __1;
    float2 __2;
      float2 v__1 = *(float2*)(xs + (i * 2));
      *(float2*)(&(__2.x)) = tl::mul2(*(float2*)(&(v__1.x)), *(float2*)(&(v__1.x)));
    *(float2*)(sq + (i * 2)) = __2;
  }
  tot[0] = 0x0p+0f/*0.000000e+00*/;
  #pragma unroll
  for (int rv = 0; rv < 14; ++rv) {
    tot[0] = (tot[0] + sq[(((rv % 7) * 2) + (rv / 7))]);
  }
  tot[0] = tl::AllReduce<tl::SumOp, 256, 1, 0, tl::NamedBarrier<256>>::run(tot[0], (&(workspace[0])));
  #pragma unroll
  for (int i_1 = 0; i_1 < 7; ++i_1) {
    *(uint1*)(G_local_cast_1 + 0) = *(uint1*)(G + ((i_1 * 512) + (((int)threadIdx.x) * 2)));
    uint1 __3;
      uint1 __4;
      float2 __5;
        float2 v__2 = *(float2*)(xs + (i_1 * 2));
        float2 v__3 = make_float2(rsqrtf(((tot[0] / 0x1.cp+11f/*3.584000e+03*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)), rsqrtf(((tot[0] / 0x1.cp+11f/*3.584000e+03*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)));
        *(float2*)(&(__5.x)) = tl::mul2(*(float2*)(&(v__2.x)), *(float2*)(&(v__3.x)));
      (reinterpret_cast<__nv_bfloat162*>(&__4))[0] = __float22bfloat162_rn(((float2*)(&__5))[0]);
      uint1 v__4 = *(uint1*)(G_local_cast_1 + 0);
      *(uint1*)(&(__3.x)) = tl::to_uint1(tl::mul2(tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(__4.x))), tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(v__4.x)))));
    *(uint1*)(O_local_cast + 0) = __3;
    *(uint1*)(O + (((((int)blockIdx.x) * 3584) + (i_1 * 512)) + (((int)threadIdx.x) * 2))) = *(uint1*)(O_local_cast + 0);
  }
}


extern "C" __global__ void k3_rms_norm_rbs_b4_h3584_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ X);
extern "C" __global__ void __launch_bounds__(256, 1) k3_rms_norm_rbs_b4_h3584_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ X) {
  float xs[14];
  float sq[14];
  float tot[1];
  extern __shared__ __align__(1024) float workspace[];
  bfloat16_t G_local_cast_1[2];
  bfloat16_t O_local_cast[2];
  #pragma unroll
  for (int i = 0; i < 7; ++i) {
    float2 __1;
    uint1 v_ = *(uint1*)(X + (((((int)blockIdx.x) * 3584) + (i * 512)) + (((int)threadIdx.x) * 2)));
    ((float2*)(&__1))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v_))[0]);
    *(float2*)(xs + (i * 2)) = __1;
    float2 __2;
      float2 v__1 = *(float2*)(xs + (i * 2));
      *(float2*)(&(__2.x)) = tl::mul2(*(float2*)(&(v__1.x)), *(float2*)(&(v__1.x)));
    *(float2*)(sq + (i * 2)) = __2;
  }
  tot[0] = 0x0p+0f/*0.000000e+00*/;
  #pragma unroll
  for (int rv = 0; rv < 14; ++rv) {
    tot[0] = (tot[0] + sq[(((rv % 7) * 2) + (rv / 7))]);
  }
  tot[0] = tl::AllReduce<tl::SumOp, 256, 1, 0, tl::NamedBarrier<256>>::run(tot[0], (&(workspace[0])));
  #pragma unroll
  for (int i_1 = 0; i_1 < 7; ++i_1) {
    *(uint1*)(G_local_cast_1 + 0) = *(uint1*)(G + ((i_1 * 512) + (((int)threadIdx.x) * 2)));
    uint1 __3;
      uint1 __4;
      float2 __5;
        float2 v__2 = *(float2*)(xs + (i_1 * 2));
        float2 v__3 = make_float2(rsqrtf(((tot[0] / 0x1.cp+11f/*3.584000e+03*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)), rsqrtf(((tot[0] / 0x1.cp+11f/*3.584000e+03*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)));
        *(float2*)(&(__5.x)) = tl::mul2(*(float2*)(&(v__2.x)), *(float2*)(&(v__3.x)));
      (reinterpret_cast<__nv_bfloat162*>(&__4))[0] = __float22bfloat162_rn(((float2*)(&__5))[0]);
      uint1 v__4 = *(uint1*)(G_local_cast_1 + 0);
      *(uint1*)(&(__3.x)) = tl::to_uint1(tl::mul2(tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(__4.x))), tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(v__4.x)))));
    *(uint1*)(O_local_cast + 0) = __3;
    *(uint1*)(O + (((((int)blockIdx.x) * 3584) + (i_1 * 512)) + (((int)threadIdx.x) * 2))) = *(uint1*)(O_local_cast + 0);
  }
}


extern "C" __global__ void k3_rms_norm_rbs_b8_h3584_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ X);
extern "C" __global__ void __launch_bounds__(256, 1) k3_rms_norm_rbs_b8_h3584_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ X) {
  float xs[14];
  float sq[14];
  float tot[1];
  extern __shared__ __align__(1024) float workspace[];
  bfloat16_t G_local_cast_1[2];
  bfloat16_t O_local_cast[2];
  #pragma unroll
  for (int i = 0; i < 7; ++i) {
    float2 __1;
    uint1 v_ = *(uint1*)(X + (((((int)blockIdx.x) * 3584) + (i * 512)) + (((int)threadIdx.x) * 2)));
    ((float2*)(&__1))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v_))[0]);
    *(float2*)(xs + (i * 2)) = __1;
    float2 __2;
      float2 v__1 = *(float2*)(xs + (i * 2));
      *(float2*)(&(__2.x)) = tl::mul2(*(float2*)(&(v__1.x)), *(float2*)(&(v__1.x)));
    *(float2*)(sq + (i * 2)) = __2;
  }
  tot[0] = 0x0p+0f/*0.000000e+00*/;
  #pragma unroll
  for (int rv = 0; rv < 14; ++rv) {
    tot[0] = (tot[0] + sq[(((rv % 7) * 2) + (rv / 7))]);
  }
  tot[0] = tl::AllReduce<tl::SumOp, 256, 1, 0, tl::NamedBarrier<256>>::run(tot[0], (&(workspace[0])));
  #pragma unroll
  for (int i_1 = 0; i_1 < 7; ++i_1) {
    *(uint1*)(G_local_cast_1 + 0) = *(uint1*)(G + ((i_1 * 512) + (((int)threadIdx.x) * 2)));
    uint1 __3;
      uint1 __4;
      float2 __5;
        float2 v__2 = *(float2*)(xs + (i_1 * 2));
        float2 v__3 = make_float2(rsqrtf(((tot[0] / 0x1.cp+11f/*3.584000e+03*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)), rsqrtf(((tot[0] / 0x1.cp+11f/*3.584000e+03*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)));
        *(float2*)(&(__5.x)) = tl::mul2(*(float2*)(&(v__2.x)), *(float2*)(&(v__3.x)));
      (reinterpret_cast<__nv_bfloat162*>(&__4))[0] = __float22bfloat162_rn(((float2*)(&__5))[0]);
      uint1 v__4 = *(uint1*)(G_local_cast_1 + 0);
      *(uint1*)(&(__3.x)) = tl::to_uint1(tl::mul2(tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(__4.x))), tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(v__4.x)))));
    *(uint1*)(O_local_cast + 0) = __3;
    *(uint1*)(O + (((((int)blockIdx.x) * 3584) + (i_1 * 512)) + (((int)threadIdx.x) * 2))) = *(uint1*)(O_local_cast + 0);
  }
}


extern "C" __global__ void k3_rms_norm_rbs_b16_h3584_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ X);
extern "C" __global__ void __launch_bounds__(256, 1) k3_rms_norm_rbs_b16_h3584_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ X) {
  float xs[14];
  float sq[14];
  float tot[1];
  extern __shared__ __align__(1024) float workspace[];
  bfloat16_t G_local_cast_1[2];
  bfloat16_t O_local_cast[2];
  #pragma unroll
  for (int i = 0; i < 7; ++i) {
    float2 __1;
    uint1 v_ = *(uint1*)(X + (((((int)blockIdx.x) * 3584) + (i * 512)) + (((int)threadIdx.x) * 2)));
    ((float2*)(&__1))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v_))[0]);
    *(float2*)(xs + (i * 2)) = __1;
    float2 __2;
      float2 v__1 = *(float2*)(xs + (i * 2));
      *(float2*)(&(__2.x)) = tl::mul2(*(float2*)(&(v__1.x)), *(float2*)(&(v__1.x)));
    *(float2*)(sq + (i * 2)) = __2;
  }
  tot[0] = 0x0p+0f/*0.000000e+00*/;
  #pragma unroll
  for (int rv = 0; rv < 14; ++rv) {
    tot[0] = (tot[0] + sq[(((rv % 7) * 2) + (rv / 7))]);
  }
  tot[0] = tl::AllReduce<tl::SumOp, 256, 1, 0, tl::NamedBarrier<256>>::run(tot[0], (&(workspace[0])));
  #pragma unroll
  for (int i_1 = 0; i_1 < 7; ++i_1) {
    *(uint1*)(G_local_cast_1 + 0) = *(uint1*)(G + ((i_1 * 512) + (((int)threadIdx.x) * 2)));
    uint1 __3;
      uint1 __4;
      float2 __5;
        float2 v__2 = *(float2*)(xs + (i_1 * 2));
        float2 v__3 = make_float2(rsqrtf(((tot[0] / 0x1.cp+11f/*3.584000e+03*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)), rsqrtf(((tot[0] / 0x1.cp+11f/*3.584000e+03*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)));
        *(float2*)(&(__5.x)) = tl::mul2(*(float2*)(&(v__2.x)), *(float2*)(&(v__3.x)));
      (reinterpret_cast<__nv_bfloat162*>(&__4))[0] = __float22bfloat162_rn(((float2*)(&__5))[0]);
      uint1 v__4 = *(uint1*)(G_local_cast_1 + 0);
      *(uint1*)(&(__3.x)) = tl::to_uint1(tl::mul2(tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(__4.x))), tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(v__4.x)))));
    *(uint1*)(O_local_cast + 0) = __3;
    *(uint1*)(O + (((((int)blockIdx.x) * 3584) + (i_1 * 512)) + (((int)threadIdx.x) * 2))) = *(uint1*)(O_local_cast + 0);
  }
}


extern "C" __global__ void k3_rms_norm_rbs_b32_h3584_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ X);
extern "C" __global__ void __launch_bounds__(256, 1) k3_rms_norm_rbs_b32_h3584_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ X) {
  float xs[14];
  float sq[14];
  float tot[1];
  extern __shared__ __align__(1024) float workspace[];
  bfloat16_t G_local_cast_1[2];
  bfloat16_t O_local_cast[2];
  #pragma unroll
  for (int i = 0; i < 7; ++i) {
    float2 __1;
    uint1 v_ = *(uint1*)(X + (((((int)blockIdx.x) * 3584) + (i * 512)) + (((int)threadIdx.x) * 2)));
    ((float2*)(&__1))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v_))[0]);
    *(float2*)(xs + (i * 2)) = __1;
    float2 __2;
      float2 v__1 = *(float2*)(xs + (i * 2));
      *(float2*)(&(__2.x)) = tl::mul2(*(float2*)(&(v__1.x)), *(float2*)(&(v__1.x)));
    *(float2*)(sq + (i * 2)) = __2;
  }
  tot[0] = 0x0p+0f/*0.000000e+00*/;
  #pragma unroll
  for (int rv = 0; rv < 14; ++rv) {
    tot[0] = (tot[0] + sq[(((rv % 7) * 2) + (rv / 7))]);
  }
  tot[0] = tl::AllReduce<tl::SumOp, 256, 1, 0, tl::NamedBarrier<256>>::run(tot[0], (&(workspace[0])));
  #pragma unroll
  for (int i_1 = 0; i_1 < 7; ++i_1) {
    *(uint1*)(G_local_cast_1 + 0) = *(uint1*)(G + ((i_1 * 512) + (((int)threadIdx.x) * 2)));
    uint1 __3;
      uint1 __4;
      float2 __5;
        float2 v__2 = *(float2*)(xs + (i_1 * 2));
        float2 v__3 = make_float2(rsqrtf(((tot[0] / 0x1.cp+11f/*3.584000e+03*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)), rsqrtf(((tot[0] / 0x1.cp+11f/*3.584000e+03*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)));
        *(float2*)(&(__5.x)) = tl::mul2(*(float2*)(&(v__2.x)), *(float2*)(&(v__3.x)));
      (reinterpret_cast<__nv_bfloat162*>(&__4))[0] = __float22bfloat162_rn(((float2*)(&__5))[0]);
      uint1 v__4 = *(uint1*)(G_local_cast_1 + 0);
      *(uint1*)(&(__3.x)) = tl::to_uint1(tl::mul2(tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(__4.x))), tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(v__4.x)))));
    *(uint1*)(O_local_cast + 0) = __3;
    *(uint1*)(O + (((((int)blockIdx.x) * 3584) + (i_1 * 512)) + (((int)threadIdx.x) * 2))) = *(uint1*)(O_local_cast + 0);
  }
}


extern "C" __global__ void k3_rms_norm_rbs_b48_h3584_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ X);
extern "C" __global__ void __launch_bounds__(256, 1) k3_rms_norm_rbs_b48_h3584_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ X) {
  float xs[14];
  float sq[14];
  float tot[1];
  extern __shared__ __align__(1024) float workspace[];
  bfloat16_t G_local_cast_1[2];
  bfloat16_t O_local_cast[2];
  #pragma unroll
  for (int i = 0; i < 7; ++i) {
    float2 __1;
    uint1 v_ = *(uint1*)(X + (((((int)blockIdx.x) * 3584) + (i * 512)) + (((int)threadIdx.x) * 2)));
    ((float2*)(&__1))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v_))[0]);
    *(float2*)(xs + (i * 2)) = __1;
    float2 __2;
      float2 v__1 = *(float2*)(xs + (i * 2));
      *(float2*)(&(__2.x)) = tl::mul2(*(float2*)(&(v__1.x)), *(float2*)(&(v__1.x)));
    *(float2*)(sq + (i * 2)) = __2;
  }
  tot[0] = 0x0p+0f/*0.000000e+00*/;
  #pragma unroll
  for (int rv = 0; rv < 14; ++rv) {
    tot[0] = (tot[0] + sq[(((rv % 7) * 2) + (rv / 7))]);
  }
  tot[0] = tl::AllReduce<tl::SumOp, 256, 1, 0, tl::NamedBarrier<256>>::run(tot[0], (&(workspace[0])));
  #pragma unroll
  for (int i_1 = 0; i_1 < 7; ++i_1) {
    *(uint1*)(G_local_cast_1 + 0) = *(uint1*)(G + ((i_1 * 512) + (((int)threadIdx.x) * 2)));
    uint1 __3;
      uint1 __4;
      float2 __5;
        float2 v__2 = *(float2*)(xs + (i_1 * 2));
        float2 v__3 = make_float2(rsqrtf(((tot[0] / 0x1.cp+11f/*3.584000e+03*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)), rsqrtf(((tot[0] / 0x1.cp+11f/*3.584000e+03*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)));
        *(float2*)(&(__5.x)) = tl::mul2(*(float2*)(&(v__2.x)), *(float2*)(&(v__3.x)));
      (reinterpret_cast<__nv_bfloat162*>(&__4))[0] = __float22bfloat162_rn(((float2*)(&__5))[0]);
      uint1 v__4 = *(uint1*)(G_local_cast_1 + 0);
      *(uint1*)(&(__3.x)) = tl::to_uint1(tl::mul2(tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(__4.x))), tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(v__4.x)))));
    *(uint1*)(O_local_cast + 0) = __3;
    *(uint1*)(O + (((((int)blockIdx.x) * 3584) + (i_1 * 512)) + (((int)threadIdx.x) * 2))) = *(uint1*)(O_local_cast + 0);
  }
}


extern "C" __global__ void k3_rms_norm_rbs_b64_h3584_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ X);
extern "C" __global__ void __launch_bounds__(256, 1) k3_rms_norm_rbs_b64_h3584_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ X) {
  float xs[14];
  float sq[14];
  float tot[1];
  extern __shared__ __align__(1024) float workspace[];
  bfloat16_t G_local_cast_1[2];
  bfloat16_t O_local_cast[2];
  #pragma unroll
  for (int i = 0; i < 7; ++i) {
    float2 __1;
    uint1 v_ = *(uint1*)(X + (((((int)blockIdx.x) * 3584) + (i * 512)) + (((int)threadIdx.x) * 2)));
    ((float2*)(&__1))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v_))[0]);
    *(float2*)(xs + (i * 2)) = __1;
    float2 __2;
      float2 v__1 = *(float2*)(xs + (i * 2));
      *(float2*)(&(__2.x)) = tl::mul2(*(float2*)(&(v__1.x)), *(float2*)(&(v__1.x)));
    *(float2*)(sq + (i * 2)) = __2;
  }
  tot[0] = 0x0p+0f/*0.000000e+00*/;
  #pragma unroll
  for (int rv = 0; rv < 14; ++rv) {
    tot[0] = (tot[0] + sq[(((rv % 7) * 2) + (rv / 7))]);
  }
  tot[0] = tl::AllReduce<tl::SumOp, 256, 1, 0, tl::NamedBarrier<256>>::run(tot[0], (&(workspace[0])));
  #pragma unroll
  for (int i_1 = 0; i_1 < 7; ++i_1) {
    *(uint1*)(G_local_cast_1 + 0) = *(uint1*)(G + ((i_1 * 512) + (((int)threadIdx.x) * 2)));
    uint1 __3;
      uint1 __4;
      float2 __5;
        float2 v__2 = *(float2*)(xs + (i_1 * 2));
        float2 v__3 = make_float2(rsqrtf(((tot[0] / 0x1.cp+11f/*3.584000e+03*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)), rsqrtf(((tot[0] / 0x1.cp+11f/*3.584000e+03*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)));
        *(float2*)(&(__5.x)) = tl::mul2(*(float2*)(&(v__2.x)), *(float2*)(&(v__3.x)));
      (reinterpret_cast<__nv_bfloat162*>(&__4))[0] = __float22bfloat162_rn(((float2*)(&__5))[0]);
      uint1 v__4 = *(uint1*)(G_local_cast_1 + 0);
      *(uint1*)(&(__3.x)) = tl::to_uint1(tl::mul2(tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(__4.x))), tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(v__4.x)))));
    *(uint1*)(O_local_cast + 0) = __3;
    *(uint1*)(O + (((((int)blockIdx.x) * 3584) + (i_1 * 512)) + (((int)threadIdx.x) * 2))) = *(uint1*)(O_local_cast + 0);
  }
}


extern "C" __global__ void k3_rms_norm_rbs_b96_h3584_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ X);
extern "C" __global__ void __launch_bounds__(256, 1) k3_rms_norm_rbs_b96_h3584_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ X) {
  float xs[14];
  float sq[14];
  float tot[1];
  extern __shared__ __align__(1024) float workspace[];
  bfloat16_t G_local_cast_1[2];
  bfloat16_t O_local_cast[2];
  #pragma unroll
  for (int i = 0; i < 7; ++i) {
    float2 __1;
    uint1 v_ = *(uint1*)(X + (((((int)blockIdx.x) * 3584) + (i * 512)) + (((int)threadIdx.x) * 2)));
    ((float2*)(&__1))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v_))[0]);
    *(float2*)(xs + (i * 2)) = __1;
    float2 __2;
      float2 v__1 = *(float2*)(xs + (i * 2));
      *(float2*)(&(__2.x)) = tl::mul2(*(float2*)(&(v__1.x)), *(float2*)(&(v__1.x)));
    *(float2*)(sq + (i * 2)) = __2;
  }
  tot[0] = 0x0p+0f/*0.000000e+00*/;
  #pragma unroll
  for (int rv = 0; rv < 14; ++rv) {
    tot[0] = (tot[0] + sq[(((rv % 7) * 2) + (rv / 7))]);
  }
  tot[0] = tl::AllReduce<tl::SumOp, 256, 1, 0, tl::NamedBarrier<256>>::run(tot[0], (&(workspace[0])));
  #pragma unroll
  for (int i_1 = 0; i_1 < 7; ++i_1) {
    *(uint1*)(G_local_cast_1 + 0) = *(uint1*)(G + ((i_1 * 512) + (((int)threadIdx.x) * 2)));
    uint1 __3;
      uint1 __4;
      float2 __5;
        float2 v__2 = *(float2*)(xs + (i_1 * 2));
        float2 v__3 = make_float2(rsqrtf(((tot[0] / 0x1.cp+11f/*3.584000e+03*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)), rsqrtf(((tot[0] / 0x1.cp+11f/*3.584000e+03*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)));
        *(float2*)(&(__5.x)) = tl::mul2(*(float2*)(&(v__2.x)), *(float2*)(&(v__3.x)));
      (reinterpret_cast<__nv_bfloat162*>(&__4))[0] = __float22bfloat162_rn(((float2*)(&__5))[0]);
      uint1 v__4 = *(uint1*)(G_local_cast_1 + 0);
      *(uint1*)(&(__3.x)) = tl::to_uint1(tl::mul2(tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(__4.x))), tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(v__4.x)))));
    *(uint1*)(O_local_cast + 0) = __3;
    *(uint1*)(O + (((((int)blockIdx.x) * 3584) + (i_1 * 512)) + (((int)threadIdx.x) * 2))) = *(uint1*)(O_local_cast + 0);
  }
}


extern "C" __global__ void k3_rms_norm_rbs_b128_h3584_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ X);
extern "C" __global__ void __launch_bounds__(256, 1) k3_rms_norm_rbs_b128_h3584_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ X) {
  float xs[14];
  float sq[14];
  float tot[1];
  extern __shared__ __align__(1024) float workspace[];
  bfloat16_t G_local_cast_1[2];
  bfloat16_t O_local_cast[2];
  #pragma unroll
  for (int i = 0; i < 7; ++i) {
    float2 __1;
    uint1 v_ = *(uint1*)(X + (((((int)blockIdx.x) * 3584) + (i * 512)) + (((int)threadIdx.x) * 2)));
    ((float2*)(&__1))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v_))[0]);
    *(float2*)(xs + (i * 2)) = __1;
    float2 __2;
      float2 v__1 = *(float2*)(xs + (i * 2));
      *(float2*)(&(__2.x)) = tl::mul2(*(float2*)(&(v__1.x)), *(float2*)(&(v__1.x)));
    *(float2*)(sq + (i * 2)) = __2;
  }
  tot[0] = 0x0p+0f/*0.000000e+00*/;
  #pragma unroll
  for (int rv = 0; rv < 14; ++rv) {
    tot[0] = (tot[0] + sq[(((rv % 7) * 2) + (rv / 7))]);
  }
  tot[0] = tl::AllReduce<tl::SumOp, 256, 1, 0, tl::NamedBarrier<256>>::run(tot[0], (&(workspace[0])));
  #pragma unroll
  for (int i_1 = 0; i_1 < 7; ++i_1) {
    *(uint1*)(G_local_cast_1 + 0) = *(uint1*)(G + ((i_1 * 512) + (((int)threadIdx.x) * 2)));
    uint1 __3;
      uint1 __4;
      float2 __5;
        float2 v__2 = *(float2*)(xs + (i_1 * 2));
        float2 v__3 = make_float2(rsqrtf(((tot[0] / 0x1.cp+11f/*3.584000e+03*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)), rsqrtf(((tot[0] / 0x1.cp+11f/*3.584000e+03*/) + 0x1.4f8b588e368f1p-17f/*1.000000e-05*/)));
        *(float2*)(&(__5.x)) = tl::mul2(*(float2*)(&(v__2.x)), *(float2*)(&(v__3.x)));
      (reinterpret_cast<__nv_bfloat162*>(&__4))[0] = __float22bfloat162_rn(((float2*)(&__5))[0]);
      uint1 v__4 = *(uint1*)(G_local_cast_1 + 0);
      *(uint1*)(&(__3.x)) = tl::to_uint1(tl::mul2(tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(__4.x))), tl::from_uint1<__nv_bfloat162>(*(uint1*)(&(v__4.x)))));
    *(uint1*)(O_local_cast + 0) = __3;
    *(uint1*)(O + (((((int)blockIdx.x) * 3584) + (i_1 * 512)) + (((int)threadIdx.x) * 2))) = *(uint1*)(O_local_cast + 0);
  }
}



// KimiRMSNorm, round-before-scale: the normalized value lands in bf16
// first and only then multiplies gamma. One row per block; gamma is a
// weight shared by every row and eps is compiled in.
extern "C" int k3_rms_norm_rbs_batched(
    const void* X,
    const void* G,
    void* O,
    int b,
    int h,
    cudaStream_t stream) {
  if (b == 1 && h == 7168) {
    k3_rms_norm_rbs_b1_h7168_kernel<<<dim3(1, 1, 1), 256, 1024, stream>>>(
        reinterpret_cast<const bfloat16_t*>(G),
        reinterpret_cast<bfloat16_t*>(O),
        reinterpret_cast<const bfloat16_t*>(X));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 2 && h == 7168) {
    k3_rms_norm_rbs_b2_h7168_kernel<<<dim3(2, 1, 1), 256, 1024, stream>>>(
        reinterpret_cast<const bfloat16_t*>(G),
        reinterpret_cast<bfloat16_t*>(O),
        reinterpret_cast<const bfloat16_t*>(X));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 4 && h == 7168) {
    k3_rms_norm_rbs_b4_h7168_kernel<<<dim3(4, 1, 1), 256, 1024, stream>>>(
        reinterpret_cast<const bfloat16_t*>(G),
        reinterpret_cast<bfloat16_t*>(O),
        reinterpret_cast<const bfloat16_t*>(X));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 8 && h == 7168) {
    k3_rms_norm_rbs_b8_h7168_kernel<<<dim3(8, 1, 1), 256, 1024, stream>>>(
        reinterpret_cast<const bfloat16_t*>(G),
        reinterpret_cast<bfloat16_t*>(O),
        reinterpret_cast<const bfloat16_t*>(X));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 16 && h == 7168) {
    k3_rms_norm_rbs_b16_h7168_kernel<<<dim3(16, 1, 1), 256, 1024, stream>>>(
        reinterpret_cast<const bfloat16_t*>(G),
        reinterpret_cast<bfloat16_t*>(O),
        reinterpret_cast<const bfloat16_t*>(X));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 32 && h == 7168) {
    k3_rms_norm_rbs_b32_h7168_kernel<<<dim3(32, 1, 1), 256, 1024, stream>>>(
        reinterpret_cast<const bfloat16_t*>(G),
        reinterpret_cast<bfloat16_t*>(O),
        reinterpret_cast<const bfloat16_t*>(X));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 48 && h == 7168) {
    k3_rms_norm_rbs_b48_h7168_kernel<<<dim3(48, 1, 1), 256, 1024, stream>>>(
        reinterpret_cast<const bfloat16_t*>(G),
        reinterpret_cast<bfloat16_t*>(O),
        reinterpret_cast<const bfloat16_t*>(X));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 64 && h == 7168) {
    k3_rms_norm_rbs_b64_h7168_kernel<<<dim3(64, 1, 1), 256, 1024, stream>>>(
        reinterpret_cast<const bfloat16_t*>(G),
        reinterpret_cast<bfloat16_t*>(O),
        reinterpret_cast<const bfloat16_t*>(X));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 96 && h == 7168) {
    k3_rms_norm_rbs_b96_h7168_kernel<<<dim3(96, 1, 1), 256, 1024, stream>>>(
        reinterpret_cast<const bfloat16_t*>(G),
        reinterpret_cast<bfloat16_t*>(O),
        reinterpret_cast<const bfloat16_t*>(X));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 128 && h == 7168) {
    k3_rms_norm_rbs_b128_h7168_kernel<<<dim3(128, 1, 1), 256, 1024, stream>>>(
        reinterpret_cast<const bfloat16_t*>(G),
        reinterpret_cast<bfloat16_t*>(O),
        reinterpret_cast<const bfloat16_t*>(X));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 1 && h == 512) {
    k3_rms_norm_rbs_b1_h512_kernel<<<dim3(1, 1, 1), 256, 1024, stream>>>(
        reinterpret_cast<const bfloat16_t*>(G),
        reinterpret_cast<bfloat16_t*>(O),
        reinterpret_cast<const bfloat16_t*>(X));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 2 && h == 512) {
    k3_rms_norm_rbs_b2_h512_kernel<<<dim3(2, 1, 1), 256, 1024, stream>>>(
        reinterpret_cast<const bfloat16_t*>(G),
        reinterpret_cast<bfloat16_t*>(O),
        reinterpret_cast<const bfloat16_t*>(X));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 4 && h == 512) {
    k3_rms_norm_rbs_b4_h512_kernel<<<dim3(4, 1, 1), 256, 1024, stream>>>(
        reinterpret_cast<const bfloat16_t*>(G),
        reinterpret_cast<bfloat16_t*>(O),
        reinterpret_cast<const bfloat16_t*>(X));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 8 && h == 512) {
    k3_rms_norm_rbs_b8_h512_kernel<<<dim3(8, 1, 1), 256, 1024, stream>>>(
        reinterpret_cast<const bfloat16_t*>(G),
        reinterpret_cast<bfloat16_t*>(O),
        reinterpret_cast<const bfloat16_t*>(X));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 16 && h == 512) {
    k3_rms_norm_rbs_b16_h512_kernel<<<dim3(16, 1, 1), 256, 1024, stream>>>(
        reinterpret_cast<const bfloat16_t*>(G),
        reinterpret_cast<bfloat16_t*>(O),
        reinterpret_cast<const bfloat16_t*>(X));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 32 && h == 512) {
    k3_rms_norm_rbs_b32_h512_kernel<<<dim3(32, 1, 1), 256, 1024, stream>>>(
        reinterpret_cast<const bfloat16_t*>(G),
        reinterpret_cast<bfloat16_t*>(O),
        reinterpret_cast<const bfloat16_t*>(X));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 48 && h == 512) {
    k3_rms_norm_rbs_b48_h512_kernel<<<dim3(48, 1, 1), 256, 1024, stream>>>(
        reinterpret_cast<const bfloat16_t*>(G),
        reinterpret_cast<bfloat16_t*>(O),
        reinterpret_cast<const bfloat16_t*>(X));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 64 && h == 512) {
    k3_rms_norm_rbs_b64_h512_kernel<<<dim3(64, 1, 1), 256, 1024, stream>>>(
        reinterpret_cast<const bfloat16_t*>(G),
        reinterpret_cast<bfloat16_t*>(O),
        reinterpret_cast<const bfloat16_t*>(X));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 96 && h == 512) {
    k3_rms_norm_rbs_b96_h512_kernel<<<dim3(96, 1, 1), 256, 1024, stream>>>(
        reinterpret_cast<const bfloat16_t*>(G),
        reinterpret_cast<bfloat16_t*>(O),
        reinterpret_cast<const bfloat16_t*>(X));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 128 && h == 512) {
    k3_rms_norm_rbs_b128_h512_kernel<<<dim3(128, 1, 1), 256, 1024, stream>>>(
        reinterpret_cast<const bfloat16_t*>(G),
        reinterpret_cast<bfloat16_t*>(O),
        reinterpret_cast<const bfloat16_t*>(X));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 1 && h == 3584) {
    k3_rms_norm_rbs_b1_h3584_kernel<<<dim3(1, 1, 1), 256, 1024, stream>>>(
        reinterpret_cast<const bfloat16_t*>(G),
        reinterpret_cast<bfloat16_t*>(O),
        reinterpret_cast<const bfloat16_t*>(X));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 2 && h == 3584) {
    k3_rms_norm_rbs_b2_h3584_kernel<<<dim3(2, 1, 1), 256, 1024, stream>>>(
        reinterpret_cast<const bfloat16_t*>(G),
        reinterpret_cast<bfloat16_t*>(O),
        reinterpret_cast<const bfloat16_t*>(X));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 4 && h == 3584) {
    k3_rms_norm_rbs_b4_h3584_kernel<<<dim3(4, 1, 1), 256, 1024, stream>>>(
        reinterpret_cast<const bfloat16_t*>(G),
        reinterpret_cast<bfloat16_t*>(O),
        reinterpret_cast<const bfloat16_t*>(X));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 8 && h == 3584) {
    k3_rms_norm_rbs_b8_h3584_kernel<<<dim3(8, 1, 1), 256, 1024, stream>>>(
        reinterpret_cast<const bfloat16_t*>(G),
        reinterpret_cast<bfloat16_t*>(O),
        reinterpret_cast<const bfloat16_t*>(X));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 16 && h == 3584) {
    k3_rms_norm_rbs_b16_h3584_kernel<<<dim3(16, 1, 1), 256, 1024, stream>>>(
        reinterpret_cast<const bfloat16_t*>(G),
        reinterpret_cast<bfloat16_t*>(O),
        reinterpret_cast<const bfloat16_t*>(X));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 32 && h == 3584) {
    k3_rms_norm_rbs_b32_h3584_kernel<<<dim3(32, 1, 1), 256, 1024, stream>>>(
        reinterpret_cast<const bfloat16_t*>(G),
        reinterpret_cast<bfloat16_t*>(O),
        reinterpret_cast<const bfloat16_t*>(X));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 48 && h == 3584) {
    k3_rms_norm_rbs_b48_h3584_kernel<<<dim3(48, 1, 1), 256, 1024, stream>>>(
        reinterpret_cast<const bfloat16_t*>(G),
        reinterpret_cast<bfloat16_t*>(O),
        reinterpret_cast<const bfloat16_t*>(X));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 64 && h == 3584) {
    k3_rms_norm_rbs_b64_h3584_kernel<<<dim3(64, 1, 1), 256, 1024, stream>>>(
        reinterpret_cast<const bfloat16_t*>(G),
        reinterpret_cast<bfloat16_t*>(O),
        reinterpret_cast<const bfloat16_t*>(X));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 96 && h == 3584) {
    k3_rms_norm_rbs_b96_h3584_kernel<<<dim3(96, 1, 1), 256, 1024, stream>>>(
        reinterpret_cast<const bfloat16_t*>(G),
        reinterpret_cast<bfloat16_t*>(O),
        reinterpret_cast<const bfloat16_t*>(X));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 128 && h == 3584) {
    k3_rms_norm_rbs_b128_h3584_kernel<<<dim3(128, 1, 1), 256, 1024, stream>>>(
        reinterpret_cast<const bfloat16_t*>(G),
        reinterpret_cast<bfloat16_t*>(O),
        reinterpret_cast<const bfloat16_t*>(X));
    return static_cast<int>(cudaGetLastError());
  }
  return static_cast<int>(cudaErrorInvalidValue);
}
