// Generated by pegainfer-k3/kernels/generate.py -- do not edit.
#include <cuda_runtime.h>

#if defined(_MSC_VER) && !defined(__clang__) && _MSC_VER < 1940
#define _tl_orig_alignas alignas
#define alignas(N) _tl_orig_alignas((N) <= 64 ? (N) : 64)
#include <cuda.h>
#undef alignas
#define alignas _tl_orig_alignas
#endif
#include <tl_templates/cuda/reduce.h>
#include <tl_templates/cuda/scan.h>
#include <tl_templates/cuda/ldsm.h>
#include <tl_templates/cuda/threadblock_swizzle.h>
#define debug_print_msg k3_router_topk_batched_debug_print_msg
#define debug_print_buffer_value k3_router_topk_batched_debug_print_buffer_value
#include <tl_templates/cuda/debug.h>
#undef debug_print_msg
#undef debug_print_buffer_value
#ifdef ENABLE_BF16
#include <tl_templates/cuda/cuda_bf16_fallbacks.cuh>
#endif

extern "C" __global__ void k3_router_topk_b1_e896_topk16_kernel(const float* __restrict__ Bias, int* __restrict__ Idx, const bfloat16_t* __restrict__ Rs, const float* __restrict__ S, float* __restrict__ Wts);
extern "C" __global__ void __launch_bounds__(256, 1) k3_router_topk_b1_e896_topk16_kernel(const float* __restrict__ Bias, int* __restrict__ Idx, const bfloat16_t* __restrict__ Rs, const float* __restrict__ S, float* __restrict__ Wts) {
  extern __shared__ __align__(1024) uchar buf_dyn_shmem[];
  void* scores = ((void*)((char*)buf_dyn_shmem + 0));
  void* biased = ((void*)((char*)buf_dyn_shmem + 3584));
  float den = 0x0p+0f/*0.000000e+00*/;
  float best = 0x0p+0f/*0.000000e+00*/;
  int bi = 0;
  if (((int)threadIdx.x) < 224) {
    float broadcast_var = 0x1p+0f/*1.000000e+00*/;
    float broadcast_var_1 = 0x1p+0f/*1.000000e+00*/;
    float broadcast_var_2 = 0x0p+0f/*0.000000e+00*/;
    float4 __1;
      float4 v_ = make_float4(broadcast_var, broadcast_var, broadcast_var, broadcast_var);
      float4 __2;
        float4 v__1 = make_float4(broadcast_var_1, broadcast_var_1, broadcast_var_1, broadcast_var_1);
        float4 __3;
        float4 __4;
          float4 v__2 = make_float4(broadcast_var_2, broadcast_var_2, broadcast_var_2, broadcast_var_2);
          float4 v__3 = *(float4*)(S + (((int)threadIdx.x) * 4));
          *(float2*)(&(__4.x)) = tl::sub2(*(float2*)(&(v__2.x)), *(float2*)(&(v__3.x)));
          *(float2*)(&(__4.z)) = tl::sub2(*(float2*)(&(v__2.z)), *(float2*)(&(v__3.z)));
        __3.x = expf(__4.x);
        __3.y = expf(__4.y);
        __3.z = expf(__4.z);
        __3.w = expf(__4.w);
        *(float2*)(&(__2.x)) = tl::add2(*(float2*)(&(v__1.x)), *(float2*)(&(__3.x)));
        *(float2*)(&(__2.z)) = tl::add2(*(float2*)(&(v__1.z)), *(float2*)(&(__3.z)));
      __1.x = (v_.x/__2.x);
      __1.y = (v_.y/__2.y);
      __1.z = (v_.z/__2.z);
      __1.w = (v_.w/__2.w);
    *(float4*)(((float*)scores) + (((int)threadIdx.x) * 4)) = __1;
    float broadcast_var_3 = 0x1p+0f/*1.000000e+00*/;
    float broadcast_var_4 = 0x1p+0f/*1.000000e+00*/;
    float broadcast_var_5 = 0x0p+0f/*0.000000e+00*/;
    float4 __5;
      float4 __6;
        float4 v__4 = make_float4(broadcast_var_3, broadcast_var_3, broadcast_var_3, broadcast_var_3);
        float4 __7;
          float4 v__5 = make_float4(broadcast_var_4, broadcast_var_4, broadcast_var_4, broadcast_var_4);
          float4 __8;
          float4 __9;
            float4 v__6 = make_float4(broadcast_var_5, broadcast_var_5, broadcast_var_5, broadcast_var_5);
            float4 v__7 = *(float4*)(S + (((int)threadIdx.x) * 4));
            *(float2*)(&(__9.x)) = tl::sub2(*(float2*)(&(v__6.x)), *(float2*)(&(v__7.x)));
            *(float2*)(&(__9.z)) = tl::sub2(*(float2*)(&(v__6.z)), *(float2*)(&(v__7.z)));
          __8.x = expf(__9.x);
          __8.y = expf(__9.y);
          __8.z = expf(__9.z);
          __8.w = expf(__9.w);
          *(float2*)(&(__7.x)) = tl::add2(*(float2*)(&(v__5.x)), *(float2*)(&(__8.x)));
          *(float2*)(&(__7.z)) = tl::add2(*(float2*)(&(v__5.z)), *(float2*)(&(__8.z)));
        __6.x = (v__4.x/__7.x);
        __6.y = (v__4.y/__7.y);
        __6.z = (v__4.z/__7.z);
        __6.w = (v__4.w/__7.w);
      float4 v__8 = *(float4*)(Bias + (((int)threadIdx.x) * 4));
      *(float2*)(&(__5.x)) = tl::add2(*(float2*)(&(__6.x)), *(float2*)(&(v__8.x)));
      *(float2*)(&(__5.z)) = tl::add2(*(float2*)(&(__6.z)), *(float2*)(&(v__8.z)));
    *(float4*)(((float*)biased) + (((int)threadIdx.x) * 4)) = __5;
  }
  __syncthreads();
  if (((int)threadIdx.x) == 0) {
    den = 0x0p+0f/*0.000000e+00*/;
    for (int t = 0; t < 16; ++t) {
      best = -0x1.93e5939a08ceap+99f/*-1.000000e+30*/;
      bi = 0;
      for (int e = 0; e < 896; ++e) {
        if (best < ((float*)biased)[e]) {
          best = ((float*)biased)[e];
          bi = e;
        }
      }
      Idx[t] = bi;
      Wts[t] = ((float*)scores)[bi];
      ((float*)biased)[bi] = -0x1.93e5939a08ceap+99f/*-1.000000e+30*/;
      den = (den + ((float*)scores)[bi]);
    }
    for (int t_1 = 0; t_1 < 16; ++t_1) {
      Wts[t_1] = ((Wts[t_1] / (den + 0x1.79ca10c924223p-67f/*1.000000e-20*/)) * ((float)Rs[0]));
    }
  }
}


extern "C" __global__ void k3_router_topk_b2_e896_topk16_kernel(const float* __restrict__ Bias, int* __restrict__ Idx, const bfloat16_t* __restrict__ Rs, const float* __restrict__ S, float* __restrict__ Wts);
extern "C" __global__ void __launch_bounds__(256, 1) k3_router_topk_b2_e896_topk16_kernel(const float* __restrict__ Bias, int* __restrict__ Idx, const bfloat16_t* __restrict__ Rs, const float* __restrict__ S, float* __restrict__ Wts) {
  extern __shared__ __align__(1024) uchar buf_dyn_shmem[];
  void* scores = ((void*)((char*)buf_dyn_shmem + 0));
  void* biased = ((void*)((char*)buf_dyn_shmem + 3584));
  float den = 0x0p+0f/*0.000000e+00*/;
  float best = 0x0p+0f/*0.000000e+00*/;
  int bi = 0;
  if (((int)threadIdx.x) < 224) {
    float broadcast_var = 0x1p+0f/*1.000000e+00*/;
    float broadcast_var_1 = 0x1p+0f/*1.000000e+00*/;
    float broadcast_var_2 = 0x0p+0f/*0.000000e+00*/;
    float4 __1;
      float4 v_ = make_float4(broadcast_var, broadcast_var, broadcast_var, broadcast_var);
      float4 __2;
        float4 v__1 = make_float4(broadcast_var_1, broadcast_var_1, broadcast_var_1, broadcast_var_1);
        float4 __3;
        float4 __4;
          float4 v__2 = make_float4(broadcast_var_2, broadcast_var_2, broadcast_var_2, broadcast_var_2);
          float4 v__3 = *(float4*)(S + ((((int)blockIdx.x) * 896) + (((int)threadIdx.x) * 4)));
          *(float2*)(&(__4.x)) = tl::sub2(*(float2*)(&(v__2.x)), *(float2*)(&(v__3.x)));
          *(float2*)(&(__4.z)) = tl::sub2(*(float2*)(&(v__2.z)), *(float2*)(&(v__3.z)));
        __3.x = expf(__4.x);
        __3.y = expf(__4.y);
        __3.z = expf(__4.z);
        __3.w = expf(__4.w);
        *(float2*)(&(__2.x)) = tl::add2(*(float2*)(&(v__1.x)), *(float2*)(&(__3.x)));
        *(float2*)(&(__2.z)) = tl::add2(*(float2*)(&(v__1.z)), *(float2*)(&(__3.z)));
      __1.x = (v_.x/__2.x);
      __1.y = (v_.y/__2.y);
      __1.z = (v_.z/__2.z);
      __1.w = (v_.w/__2.w);
    *(float4*)(((float*)scores) + (((int)threadIdx.x) * 4)) = __1;
    float broadcast_var_3 = 0x1p+0f/*1.000000e+00*/;
    float broadcast_var_4 = 0x1p+0f/*1.000000e+00*/;
    float broadcast_var_5 = 0x0p+0f/*0.000000e+00*/;
    float4 __5;
      float4 __6;
        float4 v__4 = make_float4(broadcast_var_3, broadcast_var_3, broadcast_var_3, broadcast_var_3);
        float4 __7;
          float4 v__5 = make_float4(broadcast_var_4, broadcast_var_4, broadcast_var_4, broadcast_var_4);
          float4 __8;
          float4 __9;
            float4 v__6 = make_float4(broadcast_var_5, broadcast_var_5, broadcast_var_5, broadcast_var_5);
            float4 v__7 = *(float4*)(S + ((((int)blockIdx.x) * 896) + (((int)threadIdx.x) * 4)));
            *(float2*)(&(__9.x)) = tl::sub2(*(float2*)(&(v__6.x)), *(float2*)(&(v__7.x)));
            *(float2*)(&(__9.z)) = tl::sub2(*(float2*)(&(v__6.z)), *(float2*)(&(v__7.z)));
          __8.x = expf(__9.x);
          __8.y = expf(__9.y);
          __8.z = expf(__9.z);
          __8.w = expf(__9.w);
          *(float2*)(&(__7.x)) = tl::add2(*(float2*)(&(v__5.x)), *(float2*)(&(__8.x)));
          *(float2*)(&(__7.z)) = tl::add2(*(float2*)(&(v__5.z)), *(float2*)(&(__8.z)));
        __6.x = (v__4.x/__7.x);
        __6.y = (v__4.y/__7.y);
        __6.z = (v__4.z/__7.z);
        __6.w = (v__4.w/__7.w);
      float4 v__8 = *(float4*)(Bias + (((int)threadIdx.x) * 4));
      *(float2*)(&(__5.x)) = tl::add2(*(float2*)(&(__6.x)), *(float2*)(&(v__8.x)));
      *(float2*)(&(__5.z)) = tl::add2(*(float2*)(&(__6.z)), *(float2*)(&(v__8.z)));
    *(float4*)(((float*)biased) + (((int)threadIdx.x) * 4)) = __5;
  }
  __syncthreads();
  if (((int)threadIdx.x) == 0) {
    den = 0x0p+0f/*0.000000e+00*/;
    for (int t = 0; t < 16; ++t) {
      best = -0x1.93e5939a08ceap+99f/*-1.000000e+30*/;
      bi = 0;
      for (int e = 0; e < 896; ++e) {
        if (best < ((float*)biased)[e]) {
          best = ((float*)biased)[e];
          bi = e;
        }
      }
      Idx[((((int)blockIdx.x) * 16) + t)] = bi;
      Wts[((((int)blockIdx.x) * 16) + t)] = ((float*)scores)[bi];
      ((float*)biased)[bi] = -0x1.93e5939a08ceap+99f/*-1.000000e+30*/;
      den = (den + ((float*)scores)[bi]);
    }
    for (int t_1 = 0; t_1 < 16; ++t_1) {
      Wts[((((int)blockIdx.x) * 16) + t_1)] = ((Wts[((((int)blockIdx.x) * 16) + t_1)] / (den + 0x1.79ca10c924223p-67f/*1.000000e-20*/)) * ((float)Rs[0]));
    }
  }
}


extern "C" __global__ void k3_router_topk_b4_e896_topk16_kernel(const float* __restrict__ Bias, int* __restrict__ Idx, const bfloat16_t* __restrict__ Rs, const float* __restrict__ S, float* __restrict__ Wts);
extern "C" __global__ void __launch_bounds__(256, 1) k3_router_topk_b4_e896_topk16_kernel(const float* __restrict__ Bias, int* __restrict__ Idx, const bfloat16_t* __restrict__ Rs, const float* __restrict__ S, float* __restrict__ Wts) {
  extern __shared__ __align__(1024) uchar buf_dyn_shmem[];
  void* scores = ((void*)((char*)buf_dyn_shmem + 0));
  void* biased = ((void*)((char*)buf_dyn_shmem + 3584));
  float den = 0x0p+0f/*0.000000e+00*/;
  float best = 0x0p+0f/*0.000000e+00*/;
  int bi = 0;
  if (((int)threadIdx.x) < 224) {
    float broadcast_var = 0x1p+0f/*1.000000e+00*/;
    float broadcast_var_1 = 0x1p+0f/*1.000000e+00*/;
    float broadcast_var_2 = 0x0p+0f/*0.000000e+00*/;
    float4 __1;
      float4 v_ = make_float4(broadcast_var, broadcast_var, broadcast_var, broadcast_var);
      float4 __2;
        float4 v__1 = make_float4(broadcast_var_1, broadcast_var_1, broadcast_var_1, broadcast_var_1);
        float4 __3;
        float4 __4;
          float4 v__2 = make_float4(broadcast_var_2, broadcast_var_2, broadcast_var_2, broadcast_var_2);
          float4 v__3 = *(float4*)(S + ((((int)blockIdx.x) * 896) + (((int)threadIdx.x) * 4)));
          *(float2*)(&(__4.x)) = tl::sub2(*(float2*)(&(v__2.x)), *(float2*)(&(v__3.x)));
          *(float2*)(&(__4.z)) = tl::sub2(*(float2*)(&(v__2.z)), *(float2*)(&(v__3.z)));
        __3.x = expf(__4.x);
        __3.y = expf(__4.y);
        __3.z = expf(__4.z);
        __3.w = expf(__4.w);
        *(float2*)(&(__2.x)) = tl::add2(*(float2*)(&(v__1.x)), *(float2*)(&(__3.x)));
        *(float2*)(&(__2.z)) = tl::add2(*(float2*)(&(v__1.z)), *(float2*)(&(__3.z)));
      __1.x = (v_.x/__2.x);
      __1.y = (v_.y/__2.y);
      __1.z = (v_.z/__2.z);
      __1.w = (v_.w/__2.w);
    *(float4*)(((float*)scores) + (((int)threadIdx.x) * 4)) = __1;
    float broadcast_var_3 = 0x1p+0f/*1.000000e+00*/;
    float broadcast_var_4 = 0x1p+0f/*1.000000e+00*/;
    float broadcast_var_5 = 0x0p+0f/*0.000000e+00*/;
    float4 __5;
      float4 __6;
        float4 v__4 = make_float4(broadcast_var_3, broadcast_var_3, broadcast_var_3, broadcast_var_3);
        float4 __7;
          float4 v__5 = make_float4(broadcast_var_4, broadcast_var_4, broadcast_var_4, broadcast_var_4);
          float4 __8;
          float4 __9;
            float4 v__6 = make_float4(broadcast_var_5, broadcast_var_5, broadcast_var_5, broadcast_var_5);
            float4 v__7 = *(float4*)(S + ((((int)blockIdx.x) * 896) + (((int)threadIdx.x) * 4)));
            *(float2*)(&(__9.x)) = tl::sub2(*(float2*)(&(v__6.x)), *(float2*)(&(v__7.x)));
            *(float2*)(&(__9.z)) = tl::sub2(*(float2*)(&(v__6.z)), *(float2*)(&(v__7.z)));
          __8.x = expf(__9.x);
          __8.y = expf(__9.y);
          __8.z = expf(__9.z);
          __8.w = expf(__9.w);
          *(float2*)(&(__7.x)) = tl::add2(*(float2*)(&(v__5.x)), *(float2*)(&(__8.x)));
          *(float2*)(&(__7.z)) = tl::add2(*(float2*)(&(v__5.z)), *(float2*)(&(__8.z)));
        __6.x = (v__4.x/__7.x);
        __6.y = (v__4.y/__7.y);
        __6.z = (v__4.z/__7.z);
        __6.w = (v__4.w/__7.w);
      float4 v__8 = *(float4*)(Bias + (((int)threadIdx.x) * 4));
      *(float2*)(&(__5.x)) = tl::add2(*(float2*)(&(__6.x)), *(float2*)(&(v__8.x)));
      *(float2*)(&(__5.z)) = tl::add2(*(float2*)(&(__6.z)), *(float2*)(&(v__8.z)));
    *(float4*)(((float*)biased) + (((int)threadIdx.x) * 4)) = __5;
  }
  __syncthreads();
  if (((int)threadIdx.x) == 0) {
    den = 0x0p+0f/*0.000000e+00*/;
    for (int t = 0; t < 16; ++t) {
      best = -0x1.93e5939a08ceap+99f/*-1.000000e+30*/;
      bi = 0;
      for (int e = 0; e < 896; ++e) {
        if (best < ((float*)biased)[e]) {
          best = ((float*)biased)[e];
          bi = e;
        }
      }
      Idx[((((int)blockIdx.x) * 16) + t)] = bi;
      Wts[((((int)blockIdx.x) * 16) + t)] = ((float*)scores)[bi];
      ((float*)biased)[bi] = -0x1.93e5939a08ceap+99f/*-1.000000e+30*/;
      den = (den + ((float*)scores)[bi]);
    }
    for (int t_1 = 0; t_1 < 16; ++t_1) {
      Wts[((((int)blockIdx.x) * 16) + t_1)] = ((Wts[((((int)blockIdx.x) * 16) + t_1)] / (den + 0x1.79ca10c924223p-67f/*1.000000e-20*/)) * ((float)Rs[0]));
    }
  }
}


extern "C" __global__ void k3_router_topk_b8_e896_topk16_kernel(const float* __restrict__ Bias, int* __restrict__ Idx, const bfloat16_t* __restrict__ Rs, const float* __restrict__ S, float* __restrict__ Wts);
extern "C" __global__ void __launch_bounds__(256, 1) k3_router_topk_b8_e896_topk16_kernel(const float* __restrict__ Bias, int* __restrict__ Idx, const bfloat16_t* __restrict__ Rs, const float* __restrict__ S, float* __restrict__ Wts) {
  extern __shared__ __align__(1024) uchar buf_dyn_shmem[];
  void* scores = ((void*)((char*)buf_dyn_shmem + 0));
  void* biased = ((void*)((char*)buf_dyn_shmem + 3584));
  float den = 0x0p+0f/*0.000000e+00*/;
  float best = 0x0p+0f/*0.000000e+00*/;
  int bi = 0;
  if (((int)threadIdx.x) < 224) {
    float broadcast_var = 0x1p+0f/*1.000000e+00*/;
    float broadcast_var_1 = 0x1p+0f/*1.000000e+00*/;
    float broadcast_var_2 = 0x0p+0f/*0.000000e+00*/;
    float4 __1;
      float4 v_ = make_float4(broadcast_var, broadcast_var, broadcast_var, broadcast_var);
      float4 __2;
        float4 v__1 = make_float4(broadcast_var_1, broadcast_var_1, broadcast_var_1, broadcast_var_1);
        float4 __3;
        float4 __4;
          float4 v__2 = make_float4(broadcast_var_2, broadcast_var_2, broadcast_var_2, broadcast_var_2);
          float4 v__3 = *(float4*)(S + ((((int)blockIdx.x) * 896) + (((int)threadIdx.x) * 4)));
          *(float2*)(&(__4.x)) = tl::sub2(*(float2*)(&(v__2.x)), *(float2*)(&(v__3.x)));
          *(float2*)(&(__4.z)) = tl::sub2(*(float2*)(&(v__2.z)), *(float2*)(&(v__3.z)));
        __3.x = expf(__4.x);
        __3.y = expf(__4.y);
        __3.z = expf(__4.z);
        __3.w = expf(__4.w);
        *(float2*)(&(__2.x)) = tl::add2(*(float2*)(&(v__1.x)), *(float2*)(&(__3.x)));
        *(float2*)(&(__2.z)) = tl::add2(*(float2*)(&(v__1.z)), *(float2*)(&(__3.z)));
      __1.x = (v_.x/__2.x);
      __1.y = (v_.y/__2.y);
      __1.z = (v_.z/__2.z);
      __1.w = (v_.w/__2.w);
    *(float4*)(((float*)scores) + (((int)threadIdx.x) * 4)) = __1;
    float broadcast_var_3 = 0x1p+0f/*1.000000e+00*/;
    float broadcast_var_4 = 0x1p+0f/*1.000000e+00*/;
    float broadcast_var_5 = 0x0p+0f/*0.000000e+00*/;
    float4 __5;
      float4 __6;
        float4 v__4 = make_float4(broadcast_var_3, broadcast_var_3, broadcast_var_3, broadcast_var_3);
        float4 __7;
          float4 v__5 = make_float4(broadcast_var_4, broadcast_var_4, broadcast_var_4, broadcast_var_4);
          float4 __8;
          float4 __9;
            float4 v__6 = make_float4(broadcast_var_5, broadcast_var_5, broadcast_var_5, broadcast_var_5);
            float4 v__7 = *(float4*)(S + ((((int)blockIdx.x) * 896) + (((int)threadIdx.x) * 4)));
            *(float2*)(&(__9.x)) = tl::sub2(*(float2*)(&(v__6.x)), *(float2*)(&(v__7.x)));
            *(float2*)(&(__9.z)) = tl::sub2(*(float2*)(&(v__6.z)), *(float2*)(&(v__7.z)));
          __8.x = expf(__9.x);
          __8.y = expf(__9.y);
          __8.z = expf(__9.z);
          __8.w = expf(__9.w);
          *(float2*)(&(__7.x)) = tl::add2(*(float2*)(&(v__5.x)), *(float2*)(&(__8.x)));
          *(float2*)(&(__7.z)) = tl::add2(*(float2*)(&(v__5.z)), *(float2*)(&(__8.z)));
        __6.x = (v__4.x/__7.x);
        __6.y = (v__4.y/__7.y);
        __6.z = (v__4.z/__7.z);
        __6.w = (v__4.w/__7.w);
      float4 v__8 = *(float4*)(Bias + (((int)threadIdx.x) * 4));
      *(float2*)(&(__5.x)) = tl::add2(*(float2*)(&(__6.x)), *(float2*)(&(v__8.x)));
      *(float2*)(&(__5.z)) = tl::add2(*(float2*)(&(__6.z)), *(float2*)(&(v__8.z)));
    *(float4*)(((float*)biased) + (((int)threadIdx.x) * 4)) = __5;
  }
  __syncthreads();
  if (((int)threadIdx.x) == 0) {
    den = 0x0p+0f/*0.000000e+00*/;
    for (int t = 0; t < 16; ++t) {
      best = -0x1.93e5939a08ceap+99f/*-1.000000e+30*/;
      bi = 0;
      for (int e = 0; e < 896; ++e) {
        if (best < ((float*)biased)[e]) {
          best = ((float*)biased)[e];
          bi = e;
        }
      }
      Idx[((((int)blockIdx.x) * 16) + t)] = bi;
      Wts[((((int)blockIdx.x) * 16) + t)] = ((float*)scores)[bi];
      ((float*)biased)[bi] = -0x1.93e5939a08ceap+99f/*-1.000000e+30*/;
      den = (den + ((float*)scores)[bi]);
    }
    for (int t_1 = 0; t_1 < 16; ++t_1) {
      Wts[((((int)blockIdx.x) * 16) + t_1)] = ((Wts[((((int)blockIdx.x) * 16) + t_1)] / (den + 0x1.79ca10c924223p-67f/*1.000000e-20*/)) * ((float)Rs[0]));
    }
  }
}


extern "C" __global__ void k3_router_topk_b16_e896_topk16_kernel(const float* __restrict__ Bias, int* __restrict__ Idx, const bfloat16_t* __restrict__ Rs, const float* __restrict__ S, float* __restrict__ Wts);
extern "C" __global__ void __launch_bounds__(256, 1) k3_router_topk_b16_e896_topk16_kernel(const float* __restrict__ Bias, int* __restrict__ Idx, const bfloat16_t* __restrict__ Rs, const float* __restrict__ S, float* __restrict__ Wts) {
  extern __shared__ __align__(1024) uchar buf_dyn_shmem[];
  void* scores = ((void*)((char*)buf_dyn_shmem + 0));
  void* biased = ((void*)((char*)buf_dyn_shmem + 3584));
  float den = 0x0p+0f/*0.000000e+00*/;
  float best = 0x0p+0f/*0.000000e+00*/;
  int bi = 0;
  if (((int)threadIdx.x) < 224) {
    float broadcast_var = 0x1p+0f/*1.000000e+00*/;
    float broadcast_var_1 = 0x1p+0f/*1.000000e+00*/;
    float broadcast_var_2 = 0x0p+0f/*0.000000e+00*/;
    float4 __1;
      float4 v_ = make_float4(broadcast_var, broadcast_var, broadcast_var, broadcast_var);
      float4 __2;
        float4 v__1 = make_float4(broadcast_var_1, broadcast_var_1, broadcast_var_1, broadcast_var_1);
        float4 __3;
        float4 __4;
          float4 v__2 = make_float4(broadcast_var_2, broadcast_var_2, broadcast_var_2, broadcast_var_2);
          float4 v__3 = *(float4*)(S + ((((int)blockIdx.x) * 896) + (((int)threadIdx.x) * 4)));
          *(float2*)(&(__4.x)) = tl::sub2(*(float2*)(&(v__2.x)), *(float2*)(&(v__3.x)));
          *(float2*)(&(__4.z)) = tl::sub2(*(float2*)(&(v__2.z)), *(float2*)(&(v__3.z)));
        __3.x = expf(__4.x);
        __3.y = expf(__4.y);
        __3.z = expf(__4.z);
        __3.w = expf(__4.w);
        *(float2*)(&(__2.x)) = tl::add2(*(float2*)(&(v__1.x)), *(float2*)(&(__3.x)));
        *(float2*)(&(__2.z)) = tl::add2(*(float2*)(&(v__1.z)), *(float2*)(&(__3.z)));
      __1.x = (v_.x/__2.x);
      __1.y = (v_.y/__2.y);
      __1.z = (v_.z/__2.z);
      __1.w = (v_.w/__2.w);
    *(float4*)(((float*)scores) + (((int)threadIdx.x) * 4)) = __1;
    float broadcast_var_3 = 0x1p+0f/*1.000000e+00*/;
    float broadcast_var_4 = 0x1p+0f/*1.000000e+00*/;
    float broadcast_var_5 = 0x0p+0f/*0.000000e+00*/;
    float4 __5;
      float4 __6;
        float4 v__4 = make_float4(broadcast_var_3, broadcast_var_3, broadcast_var_3, broadcast_var_3);
        float4 __7;
          float4 v__5 = make_float4(broadcast_var_4, broadcast_var_4, broadcast_var_4, broadcast_var_4);
          float4 __8;
          float4 __9;
            float4 v__6 = make_float4(broadcast_var_5, broadcast_var_5, broadcast_var_5, broadcast_var_5);
            float4 v__7 = *(float4*)(S + ((((int)blockIdx.x) * 896) + (((int)threadIdx.x) * 4)));
            *(float2*)(&(__9.x)) = tl::sub2(*(float2*)(&(v__6.x)), *(float2*)(&(v__7.x)));
            *(float2*)(&(__9.z)) = tl::sub2(*(float2*)(&(v__6.z)), *(float2*)(&(v__7.z)));
          __8.x = expf(__9.x);
          __8.y = expf(__9.y);
          __8.z = expf(__9.z);
          __8.w = expf(__9.w);
          *(float2*)(&(__7.x)) = tl::add2(*(float2*)(&(v__5.x)), *(float2*)(&(__8.x)));
          *(float2*)(&(__7.z)) = tl::add2(*(float2*)(&(v__5.z)), *(float2*)(&(__8.z)));
        __6.x = (v__4.x/__7.x);
        __6.y = (v__4.y/__7.y);
        __6.z = (v__4.z/__7.z);
        __6.w = (v__4.w/__7.w);
      float4 v__8 = *(float4*)(Bias + (((int)threadIdx.x) * 4));
      *(float2*)(&(__5.x)) = tl::add2(*(float2*)(&(__6.x)), *(float2*)(&(v__8.x)));
      *(float2*)(&(__5.z)) = tl::add2(*(float2*)(&(__6.z)), *(float2*)(&(v__8.z)));
    *(float4*)(((float*)biased) + (((int)threadIdx.x) * 4)) = __5;
  }
  __syncthreads();
  if (((int)threadIdx.x) == 0) {
    den = 0x0p+0f/*0.000000e+00*/;
    for (int t = 0; t < 16; ++t) {
      best = -0x1.93e5939a08ceap+99f/*-1.000000e+30*/;
      bi = 0;
      for (int e = 0; e < 896; ++e) {
        if (best < ((float*)biased)[e]) {
          best = ((float*)biased)[e];
          bi = e;
        }
      }
      Idx[((((int)blockIdx.x) * 16) + t)] = bi;
      Wts[((((int)blockIdx.x) * 16) + t)] = ((float*)scores)[bi];
      ((float*)biased)[bi] = -0x1.93e5939a08ceap+99f/*-1.000000e+30*/;
      den = (den + ((float*)scores)[bi]);
    }
    for (int t_1 = 0; t_1 < 16; ++t_1) {
      Wts[((((int)blockIdx.x) * 16) + t_1)] = ((Wts[((((int)blockIdx.x) * 16) + t_1)] / (den + 0x1.79ca10c924223p-67f/*1.000000e-20*/)) * ((float)Rs[0]));
    }
  }
}


extern "C" __global__ void k3_router_topk_b32_e896_topk16_kernel(const float* __restrict__ Bias, int* __restrict__ Idx, const bfloat16_t* __restrict__ Rs, const float* __restrict__ S, float* __restrict__ Wts);
extern "C" __global__ void __launch_bounds__(256, 1) k3_router_topk_b32_e896_topk16_kernel(const float* __restrict__ Bias, int* __restrict__ Idx, const bfloat16_t* __restrict__ Rs, const float* __restrict__ S, float* __restrict__ Wts) {
  extern __shared__ __align__(1024) uchar buf_dyn_shmem[];
  void* scores = ((void*)((char*)buf_dyn_shmem + 0));
  void* biased = ((void*)((char*)buf_dyn_shmem + 3584));
  float den = 0x0p+0f/*0.000000e+00*/;
  float best = 0x0p+0f/*0.000000e+00*/;
  int bi = 0;
  if (((int)threadIdx.x) < 224) {
    float broadcast_var = 0x1p+0f/*1.000000e+00*/;
    float broadcast_var_1 = 0x1p+0f/*1.000000e+00*/;
    float broadcast_var_2 = 0x0p+0f/*0.000000e+00*/;
    float4 __1;
      float4 v_ = make_float4(broadcast_var, broadcast_var, broadcast_var, broadcast_var);
      float4 __2;
        float4 v__1 = make_float4(broadcast_var_1, broadcast_var_1, broadcast_var_1, broadcast_var_1);
        float4 __3;
        float4 __4;
          float4 v__2 = make_float4(broadcast_var_2, broadcast_var_2, broadcast_var_2, broadcast_var_2);
          float4 v__3 = *(float4*)(S + ((((int)blockIdx.x) * 896) + (((int)threadIdx.x) * 4)));
          *(float2*)(&(__4.x)) = tl::sub2(*(float2*)(&(v__2.x)), *(float2*)(&(v__3.x)));
          *(float2*)(&(__4.z)) = tl::sub2(*(float2*)(&(v__2.z)), *(float2*)(&(v__3.z)));
        __3.x = expf(__4.x);
        __3.y = expf(__4.y);
        __3.z = expf(__4.z);
        __3.w = expf(__4.w);
        *(float2*)(&(__2.x)) = tl::add2(*(float2*)(&(v__1.x)), *(float2*)(&(__3.x)));
        *(float2*)(&(__2.z)) = tl::add2(*(float2*)(&(v__1.z)), *(float2*)(&(__3.z)));
      __1.x = (v_.x/__2.x);
      __1.y = (v_.y/__2.y);
      __1.z = (v_.z/__2.z);
      __1.w = (v_.w/__2.w);
    *(float4*)(((float*)scores) + (((int)threadIdx.x) * 4)) = __1;
    float broadcast_var_3 = 0x1p+0f/*1.000000e+00*/;
    float broadcast_var_4 = 0x1p+0f/*1.000000e+00*/;
    float broadcast_var_5 = 0x0p+0f/*0.000000e+00*/;
    float4 __5;
      float4 __6;
        float4 v__4 = make_float4(broadcast_var_3, broadcast_var_3, broadcast_var_3, broadcast_var_3);
        float4 __7;
          float4 v__5 = make_float4(broadcast_var_4, broadcast_var_4, broadcast_var_4, broadcast_var_4);
          float4 __8;
          float4 __9;
            float4 v__6 = make_float4(broadcast_var_5, broadcast_var_5, broadcast_var_5, broadcast_var_5);
            float4 v__7 = *(float4*)(S + ((((int)blockIdx.x) * 896) + (((int)threadIdx.x) * 4)));
            *(float2*)(&(__9.x)) = tl::sub2(*(float2*)(&(v__6.x)), *(float2*)(&(v__7.x)));
            *(float2*)(&(__9.z)) = tl::sub2(*(float2*)(&(v__6.z)), *(float2*)(&(v__7.z)));
          __8.x = expf(__9.x);
          __8.y = expf(__9.y);
          __8.z = expf(__9.z);
          __8.w = expf(__9.w);
          *(float2*)(&(__7.x)) = tl::add2(*(float2*)(&(v__5.x)), *(float2*)(&(__8.x)));
          *(float2*)(&(__7.z)) = tl::add2(*(float2*)(&(v__5.z)), *(float2*)(&(__8.z)));
        __6.x = (v__4.x/__7.x);
        __6.y = (v__4.y/__7.y);
        __6.z = (v__4.z/__7.z);
        __6.w = (v__4.w/__7.w);
      float4 v__8 = *(float4*)(Bias + (((int)threadIdx.x) * 4));
      *(float2*)(&(__5.x)) = tl::add2(*(float2*)(&(__6.x)), *(float2*)(&(v__8.x)));
      *(float2*)(&(__5.z)) = tl::add2(*(float2*)(&(__6.z)), *(float2*)(&(v__8.z)));
    *(float4*)(((float*)biased) + (((int)threadIdx.x) * 4)) = __5;
  }
  __syncthreads();
  if (((int)threadIdx.x) == 0) {
    den = 0x0p+0f/*0.000000e+00*/;
    for (int t = 0; t < 16; ++t) {
      best = -0x1.93e5939a08ceap+99f/*-1.000000e+30*/;
      bi = 0;
      for (int e = 0; e < 896; ++e) {
        if (best < ((float*)biased)[e]) {
          best = ((float*)biased)[e];
          bi = e;
        }
      }
      Idx[((((int)blockIdx.x) * 16) + t)] = bi;
      Wts[((((int)blockIdx.x) * 16) + t)] = ((float*)scores)[bi];
      ((float*)biased)[bi] = -0x1.93e5939a08ceap+99f/*-1.000000e+30*/;
      den = (den + ((float*)scores)[bi]);
    }
    for (int t_1 = 0; t_1 < 16; ++t_1) {
      Wts[((((int)blockIdx.x) * 16) + t_1)] = ((Wts[((((int)blockIdx.x) * 16) + t_1)] / (den + 0x1.79ca10c924223p-67f/*1.000000e-20*/)) * ((float)Rs[0]));
    }
  }
}


extern "C" __global__ void k3_router_topk_b48_e896_topk16_kernel(const float* __restrict__ Bias, int* __restrict__ Idx, const bfloat16_t* __restrict__ Rs, const float* __restrict__ S, float* __restrict__ Wts);
extern "C" __global__ void __launch_bounds__(256, 1) k3_router_topk_b48_e896_topk16_kernel(const float* __restrict__ Bias, int* __restrict__ Idx, const bfloat16_t* __restrict__ Rs, const float* __restrict__ S, float* __restrict__ Wts) {
  extern __shared__ __align__(1024) uchar buf_dyn_shmem[];
  void* scores = ((void*)((char*)buf_dyn_shmem + 0));
  void* biased = ((void*)((char*)buf_dyn_shmem + 3584));
  float den = 0x0p+0f/*0.000000e+00*/;
  float best = 0x0p+0f/*0.000000e+00*/;
  int bi = 0;
  if (((int)threadIdx.x) < 224) {
    float broadcast_var = 0x1p+0f/*1.000000e+00*/;
    float broadcast_var_1 = 0x1p+0f/*1.000000e+00*/;
    float broadcast_var_2 = 0x0p+0f/*0.000000e+00*/;
    float4 __1;
      float4 v_ = make_float4(broadcast_var, broadcast_var, broadcast_var, broadcast_var);
      float4 __2;
        float4 v__1 = make_float4(broadcast_var_1, broadcast_var_1, broadcast_var_1, broadcast_var_1);
        float4 __3;
        float4 __4;
          float4 v__2 = make_float4(broadcast_var_2, broadcast_var_2, broadcast_var_2, broadcast_var_2);
          float4 v__3 = *(float4*)(S + ((((int)blockIdx.x) * 896) + (((int)threadIdx.x) * 4)));
          *(float2*)(&(__4.x)) = tl::sub2(*(float2*)(&(v__2.x)), *(float2*)(&(v__3.x)));
          *(float2*)(&(__4.z)) = tl::sub2(*(float2*)(&(v__2.z)), *(float2*)(&(v__3.z)));
        __3.x = expf(__4.x);
        __3.y = expf(__4.y);
        __3.z = expf(__4.z);
        __3.w = expf(__4.w);
        *(float2*)(&(__2.x)) = tl::add2(*(float2*)(&(v__1.x)), *(float2*)(&(__3.x)));
        *(float2*)(&(__2.z)) = tl::add2(*(float2*)(&(v__1.z)), *(float2*)(&(__3.z)));
      __1.x = (v_.x/__2.x);
      __1.y = (v_.y/__2.y);
      __1.z = (v_.z/__2.z);
      __1.w = (v_.w/__2.w);
    *(float4*)(((float*)scores) + (((int)threadIdx.x) * 4)) = __1;
    float broadcast_var_3 = 0x1p+0f/*1.000000e+00*/;
    float broadcast_var_4 = 0x1p+0f/*1.000000e+00*/;
    float broadcast_var_5 = 0x0p+0f/*0.000000e+00*/;
    float4 __5;
      float4 __6;
        float4 v__4 = make_float4(broadcast_var_3, broadcast_var_3, broadcast_var_3, broadcast_var_3);
        float4 __7;
          float4 v__5 = make_float4(broadcast_var_4, broadcast_var_4, broadcast_var_4, broadcast_var_4);
          float4 __8;
          float4 __9;
            float4 v__6 = make_float4(broadcast_var_5, broadcast_var_5, broadcast_var_5, broadcast_var_5);
            float4 v__7 = *(float4*)(S + ((((int)blockIdx.x) * 896) + (((int)threadIdx.x) * 4)));
            *(float2*)(&(__9.x)) = tl::sub2(*(float2*)(&(v__6.x)), *(float2*)(&(v__7.x)));
            *(float2*)(&(__9.z)) = tl::sub2(*(float2*)(&(v__6.z)), *(float2*)(&(v__7.z)));
          __8.x = expf(__9.x);
          __8.y = expf(__9.y);
          __8.z = expf(__9.z);
          __8.w = expf(__9.w);
          *(float2*)(&(__7.x)) = tl::add2(*(float2*)(&(v__5.x)), *(float2*)(&(__8.x)));
          *(float2*)(&(__7.z)) = tl::add2(*(float2*)(&(v__5.z)), *(float2*)(&(__8.z)));
        __6.x = (v__4.x/__7.x);
        __6.y = (v__4.y/__7.y);
        __6.z = (v__4.z/__7.z);
        __6.w = (v__4.w/__7.w);
      float4 v__8 = *(float4*)(Bias + (((int)threadIdx.x) * 4));
      *(float2*)(&(__5.x)) = tl::add2(*(float2*)(&(__6.x)), *(float2*)(&(v__8.x)));
      *(float2*)(&(__5.z)) = tl::add2(*(float2*)(&(__6.z)), *(float2*)(&(v__8.z)));
    *(float4*)(((float*)biased) + (((int)threadIdx.x) * 4)) = __5;
  }
  __syncthreads();
  if (((int)threadIdx.x) == 0) {
    den = 0x0p+0f/*0.000000e+00*/;
    for (int t = 0; t < 16; ++t) {
      best = -0x1.93e5939a08ceap+99f/*-1.000000e+30*/;
      bi = 0;
      for (int e = 0; e < 896; ++e) {
        if (best < ((float*)biased)[e]) {
          best = ((float*)biased)[e];
          bi = e;
        }
      }
      Idx[((((int)blockIdx.x) * 16) + t)] = bi;
      Wts[((((int)blockIdx.x) * 16) + t)] = ((float*)scores)[bi];
      ((float*)biased)[bi] = -0x1.93e5939a08ceap+99f/*-1.000000e+30*/;
      den = (den + ((float*)scores)[bi]);
    }
    for (int t_1 = 0; t_1 < 16; ++t_1) {
      Wts[((((int)blockIdx.x) * 16) + t_1)] = ((Wts[((((int)blockIdx.x) * 16) + t_1)] / (den + 0x1.79ca10c924223p-67f/*1.000000e-20*/)) * ((float)Rs[0]));
    }
  }
}


extern "C" __global__ void k3_router_topk_b64_e896_topk16_kernel(const float* __restrict__ Bias, int* __restrict__ Idx, const bfloat16_t* __restrict__ Rs, const float* __restrict__ S, float* __restrict__ Wts);
extern "C" __global__ void __launch_bounds__(256, 1) k3_router_topk_b64_e896_topk16_kernel(const float* __restrict__ Bias, int* __restrict__ Idx, const bfloat16_t* __restrict__ Rs, const float* __restrict__ S, float* __restrict__ Wts) {
  extern __shared__ __align__(1024) uchar buf_dyn_shmem[];
  void* scores = ((void*)((char*)buf_dyn_shmem + 0));
  void* biased = ((void*)((char*)buf_dyn_shmem + 3584));
  float den = 0x0p+0f/*0.000000e+00*/;
  float best = 0x0p+0f/*0.000000e+00*/;
  int bi = 0;
  if (((int)threadIdx.x) < 224) {
    float broadcast_var = 0x1p+0f/*1.000000e+00*/;
    float broadcast_var_1 = 0x1p+0f/*1.000000e+00*/;
    float broadcast_var_2 = 0x0p+0f/*0.000000e+00*/;
    float4 __1;
      float4 v_ = make_float4(broadcast_var, broadcast_var, broadcast_var, broadcast_var);
      float4 __2;
        float4 v__1 = make_float4(broadcast_var_1, broadcast_var_1, broadcast_var_1, broadcast_var_1);
        float4 __3;
        float4 __4;
          float4 v__2 = make_float4(broadcast_var_2, broadcast_var_2, broadcast_var_2, broadcast_var_2);
          float4 v__3 = *(float4*)(S + ((((int)blockIdx.x) * 896) + (((int)threadIdx.x) * 4)));
          *(float2*)(&(__4.x)) = tl::sub2(*(float2*)(&(v__2.x)), *(float2*)(&(v__3.x)));
          *(float2*)(&(__4.z)) = tl::sub2(*(float2*)(&(v__2.z)), *(float2*)(&(v__3.z)));
        __3.x = expf(__4.x);
        __3.y = expf(__4.y);
        __3.z = expf(__4.z);
        __3.w = expf(__4.w);
        *(float2*)(&(__2.x)) = tl::add2(*(float2*)(&(v__1.x)), *(float2*)(&(__3.x)));
        *(float2*)(&(__2.z)) = tl::add2(*(float2*)(&(v__1.z)), *(float2*)(&(__3.z)));
      __1.x = (v_.x/__2.x);
      __1.y = (v_.y/__2.y);
      __1.z = (v_.z/__2.z);
      __1.w = (v_.w/__2.w);
    *(float4*)(((float*)scores) + (((int)threadIdx.x) * 4)) = __1;
    float broadcast_var_3 = 0x1p+0f/*1.000000e+00*/;
    float broadcast_var_4 = 0x1p+0f/*1.000000e+00*/;
    float broadcast_var_5 = 0x0p+0f/*0.000000e+00*/;
    float4 __5;
      float4 __6;
        float4 v__4 = make_float4(broadcast_var_3, broadcast_var_3, broadcast_var_3, broadcast_var_3);
        float4 __7;
          float4 v__5 = make_float4(broadcast_var_4, broadcast_var_4, broadcast_var_4, broadcast_var_4);
          float4 __8;
          float4 __9;
            float4 v__6 = make_float4(broadcast_var_5, broadcast_var_5, broadcast_var_5, broadcast_var_5);
            float4 v__7 = *(float4*)(S + ((((int)blockIdx.x) * 896) + (((int)threadIdx.x) * 4)));
            *(float2*)(&(__9.x)) = tl::sub2(*(float2*)(&(v__6.x)), *(float2*)(&(v__7.x)));
            *(float2*)(&(__9.z)) = tl::sub2(*(float2*)(&(v__6.z)), *(float2*)(&(v__7.z)));
          __8.x = expf(__9.x);
          __8.y = expf(__9.y);
          __8.z = expf(__9.z);
          __8.w = expf(__9.w);
          *(float2*)(&(__7.x)) = tl::add2(*(float2*)(&(v__5.x)), *(float2*)(&(__8.x)));
          *(float2*)(&(__7.z)) = tl::add2(*(float2*)(&(v__5.z)), *(float2*)(&(__8.z)));
        __6.x = (v__4.x/__7.x);
        __6.y = (v__4.y/__7.y);
        __6.z = (v__4.z/__7.z);
        __6.w = (v__4.w/__7.w);
      float4 v__8 = *(float4*)(Bias + (((int)threadIdx.x) * 4));
      *(float2*)(&(__5.x)) = tl::add2(*(float2*)(&(__6.x)), *(float2*)(&(v__8.x)));
      *(float2*)(&(__5.z)) = tl::add2(*(float2*)(&(__6.z)), *(float2*)(&(v__8.z)));
    *(float4*)(((float*)biased) + (((int)threadIdx.x) * 4)) = __5;
  }
  __syncthreads();
  if (((int)threadIdx.x) == 0) {
    den = 0x0p+0f/*0.000000e+00*/;
    for (int t = 0; t < 16; ++t) {
      best = -0x1.93e5939a08ceap+99f/*-1.000000e+30*/;
      bi = 0;
      for (int e = 0; e < 896; ++e) {
        if (best < ((float*)biased)[e]) {
          best = ((float*)biased)[e];
          bi = e;
        }
      }
      Idx[((((int)blockIdx.x) * 16) + t)] = bi;
      Wts[((((int)blockIdx.x) * 16) + t)] = ((float*)scores)[bi];
      ((float*)biased)[bi] = -0x1.93e5939a08ceap+99f/*-1.000000e+30*/;
      den = (den + ((float*)scores)[bi]);
    }
    for (int t_1 = 0; t_1 < 16; ++t_1) {
      Wts[((((int)blockIdx.x) * 16) + t_1)] = ((Wts[((((int)blockIdx.x) * 16) + t_1)] / (den + 0x1.79ca10c924223p-67f/*1.000000e-20*/)) * ((float)Rs[0]));
    }
  }
}


extern "C" __global__ void k3_router_topk_b96_e896_topk16_kernel(const float* __restrict__ Bias, int* __restrict__ Idx, const bfloat16_t* __restrict__ Rs, const float* __restrict__ S, float* __restrict__ Wts);
extern "C" __global__ void __launch_bounds__(256, 1) k3_router_topk_b96_e896_topk16_kernel(const float* __restrict__ Bias, int* __restrict__ Idx, const bfloat16_t* __restrict__ Rs, const float* __restrict__ S, float* __restrict__ Wts) {
  extern __shared__ __align__(1024) uchar buf_dyn_shmem[];
  void* scores = ((void*)((char*)buf_dyn_shmem + 0));
  void* biased = ((void*)((char*)buf_dyn_shmem + 3584));
  float den = 0x0p+0f/*0.000000e+00*/;
  float best = 0x0p+0f/*0.000000e+00*/;
  int bi = 0;
  if (((int)threadIdx.x) < 224) {
    float broadcast_var = 0x1p+0f/*1.000000e+00*/;
    float broadcast_var_1 = 0x1p+0f/*1.000000e+00*/;
    float broadcast_var_2 = 0x0p+0f/*0.000000e+00*/;
    float4 __1;
      float4 v_ = make_float4(broadcast_var, broadcast_var, broadcast_var, broadcast_var);
      float4 __2;
        float4 v__1 = make_float4(broadcast_var_1, broadcast_var_1, broadcast_var_1, broadcast_var_1);
        float4 __3;
        float4 __4;
          float4 v__2 = make_float4(broadcast_var_2, broadcast_var_2, broadcast_var_2, broadcast_var_2);
          float4 v__3 = *(float4*)(S + ((((int)blockIdx.x) * 896) + (((int)threadIdx.x) * 4)));
          *(float2*)(&(__4.x)) = tl::sub2(*(float2*)(&(v__2.x)), *(float2*)(&(v__3.x)));
          *(float2*)(&(__4.z)) = tl::sub2(*(float2*)(&(v__2.z)), *(float2*)(&(v__3.z)));
        __3.x = expf(__4.x);
        __3.y = expf(__4.y);
        __3.z = expf(__4.z);
        __3.w = expf(__4.w);
        *(float2*)(&(__2.x)) = tl::add2(*(float2*)(&(v__1.x)), *(float2*)(&(__3.x)));
        *(float2*)(&(__2.z)) = tl::add2(*(float2*)(&(v__1.z)), *(float2*)(&(__3.z)));
      __1.x = (v_.x/__2.x);
      __1.y = (v_.y/__2.y);
      __1.z = (v_.z/__2.z);
      __1.w = (v_.w/__2.w);
    *(float4*)(((float*)scores) + (((int)threadIdx.x) * 4)) = __1;
    float broadcast_var_3 = 0x1p+0f/*1.000000e+00*/;
    float broadcast_var_4 = 0x1p+0f/*1.000000e+00*/;
    float broadcast_var_5 = 0x0p+0f/*0.000000e+00*/;
    float4 __5;
      float4 __6;
        float4 v__4 = make_float4(broadcast_var_3, broadcast_var_3, broadcast_var_3, broadcast_var_3);
        float4 __7;
          float4 v__5 = make_float4(broadcast_var_4, broadcast_var_4, broadcast_var_4, broadcast_var_4);
          float4 __8;
          float4 __9;
            float4 v__6 = make_float4(broadcast_var_5, broadcast_var_5, broadcast_var_5, broadcast_var_5);
            float4 v__7 = *(float4*)(S + ((((int)blockIdx.x) * 896) + (((int)threadIdx.x) * 4)));
            *(float2*)(&(__9.x)) = tl::sub2(*(float2*)(&(v__6.x)), *(float2*)(&(v__7.x)));
            *(float2*)(&(__9.z)) = tl::sub2(*(float2*)(&(v__6.z)), *(float2*)(&(v__7.z)));
          __8.x = expf(__9.x);
          __8.y = expf(__9.y);
          __8.z = expf(__9.z);
          __8.w = expf(__9.w);
          *(float2*)(&(__7.x)) = tl::add2(*(float2*)(&(v__5.x)), *(float2*)(&(__8.x)));
          *(float2*)(&(__7.z)) = tl::add2(*(float2*)(&(v__5.z)), *(float2*)(&(__8.z)));
        __6.x = (v__4.x/__7.x);
        __6.y = (v__4.y/__7.y);
        __6.z = (v__4.z/__7.z);
        __6.w = (v__4.w/__7.w);
      float4 v__8 = *(float4*)(Bias + (((int)threadIdx.x) * 4));
      *(float2*)(&(__5.x)) = tl::add2(*(float2*)(&(__6.x)), *(float2*)(&(v__8.x)));
      *(float2*)(&(__5.z)) = tl::add2(*(float2*)(&(__6.z)), *(float2*)(&(v__8.z)));
    *(float4*)(((float*)biased) + (((int)threadIdx.x) * 4)) = __5;
  }
  __syncthreads();
  if (((int)threadIdx.x) == 0) {
    den = 0x0p+0f/*0.000000e+00*/;
    for (int t = 0; t < 16; ++t) {
      best = -0x1.93e5939a08ceap+99f/*-1.000000e+30*/;
      bi = 0;
      for (int e = 0; e < 896; ++e) {
        if (best < ((float*)biased)[e]) {
          best = ((float*)biased)[e];
          bi = e;
        }
      }
      Idx[((((int)blockIdx.x) * 16) + t)] = bi;
      Wts[((((int)blockIdx.x) * 16) + t)] = ((float*)scores)[bi];
      ((float*)biased)[bi] = -0x1.93e5939a08ceap+99f/*-1.000000e+30*/;
      den = (den + ((float*)scores)[bi]);
    }
    for (int t_1 = 0; t_1 < 16; ++t_1) {
      Wts[((((int)blockIdx.x) * 16) + t_1)] = ((Wts[((((int)blockIdx.x) * 16) + t_1)] / (den + 0x1.79ca10c924223p-67f/*1.000000e-20*/)) * ((float)Rs[0]));
    }
  }
}


extern "C" __global__ void k3_router_topk_b128_e896_topk16_kernel(const float* __restrict__ Bias, int* __restrict__ Idx, const bfloat16_t* __restrict__ Rs, const float* __restrict__ S, float* __restrict__ Wts);
extern "C" __global__ void __launch_bounds__(256, 1) k3_router_topk_b128_e896_topk16_kernel(const float* __restrict__ Bias, int* __restrict__ Idx, const bfloat16_t* __restrict__ Rs, const float* __restrict__ S, float* __restrict__ Wts) {
  extern __shared__ __align__(1024) uchar buf_dyn_shmem[];
  void* scores = ((void*)((char*)buf_dyn_shmem + 0));
  void* biased = ((void*)((char*)buf_dyn_shmem + 3584));
  float den = 0x0p+0f/*0.000000e+00*/;
  float best = 0x0p+0f/*0.000000e+00*/;
  int bi = 0;
  if (((int)threadIdx.x) < 224) {
    float broadcast_var = 0x1p+0f/*1.000000e+00*/;
    float broadcast_var_1 = 0x1p+0f/*1.000000e+00*/;
    float broadcast_var_2 = 0x0p+0f/*0.000000e+00*/;
    float4 __1;
      float4 v_ = make_float4(broadcast_var, broadcast_var, broadcast_var, broadcast_var);
      float4 __2;
        float4 v__1 = make_float4(broadcast_var_1, broadcast_var_1, broadcast_var_1, broadcast_var_1);
        float4 __3;
        float4 __4;
          float4 v__2 = make_float4(broadcast_var_2, broadcast_var_2, broadcast_var_2, broadcast_var_2);
          float4 v__3 = *(float4*)(S + ((((int)blockIdx.x) * 896) + (((int)threadIdx.x) * 4)));
          *(float2*)(&(__4.x)) = tl::sub2(*(float2*)(&(v__2.x)), *(float2*)(&(v__3.x)));
          *(float2*)(&(__4.z)) = tl::sub2(*(float2*)(&(v__2.z)), *(float2*)(&(v__3.z)));
        __3.x = expf(__4.x);
        __3.y = expf(__4.y);
        __3.z = expf(__4.z);
        __3.w = expf(__4.w);
        *(float2*)(&(__2.x)) = tl::add2(*(float2*)(&(v__1.x)), *(float2*)(&(__3.x)));
        *(float2*)(&(__2.z)) = tl::add2(*(float2*)(&(v__1.z)), *(float2*)(&(__3.z)));
      __1.x = (v_.x/__2.x);
      __1.y = (v_.y/__2.y);
      __1.z = (v_.z/__2.z);
      __1.w = (v_.w/__2.w);
    *(float4*)(((float*)scores) + (((int)threadIdx.x) * 4)) = __1;
    float broadcast_var_3 = 0x1p+0f/*1.000000e+00*/;
    float broadcast_var_4 = 0x1p+0f/*1.000000e+00*/;
    float broadcast_var_5 = 0x0p+0f/*0.000000e+00*/;
    float4 __5;
      float4 __6;
        float4 v__4 = make_float4(broadcast_var_3, broadcast_var_3, broadcast_var_3, broadcast_var_3);
        float4 __7;
          float4 v__5 = make_float4(broadcast_var_4, broadcast_var_4, broadcast_var_4, broadcast_var_4);
          float4 __8;
          float4 __9;
            float4 v__6 = make_float4(broadcast_var_5, broadcast_var_5, broadcast_var_5, broadcast_var_5);
            float4 v__7 = *(float4*)(S + ((((int)blockIdx.x) * 896) + (((int)threadIdx.x) * 4)));
            *(float2*)(&(__9.x)) = tl::sub2(*(float2*)(&(v__6.x)), *(float2*)(&(v__7.x)));
            *(float2*)(&(__9.z)) = tl::sub2(*(float2*)(&(v__6.z)), *(float2*)(&(v__7.z)));
          __8.x = expf(__9.x);
          __8.y = expf(__9.y);
          __8.z = expf(__9.z);
          __8.w = expf(__9.w);
          *(float2*)(&(__7.x)) = tl::add2(*(float2*)(&(v__5.x)), *(float2*)(&(__8.x)));
          *(float2*)(&(__7.z)) = tl::add2(*(float2*)(&(v__5.z)), *(float2*)(&(__8.z)));
        __6.x = (v__4.x/__7.x);
        __6.y = (v__4.y/__7.y);
        __6.z = (v__4.z/__7.z);
        __6.w = (v__4.w/__7.w);
      float4 v__8 = *(float4*)(Bias + (((int)threadIdx.x) * 4));
      *(float2*)(&(__5.x)) = tl::add2(*(float2*)(&(__6.x)), *(float2*)(&(v__8.x)));
      *(float2*)(&(__5.z)) = tl::add2(*(float2*)(&(__6.z)), *(float2*)(&(v__8.z)));
    *(float4*)(((float*)biased) + (((int)threadIdx.x) * 4)) = __5;
  }
  __syncthreads();
  if (((int)threadIdx.x) == 0) {
    den = 0x0p+0f/*0.000000e+00*/;
    for (int t = 0; t < 16; ++t) {
      best = -0x1.93e5939a08ceap+99f/*-1.000000e+30*/;
      bi = 0;
      for (int e = 0; e < 896; ++e) {
        if (best < ((float*)biased)[e]) {
          best = ((float*)biased)[e];
          bi = e;
        }
      }
      Idx[((((int)blockIdx.x) * 16) + t)] = bi;
      Wts[((((int)blockIdx.x) * 16) + t)] = ((float*)scores)[bi];
      ((float*)biased)[bi] = -0x1.93e5939a08ceap+99f/*-1.000000e+30*/;
      den = (den + ((float*)scores)[bi]);
    }
    for (int t_1 = 0; t_1 < 16; ++t_1) {
      Wts[((((int)blockIdx.x) * 16) + t_1)] = ((Wts[((((int)blockIdx.x) * 16) + t_1)] / (den + 0x1.79ca10c924223p-67f/*1.000000e-20*/)) * ((float)Rs[0]));
    }
  }
}


extern "C" __global__ void k3_router_topk_b1_e224_topk16_kernel(const float* __restrict__ Bias, int* __restrict__ Idx, const bfloat16_t* __restrict__ Rs, const float* __restrict__ S, float* __restrict__ Wts);
extern "C" __global__ void __launch_bounds__(256, 1) k3_router_topk_b1_e224_topk16_kernel(const float* __restrict__ Bias, int* __restrict__ Idx, const bfloat16_t* __restrict__ Rs, const float* __restrict__ S, float* __restrict__ Wts) {
  extern __shared__ __align__(1024) uchar buf_dyn_shmem[];
  void* scores = ((void*)((char*)buf_dyn_shmem + 0));
  void* biased = ((void*)((char*)buf_dyn_shmem + 896));
  float den = 0x0p+0f/*0.000000e+00*/;
  float best = 0x0p+0f/*0.000000e+00*/;
  int bi = 0;
  if (((int)threadIdx.x) < 224) {
    ((float*)scores)[((int)threadIdx.x)] = (0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - S[((int)threadIdx.x)]))));
    ((float*)biased)[((int)threadIdx.x)] = ((0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - S[((int)threadIdx.x)])))) + Bias[((int)threadIdx.x)]);
  }
  __syncthreads();
  if (((int)threadIdx.x) == 0) {
    den = 0x0p+0f/*0.000000e+00*/;
    for (int t = 0; t < 16; ++t) {
      best = -0x1.93e5939a08ceap+99f/*-1.000000e+30*/;
      bi = 0;
      for (int e = 0; e < 224; ++e) {
        if (best < ((float*)biased)[e]) {
          best = ((float*)biased)[e];
          bi = e;
        }
      }
      Idx[t] = bi;
      Wts[t] = ((float*)scores)[bi];
      ((float*)biased)[bi] = -0x1.93e5939a08ceap+99f/*-1.000000e+30*/;
      den = (den + ((float*)scores)[bi]);
    }
    for (int t_1 = 0; t_1 < 16; ++t_1) {
      Wts[t_1] = ((Wts[t_1] / (den + 0x1.79ca10c924223p-67f/*1.000000e-20*/)) * ((float)Rs[0]));
    }
  }
}


extern "C" __global__ void k3_router_topk_b2_e224_topk16_kernel(const float* __restrict__ Bias, int* __restrict__ Idx, const bfloat16_t* __restrict__ Rs, const float* __restrict__ S, float* __restrict__ Wts);
extern "C" __global__ void __launch_bounds__(256, 1) k3_router_topk_b2_e224_topk16_kernel(const float* __restrict__ Bias, int* __restrict__ Idx, const bfloat16_t* __restrict__ Rs, const float* __restrict__ S, float* __restrict__ Wts) {
  extern __shared__ __align__(1024) uchar buf_dyn_shmem[];
  void* scores = ((void*)((char*)buf_dyn_shmem + 0));
  void* biased = ((void*)((char*)buf_dyn_shmem + 896));
  float den = 0x0p+0f/*0.000000e+00*/;
  float best = 0x0p+0f/*0.000000e+00*/;
  int bi = 0;
  if (((int)threadIdx.x) < 224) {
    ((float*)scores)[((int)threadIdx.x)] = (0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - S[((((int)blockIdx.x) * 224) + ((int)threadIdx.x))]))));
    ((float*)biased)[((int)threadIdx.x)] = ((0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - S[((((int)blockIdx.x) * 224) + ((int)threadIdx.x))])))) + Bias[((int)threadIdx.x)]);
  }
  __syncthreads();
  if (((int)threadIdx.x) == 0) {
    den = 0x0p+0f/*0.000000e+00*/;
    for (int t = 0; t < 16; ++t) {
      best = -0x1.93e5939a08ceap+99f/*-1.000000e+30*/;
      bi = 0;
      for (int e = 0; e < 224; ++e) {
        if (best < ((float*)biased)[e]) {
          best = ((float*)biased)[e];
          bi = e;
        }
      }
      Idx[((((int)blockIdx.x) * 16) + t)] = bi;
      Wts[((((int)blockIdx.x) * 16) + t)] = ((float*)scores)[bi];
      ((float*)biased)[bi] = -0x1.93e5939a08ceap+99f/*-1.000000e+30*/;
      den = (den + ((float*)scores)[bi]);
    }
    for (int t_1 = 0; t_1 < 16; ++t_1) {
      Wts[((((int)blockIdx.x) * 16) + t_1)] = ((Wts[((((int)blockIdx.x) * 16) + t_1)] / (den + 0x1.79ca10c924223p-67f/*1.000000e-20*/)) * ((float)Rs[0]));
    }
  }
}


extern "C" __global__ void k3_router_topk_b4_e224_topk16_kernel(const float* __restrict__ Bias, int* __restrict__ Idx, const bfloat16_t* __restrict__ Rs, const float* __restrict__ S, float* __restrict__ Wts);
extern "C" __global__ void __launch_bounds__(256, 1) k3_router_topk_b4_e224_topk16_kernel(const float* __restrict__ Bias, int* __restrict__ Idx, const bfloat16_t* __restrict__ Rs, const float* __restrict__ S, float* __restrict__ Wts) {
  extern __shared__ __align__(1024) uchar buf_dyn_shmem[];
  void* scores = ((void*)((char*)buf_dyn_shmem + 0));
  void* biased = ((void*)((char*)buf_dyn_shmem + 896));
  float den = 0x0p+0f/*0.000000e+00*/;
  float best = 0x0p+0f/*0.000000e+00*/;
  int bi = 0;
  if (((int)threadIdx.x) < 224) {
    ((float*)scores)[((int)threadIdx.x)] = (0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - S[((((int)blockIdx.x) * 224) + ((int)threadIdx.x))]))));
    ((float*)biased)[((int)threadIdx.x)] = ((0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - S[((((int)blockIdx.x) * 224) + ((int)threadIdx.x))])))) + Bias[((int)threadIdx.x)]);
  }
  __syncthreads();
  if (((int)threadIdx.x) == 0) {
    den = 0x0p+0f/*0.000000e+00*/;
    for (int t = 0; t < 16; ++t) {
      best = -0x1.93e5939a08ceap+99f/*-1.000000e+30*/;
      bi = 0;
      for (int e = 0; e < 224; ++e) {
        if (best < ((float*)biased)[e]) {
          best = ((float*)biased)[e];
          bi = e;
        }
      }
      Idx[((((int)blockIdx.x) * 16) + t)] = bi;
      Wts[((((int)blockIdx.x) * 16) + t)] = ((float*)scores)[bi];
      ((float*)biased)[bi] = -0x1.93e5939a08ceap+99f/*-1.000000e+30*/;
      den = (den + ((float*)scores)[bi]);
    }
    for (int t_1 = 0; t_1 < 16; ++t_1) {
      Wts[((((int)blockIdx.x) * 16) + t_1)] = ((Wts[((((int)blockIdx.x) * 16) + t_1)] / (den + 0x1.79ca10c924223p-67f/*1.000000e-20*/)) * ((float)Rs[0]));
    }
  }
}


extern "C" __global__ void k3_router_topk_b8_e224_topk16_kernel(const float* __restrict__ Bias, int* __restrict__ Idx, const bfloat16_t* __restrict__ Rs, const float* __restrict__ S, float* __restrict__ Wts);
extern "C" __global__ void __launch_bounds__(256, 1) k3_router_topk_b8_e224_topk16_kernel(const float* __restrict__ Bias, int* __restrict__ Idx, const bfloat16_t* __restrict__ Rs, const float* __restrict__ S, float* __restrict__ Wts) {
  extern __shared__ __align__(1024) uchar buf_dyn_shmem[];
  void* scores = ((void*)((char*)buf_dyn_shmem + 0));
  void* biased = ((void*)((char*)buf_dyn_shmem + 896));
  float den = 0x0p+0f/*0.000000e+00*/;
  float best = 0x0p+0f/*0.000000e+00*/;
  int bi = 0;
  if (((int)threadIdx.x) < 224) {
    ((float*)scores)[((int)threadIdx.x)] = (0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - S[((((int)blockIdx.x) * 224) + ((int)threadIdx.x))]))));
    ((float*)biased)[((int)threadIdx.x)] = ((0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - S[((((int)blockIdx.x) * 224) + ((int)threadIdx.x))])))) + Bias[((int)threadIdx.x)]);
  }
  __syncthreads();
  if (((int)threadIdx.x) == 0) {
    den = 0x0p+0f/*0.000000e+00*/;
    for (int t = 0; t < 16; ++t) {
      best = -0x1.93e5939a08ceap+99f/*-1.000000e+30*/;
      bi = 0;
      for (int e = 0; e < 224; ++e) {
        if (best < ((float*)biased)[e]) {
          best = ((float*)biased)[e];
          bi = e;
        }
      }
      Idx[((((int)blockIdx.x) * 16) + t)] = bi;
      Wts[((((int)blockIdx.x) * 16) + t)] = ((float*)scores)[bi];
      ((float*)biased)[bi] = -0x1.93e5939a08ceap+99f/*-1.000000e+30*/;
      den = (den + ((float*)scores)[bi]);
    }
    for (int t_1 = 0; t_1 < 16; ++t_1) {
      Wts[((((int)blockIdx.x) * 16) + t_1)] = ((Wts[((((int)blockIdx.x) * 16) + t_1)] / (den + 0x1.79ca10c924223p-67f/*1.000000e-20*/)) * ((float)Rs[0]));
    }
  }
}


extern "C" __global__ void k3_router_topk_b16_e224_topk16_kernel(const float* __restrict__ Bias, int* __restrict__ Idx, const bfloat16_t* __restrict__ Rs, const float* __restrict__ S, float* __restrict__ Wts);
extern "C" __global__ void __launch_bounds__(256, 1) k3_router_topk_b16_e224_topk16_kernel(const float* __restrict__ Bias, int* __restrict__ Idx, const bfloat16_t* __restrict__ Rs, const float* __restrict__ S, float* __restrict__ Wts) {
  extern __shared__ __align__(1024) uchar buf_dyn_shmem[];
  void* scores = ((void*)((char*)buf_dyn_shmem + 0));
  void* biased = ((void*)((char*)buf_dyn_shmem + 896));
  float den = 0x0p+0f/*0.000000e+00*/;
  float best = 0x0p+0f/*0.000000e+00*/;
  int bi = 0;
  if (((int)threadIdx.x) < 224) {
    ((float*)scores)[((int)threadIdx.x)] = (0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - S[((((int)blockIdx.x) * 224) + ((int)threadIdx.x))]))));
    ((float*)biased)[((int)threadIdx.x)] = ((0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - S[((((int)blockIdx.x) * 224) + ((int)threadIdx.x))])))) + Bias[((int)threadIdx.x)]);
  }
  __syncthreads();
  if (((int)threadIdx.x) == 0) {
    den = 0x0p+0f/*0.000000e+00*/;
    for (int t = 0; t < 16; ++t) {
      best = -0x1.93e5939a08ceap+99f/*-1.000000e+30*/;
      bi = 0;
      for (int e = 0; e < 224; ++e) {
        if (best < ((float*)biased)[e]) {
          best = ((float*)biased)[e];
          bi = e;
        }
      }
      Idx[((((int)blockIdx.x) * 16) + t)] = bi;
      Wts[((((int)blockIdx.x) * 16) + t)] = ((float*)scores)[bi];
      ((float*)biased)[bi] = -0x1.93e5939a08ceap+99f/*-1.000000e+30*/;
      den = (den + ((float*)scores)[bi]);
    }
    for (int t_1 = 0; t_1 < 16; ++t_1) {
      Wts[((((int)blockIdx.x) * 16) + t_1)] = ((Wts[((((int)blockIdx.x) * 16) + t_1)] / (den + 0x1.79ca10c924223p-67f/*1.000000e-20*/)) * ((float)Rs[0]));
    }
  }
}


extern "C" __global__ void k3_router_topk_b32_e224_topk16_kernel(const float* __restrict__ Bias, int* __restrict__ Idx, const bfloat16_t* __restrict__ Rs, const float* __restrict__ S, float* __restrict__ Wts);
extern "C" __global__ void __launch_bounds__(256, 1) k3_router_topk_b32_e224_topk16_kernel(const float* __restrict__ Bias, int* __restrict__ Idx, const bfloat16_t* __restrict__ Rs, const float* __restrict__ S, float* __restrict__ Wts) {
  extern __shared__ __align__(1024) uchar buf_dyn_shmem[];
  void* scores = ((void*)((char*)buf_dyn_shmem + 0));
  void* biased = ((void*)((char*)buf_dyn_shmem + 896));
  float den = 0x0p+0f/*0.000000e+00*/;
  float best = 0x0p+0f/*0.000000e+00*/;
  int bi = 0;
  if (((int)threadIdx.x) < 224) {
    ((float*)scores)[((int)threadIdx.x)] = (0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - S[((((int)blockIdx.x) * 224) + ((int)threadIdx.x))]))));
    ((float*)biased)[((int)threadIdx.x)] = ((0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - S[((((int)blockIdx.x) * 224) + ((int)threadIdx.x))])))) + Bias[((int)threadIdx.x)]);
  }
  __syncthreads();
  if (((int)threadIdx.x) == 0) {
    den = 0x0p+0f/*0.000000e+00*/;
    for (int t = 0; t < 16; ++t) {
      best = -0x1.93e5939a08ceap+99f/*-1.000000e+30*/;
      bi = 0;
      for (int e = 0; e < 224; ++e) {
        if (best < ((float*)biased)[e]) {
          best = ((float*)biased)[e];
          bi = e;
        }
      }
      Idx[((((int)blockIdx.x) * 16) + t)] = bi;
      Wts[((((int)blockIdx.x) * 16) + t)] = ((float*)scores)[bi];
      ((float*)biased)[bi] = -0x1.93e5939a08ceap+99f/*-1.000000e+30*/;
      den = (den + ((float*)scores)[bi]);
    }
    for (int t_1 = 0; t_1 < 16; ++t_1) {
      Wts[((((int)blockIdx.x) * 16) + t_1)] = ((Wts[((((int)blockIdx.x) * 16) + t_1)] / (den + 0x1.79ca10c924223p-67f/*1.000000e-20*/)) * ((float)Rs[0]));
    }
  }
}


extern "C" __global__ void k3_router_topk_b48_e224_topk16_kernel(const float* __restrict__ Bias, int* __restrict__ Idx, const bfloat16_t* __restrict__ Rs, const float* __restrict__ S, float* __restrict__ Wts);
extern "C" __global__ void __launch_bounds__(256, 1) k3_router_topk_b48_e224_topk16_kernel(const float* __restrict__ Bias, int* __restrict__ Idx, const bfloat16_t* __restrict__ Rs, const float* __restrict__ S, float* __restrict__ Wts) {
  extern __shared__ __align__(1024) uchar buf_dyn_shmem[];
  void* scores = ((void*)((char*)buf_dyn_shmem + 0));
  void* biased = ((void*)((char*)buf_dyn_shmem + 896));
  float den = 0x0p+0f/*0.000000e+00*/;
  float best = 0x0p+0f/*0.000000e+00*/;
  int bi = 0;
  if (((int)threadIdx.x) < 224) {
    ((float*)scores)[((int)threadIdx.x)] = (0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - S[((((int)blockIdx.x) * 224) + ((int)threadIdx.x))]))));
    ((float*)biased)[((int)threadIdx.x)] = ((0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - S[((((int)blockIdx.x) * 224) + ((int)threadIdx.x))])))) + Bias[((int)threadIdx.x)]);
  }
  __syncthreads();
  if (((int)threadIdx.x) == 0) {
    den = 0x0p+0f/*0.000000e+00*/;
    for (int t = 0; t < 16; ++t) {
      best = -0x1.93e5939a08ceap+99f/*-1.000000e+30*/;
      bi = 0;
      for (int e = 0; e < 224; ++e) {
        if (best < ((float*)biased)[e]) {
          best = ((float*)biased)[e];
          bi = e;
        }
      }
      Idx[((((int)blockIdx.x) * 16) + t)] = bi;
      Wts[((((int)blockIdx.x) * 16) + t)] = ((float*)scores)[bi];
      ((float*)biased)[bi] = -0x1.93e5939a08ceap+99f/*-1.000000e+30*/;
      den = (den + ((float*)scores)[bi]);
    }
    for (int t_1 = 0; t_1 < 16; ++t_1) {
      Wts[((((int)blockIdx.x) * 16) + t_1)] = ((Wts[((((int)blockIdx.x) * 16) + t_1)] / (den + 0x1.79ca10c924223p-67f/*1.000000e-20*/)) * ((float)Rs[0]));
    }
  }
}


extern "C" __global__ void k3_router_topk_b64_e224_topk16_kernel(const float* __restrict__ Bias, int* __restrict__ Idx, const bfloat16_t* __restrict__ Rs, const float* __restrict__ S, float* __restrict__ Wts);
extern "C" __global__ void __launch_bounds__(256, 1) k3_router_topk_b64_e224_topk16_kernel(const float* __restrict__ Bias, int* __restrict__ Idx, const bfloat16_t* __restrict__ Rs, const float* __restrict__ S, float* __restrict__ Wts) {
  extern __shared__ __align__(1024) uchar buf_dyn_shmem[];
  void* scores = ((void*)((char*)buf_dyn_shmem + 0));
  void* biased = ((void*)((char*)buf_dyn_shmem + 896));
  float den = 0x0p+0f/*0.000000e+00*/;
  float best = 0x0p+0f/*0.000000e+00*/;
  int bi = 0;
  if (((int)threadIdx.x) < 224) {
    ((float*)scores)[((int)threadIdx.x)] = (0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - S[((((int)blockIdx.x) * 224) + ((int)threadIdx.x))]))));
    ((float*)biased)[((int)threadIdx.x)] = ((0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - S[((((int)blockIdx.x) * 224) + ((int)threadIdx.x))])))) + Bias[((int)threadIdx.x)]);
  }
  __syncthreads();
  if (((int)threadIdx.x) == 0) {
    den = 0x0p+0f/*0.000000e+00*/;
    for (int t = 0; t < 16; ++t) {
      best = -0x1.93e5939a08ceap+99f/*-1.000000e+30*/;
      bi = 0;
      for (int e = 0; e < 224; ++e) {
        if (best < ((float*)biased)[e]) {
          best = ((float*)biased)[e];
          bi = e;
        }
      }
      Idx[((((int)blockIdx.x) * 16) + t)] = bi;
      Wts[((((int)blockIdx.x) * 16) + t)] = ((float*)scores)[bi];
      ((float*)biased)[bi] = -0x1.93e5939a08ceap+99f/*-1.000000e+30*/;
      den = (den + ((float*)scores)[bi]);
    }
    for (int t_1 = 0; t_1 < 16; ++t_1) {
      Wts[((((int)blockIdx.x) * 16) + t_1)] = ((Wts[((((int)blockIdx.x) * 16) + t_1)] / (den + 0x1.79ca10c924223p-67f/*1.000000e-20*/)) * ((float)Rs[0]));
    }
  }
}


extern "C" __global__ void k3_router_topk_b96_e224_topk16_kernel(const float* __restrict__ Bias, int* __restrict__ Idx, const bfloat16_t* __restrict__ Rs, const float* __restrict__ S, float* __restrict__ Wts);
extern "C" __global__ void __launch_bounds__(256, 1) k3_router_topk_b96_e224_topk16_kernel(const float* __restrict__ Bias, int* __restrict__ Idx, const bfloat16_t* __restrict__ Rs, const float* __restrict__ S, float* __restrict__ Wts) {
  extern __shared__ __align__(1024) uchar buf_dyn_shmem[];
  void* scores = ((void*)((char*)buf_dyn_shmem + 0));
  void* biased = ((void*)((char*)buf_dyn_shmem + 896));
  float den = 0x0p+0f/*0.000000e+00*/;
  float best = 0x0p+0f/*0.000000e+00*/;
  int bi = 0;
  if (((int)threadIdx.x) < 224) {
    ((float*)scores)[((int)threadIdx.x)] = (0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - S[((((int)blockIdx.x) * 224) + ((int)threadIdx.x))]))));
    ((float*)biased)[((int)threadIdx.x)] = ((0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - S[((((int)blockIdx.x) * 224) + ((int)threadIdx.x))])))) + Bias[((int)threadIdx.x)]);
  }
  __syncthreads();
  if (((int)threadIdx.x) == 0) {
    den = 0x0p+0f/*0.000000e+00*/;
    for (int t = 0; t < 16; ++t) {
      best = -0x1.93e5939a08ceap+99f/*-1.000000e+30*/;
      bi = 0;
      for (int e = 0; e < 224; ++e) {
        if (best < ((float*)biased)[e]) {
          best = ((float*)biased)[e];
          bi = e;
        }
      }
      Idx[((((int)blockIdx.x) * 16) + t)] = bi;
      Wts[((((int)blockIdx.x) * 16) + t)] = ((float*)scores)[bi];
      ((float*)biased)[bi] = -0x1.93e5939a08ceap+99f/*-1.000000e+30*/;
      den = (den + ((float*)scores)[bi]);
    }
    for (int t_1 = 0; t_1 < 16; ++t_1) {
      Wts[((((int)blockIdx.x) * 16) + t_1)] = ((Wts[((((int)blockIdx.x) * 16) + t_1)] / (den + 0x1.79ca10c924223p-67f/*1.000000e-20*/)) * ((float)Rs[0]));
    }
  }
}


extern "C" __global__ void k3_router_topk_b128_e224_topk16_kernel(const float* __restrict__ Bias, int* __restrict__ Idx, const bfloat16_t* __restrict__ Rs, const float* __restrict__ S, float* __restrict__ Wts);
extern "C" __global__ void __launch_bounds__(256, 1) k3_router_topk_b128_e224_topk16_kernel(const float* __restrict__ Bias, int* __restrict__ Idx, const bfloat16_t* __restrict__ Rs, const float* __restrict__ S, float* __restrict__ Wts) {
  extern __shared__ __align__(1024) uchar buf_dyn_shmem[];
  void* scores = ((void*)((char*)buf_dyn_shmem + 0));
  void* biased = ((void*)((char*)buf_dyn_shmem + 896));
  float den = 0x0p+0f/*0.000000e+00*/;
  float best = 0x0p+0f/*0.000000e+00*/;
  int bi = 0;
  if (((int)threadIdx.x) < 224) {
    ((float*)scores)[((int)threadIdx.x)] = (0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - S[((((int)blockIdx.x) * 224) + ((int)threadIdx.x))]))));
    ((float*)biased)[((int)threadIdx.x)] = ((0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - S[((((int)blockIdx.x) * 224) + ((int)threadIdx.x))])))) + Bias[((int)threadIdx.x)]);
  }
  __syncthreads();
  if (((int)threadIdx.x) == 0) {
    den = 0x0p+0f/*0.000000e+00*/;
    for (int t = 0; t < 16; ++t) {
      best = -0x1.93e5939a08ceap+99f/*-1.000000e+30*/;
      bi = 0;
      for (int e = 0; e < 224; ++e) {
        if (best < ((float*)biased)[e]) {
          best = ((float*)biased)[e];
          bi = e;
        }
      }
      Idx[((((int)blockIdx.x) * 16) + t)] = bi;
      Wts[((((int)blockIdx.x) * 16) + t)] = ((float*)scores)[bi];
      ((float*)biased)[bi] = -0x1.93e5939a08ceap+99f/*-1.000000e+30*/;
      den = (den + ((float*)scores)[bi]);
    }
    for (int t_1 = 0; t_1 < 16; ++t_1) {
      Wts[((((int)blockIdx.x) * 16) + t_1)] = ((Wts[((((int)blockIdx.x) * 16) + t_1)] / (den + 0x1.79ca10c924223p-67f/*1.000000e-20*/)) * ((float)Rs[0]));
    }
  }
}



// Sigmoid router plus biased top-k over already-merged f32 score rows,
// one row per block. The selection is a serial O(topk * num_experts)
// scan by thread 0 with a lowest-index tie-break; the weights are
// gathered from the un-biased scores, the denominator carries the
// +1e-20 guard, and the result is scaled by the bf16 routed scale Rs.
extern "C" int k3_router_topk_batched(
    const float* S,
    const float* Bias,
    const void* Rs,
    int* Idx,
    float* Wts,
    int b,
    int num_experts,
    int topk,
    cudaStream_t stream) {
  if (b == 1 && num_experts == 896 && topk == 16) {
    k3_router_topk_b1_e896_topk16_kernel<<<dim3(1, 1, 1), 256, 7168, stream>>>(
        Bias,
        Idx,
        reinterpret_cast<const bfloat16_t*>(Rs),
        S,
        Wts);
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 2 && num_experts == 896 && topk == 16) {
    k3_router_topk_b2_e896_topk16_kernel<<<dim3(2, 1, 1), 256, 7168, stream>>>(
        Bias,
        Idx,
        reinterpret_cast<const bfloat16_t*>(Rs),
        S,
        Wts);
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 4 && num_experts == 896 && topk == 16) {
    k3_router_topk_b4_e896_topk16_kernel<<<dim3(4, 1, 1), 256, 7168, stream>>>(
        Bias,
        Idx,
        reinterpret_cast<const bfloat16_t*>(Rs),
        S,
        Wts);
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 8 && num_experts == 896 && topk == 16) {
    k3_router_topk_b8_e896_topk16_kernel<<<dim3(8, 1, 1), 256, 7168, stream>>>(
        Bias,
        Idx,
        reinterpret_cast<const bfloat16_t*>(Rs),
        S,
        Wts);
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 16 && num_experts == 896 && topk == 16) {
    k3_router_topk_b16_e896_topk16_kernel<<<dim3(16, 1, 1), 256, 7168, stream>>>(
        Bias,
        Idx,
        reinterpret_cast<const bfloat16_t*>(Rs),
        S,
        Wts);
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 32 && num_experts == 896 && topk == 16) {
    k3_router_topk_b32_e896_topk16_kernel<<<dim3(32, 1, 1), 256, 7168, stream>>>(
        Bias,
        Idx,
        reinterpret_cast<const bfloat16_t*>(Rs),
        S,
        Wts);
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 48 && num_experts == 896 && topk == 16) {
    k3_router_topk_b48_e896_topk16_kernel<<<dim3(48, 1, 1), 256, 7168, stream>>>(
        Bias,
        Idx,
        reinterpret_cast<const bfloat16_t*>(Rs),
        S,
        Wts);
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 64 && num_experts == 896 && topk == 16) {
    k3_router_topk_b64_e896_topk16_kernel<<<dim3(64, 1, 1), 256, 7168, stream>>>(
        Bias,
        Idx,
        reinterpret_cast<const bfloat16_t*>(Rs),
        S,
        Wts);
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 96 && num_experts == 896 && topk == 16) {
    k3_router_topk_b96_e896_topk16_kernel<<<dim3(96, 1, 1), 256, 7168, stream>>>(
        Bias,
        Idx,
        reinterpret_cast<const bfloat16_t*>(Rs),
        S,
        Wts);
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 128 && num_experts == 896 && topk == 16) {
    k3_router_topk_b128_e896_topk16_kernel<<<dim3(128, 1, 1), 256, 7168, stream>>>(
        Bias,
        Idx,
        reinterpret_cast<const bfloat16_t*>(Rs),
        S,
        Wts);
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 1 && num_experts == 224 && topk == 16) {
    k3_router_topk_b1_e224_topk16_kernel<<<dim3(1, 1, 1), 256, 1792, stream>>>(
        Bias,
        Idx,
        reinterpret_cast<const bfloat16_t*>(Rs),
        S,
        Wts);
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 2 && num_experts == 224 && topk == 16) {
    k3_router_topk_b2_e224_topk16_kernel<<<dim3(2, 1, 1), 256, 1792, stream>>>(
        Bias,
        Idx,
        reinterpret_cast<const bfloat16_t*>(Rs),
        S,
        Wts);
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 4 && num_experts == 224 && topk == 16) {
    k3_router_topk_b4_e224_topk16_kernel<<<dim3(4, 1, 1), 256, 1792, stream>>>(
        Bias,
        Idx,
        reinterpret_cast<const bfloat16_t*>(Rs),
        S,
        Wts);
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 8 && num_experts == 224 && topk == 16) {
    k3_router_topk_b8_e224_topk16_kernel<<<dim3(8, 1, 1), 256, 1792, stream>>>(
        Bias,
        Idx,
        reinterpret_cast<const bfloat16_t*>(Rs),
        S,
        Wts);
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 16 && num_experts == 224 && topk == 16) {
    k3_router_topk_b16_e224_topk16_kernel<<<dim3(16, 1, 1), 256, 1792, stream>>>(
        Bias,
        Idx,
        reinterpret_cast<const bfloat16_t*>(Rs),
        S,
        Wts);
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 32 && num_experts == 224 && topk == 16) {
    k3_router_topk_b32_e224_topk16_kernel<<<dim3(32, 1, 1), 256, 1792, stream>>>(
        Bias,
        Idx,
        reinterpret_cast<const bfloat16_t*>(Rs),
        S,
        Wts);
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 48 && num_experts == 224 && topk == 16) {
    k3_router_topk_b48_e224_topk16_kernel<<<dim3(48, 1, 1), 256, 1792, stream>>>(
        Bias,
        Idx,
        reinterpret_cast<const bfloat16_t*>(Rs),
        S,
        Wts);
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 64 && num_experts == 224 && topk == 16) {
    k3_router_topk_b64_e224_topk16_kernel<<<dim3(64, 1, 1), 256, 1792, stream>>>(
        Bias,
        Idx,
        reinterpret_cast<const bfloat16_t*>(Rs),
        S,
        Wts);
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 96 && num_experts == 224 && topk == 16) {
    k3_router_topk_b96_e224_topk16_kernel<<<dim3(96, 1, 1), 256, 1792, stream>>>(
        Bias,
        Idx,
        reinterpret_cast<const bfloat16_t*>(Rs),
        S,
        Wts);
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 128 && num_experts == 224 && topk == 16) {
    k3_router_topk_b128_e224_topk16_kernel<<<dim3(128, 1, 1), 256, 1792, stream>>>(
        Bias,
        Idx,
        reinterpret_cast<const bfloat16_t*>(Rs),
        S,
        Wts);
    return static_cast<int>(cudaGetLastError());
  }
  return static_cast<int>(cudaErrorInvalidValue);
}
