// Generated by pegainfer-k3/kernels/generate.py -- do not edit.
#include <cuda_runtime.h>

#if defined(_MSC_VER) && !defined(__clang__) && _MSC_VER < 1940
#define _tl_orig_alignas alignas
#define alignas(N) _tl_orig_alignas((N) <= 64 ? (N) : 64)
#include <cuda.h>
#undef alignas
#define alignas _tl_orig_alignas
#endif
#include <tl_templates/cuda/reduce.h>
#include <tl_templates/cuda/scan.h>
#include <tl_templates/cuda/ldsm.h>
#include <tl_templates/cuda/threadblock_swizzle.h>
#define debug_print_msg k3_situ_batched_debug_print_msg
#define debug_print_buffer_value k3_situ_batched_debug_print_buffer_value
#include <tl_templates/cuda/debug.h>
#undef debug_print_msg
#undef debug_print_buffer_value
#ifdef ENABLE_BF16
#include <tl_templates/cuda/cuda_bf16_fallbacks.cuh>
#endif

extern "C" __global__ void k3_situ_b1_n6144_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ U);
extern "C" __global__ void __launch_bounds__(256, 1) k3_situ_b1_n6144_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ U) {
  float g = ((float)G[((((int)blockIdx.y) * 256) + ((int)threadIdx.x))]);
  float u = ((float)U[((((int)blockIdx.y) * 256) + ((int)threadIdx.x))]);
  O[((((int)blockIdx.y) * 256) + ((int)threadIdx.x))] = ((bfloat16_t)(((0x1p+2f/*4.000000e+00*/ * tanhf((g / 0x1p+2f/*4.000000e+00*/))) * (0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - g))))) * (0x1.9p+4f/*2.500000e+01*/ * tanhf((u / 0x1.9p+4f/*2.500000e+01*/)))));
}


extern "C" __global__ void k3_situ_b2_n6144_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ U);
extern "C" __global__ void __launch_bounds__(256, 1) k3_situ_b2_n6144_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ U) {
  float g = ((float)G[(((((int)blockIdx.x) * 6144) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]);
  float u = ((float)U[(((((int)blockIdx.x) * 6144) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]);
  O[(((((int)blockIdx.x) * 6144) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] = ((bfloat16_t)(((0x1p+2f/*4.000000e+00*/ * tanhf((g / 0x1p+2f/*4.000000e+00*/))) * (0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - g))))) * (0x1.9p+4f/*2.500000e+01*/ * tanhf((u / 0x1.9p+4f/*2.500000e+01*/)))));
}


extern "C" __global__ void k3_situ_b4_n6144_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ U);
extern "C" __global__ void __launch_bounds__(256, 1) k3_situ_b4_n6144_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ U) {
  float g = ((float)G[(((((int)blockIdx.x) * 6144) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]);
  float u = ((float)U[(((((int)blockIdx.x) * 6144) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]);
  O[(((((int)blockIdx.x) * 6144) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] = ((bfloat16_t)(((0x1p+2f/*4.000000e+00*/ * tanhf((g / 0x1p+2f/*4.000000e+00*/))) * (0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - g))))) * (0x1.9p+4f/*2.500000e+01*/ * tanhf((u / 0x1.9p+4f/*2.500000e+01*/)))));
}


extern "C" __global__ void k3_situ_b8_n6144_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ U);
extern "C" __global__ void __launch_bounds__(256, 1) k3_situ_b8_n6144_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ U) {
  float g = ((float)G[(((((int)blockIdx.x) * 6144) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]);
  float u = ((float)U[(((((int)blockIdx.x) * 6144) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]);
  O[(((((int)blockIdx.x) * 6144) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] = ((bfloat16_t)(((0x1p+2f/*4.000000e+00*/ * tanhf((g / 0x1p+2f/*4.000000e+00*/))) * (0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - g))))) * (0x1.9p+4f/*2.500000e+01*/ * tanhf((u / 0x1.9p+4f/*2.500000e+01*/)))));
}


extern "C" __global__ void k3_situ_b16_n6144_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ U);
extern "C" __global__ void __launch_bounds__(256, 1) k3_situ_b16_n6144_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ U) {
  float g = ((float)G[(((((int)blockIdx.x) * 6144) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]);
  float u = ((float)U[(((((int)blockIdx.x) * 6144) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]);
  O[(((((int)blockIdx.x) * 6144) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] = ((bfloat16_t)(((0x1p+2f/*4.000000e+00*/ * tanhf((g / 0x1p+2f/*4.000000e+00*/))) * (0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - g))))) * (0x1.9p+4f/*2.500000e+01*/ * tanhf((u / 0x1.9p+4f/*2.500000e+01*/)))));
}


extern "C" __global__ void k3_situ_b32_n6144_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ U);
extern "C" __global__ void __launch_bounds__(256, 1) k3_situ_b32_n6144_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ U) {
  float g = ((float)G[(((((int)blockIdx.x) * 6144) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]);
  float u = ((float)U[(((((int)blockIdx.x) * 6144) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]);
  O[(((((int)blockIdx.x) * 6144) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] = ((bfloat16_t)(((0x1p+2f/*4.000000e+00*/ * tanhf((g / 0x1p+2f/*4.000000e+00*/))) * (0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - g))))) * (0x1.9p+4f/*2.500000e+01*/ * tanhf((u / 0x1.9p+4f/*2.500000e+01*/)))));
}


extern "C" __global__ void k3_situ_b48_n6144_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ U);
extern "C" __global__ void __launch_bounds__(256, 1) k3_situ_b48_n6144_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ U) {
  float g = ((float)G[(((((int)blockIdx.x) * 6144) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]);
  float u = ((float)U[(((((int)blockIdx.x) * 6144) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]);
  O[(((((int)blockIdx.x) * 6144) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] = ((bfloat16_t)(((0x1p+2f/*4.000000e+00*/ * tanhf((g / 0x1p+2f/*4.000000e+00*/))) * (0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - g))))) * (0x1.9p+4f/*2.500000e+01*/ * tanhf((u / 0x1.9p+4f/*2.500000e+01*/)))));
}


extern "C" __global__ void k3_situ_b64_n6144_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ U);
extern "C" __global__ void __launch_bounds__(256, 1) k3_situ_b64_n6144_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ U) {
  float g = ((float)G[(((((int)blockIdx.x) * 6144) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]);
  float u = ((float)U[(((((int)blockIdx.x) * 6144) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]);
  O[(((((int)blockIdx.x) * 6144) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] = ((bfloat16_t)(((0x1p+2f/*4.000000e+00*/ * tanhf((g / 0x1p+2f/*4.000000e+00*/))) * (0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - g))))) * (0x1.9p+4f/*2.500000e+01*/ * tanhf((u / 0x1.9p+4f/*2.500000e+01*/)))));
}


extern "C" __global__ void k3_situ_b96_n6144_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ U);
extern "C" __global__ void __launch_bounds__(256, 1) k3_situ_b96_n6144_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ U) {
  float g = ((float)G[(((((int)blockIdx.x) * 6144) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]);
  float u = ((float)U[(((((int)blockIdx.x) * 6144) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]);
  O[(((((int)blockIdx.x) * 6144) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] = ((bfloat16_t)(((0x1p+2f/*4.000000e+00*/ * tanhf((g / 0x1p+2f/*4.000000e+00*/))) * (0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - g))))) * (0x1.9p+4f/*2.500000e+01*/ * tanhf((u / 0x1.9p+4f/*2.500000e+01*/)))));
}


extern "C" __global__ void k3_situ_b128_n6144_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ U);
extern "C" __global__ void __launch_bounds__(256, 1) k3_situ_b128_n6144_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ U) {
  float g = ((float)G[(((((int)blockIdx.x) * 6144) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]);
  float u = ((float)U[(((((int)blockIdx.x) * 6144) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]);
  O[(((((int)blockIdx.x) * 6144) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] = ((bfloat16_t)(((0x1p+2f/*4.000000e+00*/ * tanhf((g / 0x1p+2f/*4.000000e+00*/))) * (0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - g))))) * (0x1.9p+4f/*2.500000e+01*/ * tanhf((u / 0x1.9p+4f/*2.500000e+01*/)))));
}


extern "C" __global__ void k3_situ_b1_n33792_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ U);
extern "C" __global__ void __launch_bounds__(256, 1) k3_situ_b1_n33792_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ U) {
  float g = ((float)G[((((int)blockIdx.y) * 256) + ((int)threadIdx.x))]);
  float u = ((float)U[((((int)blockIdx.y) * 256) + ((int)threadIdx.x))]);
  O[((((int)blockIdx.y) * 256) + ((int)threadIdx.x))] = ((bfloat16_t)(((0x1p+2f/*4.000000e+00*/ * tanhf((g / 0x1p+2f/*4.000000e+00*/))) * (0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - g))))) * (0x1.9p+4f/*2.500000e+01*/ * tanhf((u / 0x1.9p+4f/*2.500000e+01*/)))));
}


extern "C" __global__ void k3_situ_b2_n33792_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ U);
extern "C" __global__ void __launch_bounds__(256, 1) k3_situ_b2_n33792_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ U) {
  float g = ((float)G[(((((int)blockIdx.x) * 33792) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]);
  float u = ((float)U[(((((int)blockIdx.x) * 33792) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]);
  O[(((((int)blockIdx.x) * 33792) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] = ((bfloat16_t)(((0x1p+2f/*4.000000e+00*/ * tanhf((g / 0x1p+2f/*4.000000e+00*/))) * (0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - g))))) * (0x1.9p+4f/*2.500000e+01*/ * tanhf((u / 0x1.9p+4f/*2.500000e+01*/)))));
}


extern "C" __global__ void k3_situ_b4_n33792_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ U);
extern "C" __global__ void __launch_bounds__(256, 1) k3_situ_b4_n33792_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ U) {
  float g = ((float)G[(((((int)blockIdx.x) * 33792) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]);
  float u = ((float)U[(((((int)blockIdx.x) * 33792) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]);
  O[(((((int)blockIdx.x) * 33792) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] = ((bfloat16_t)(((0x1p+2f/*4.000000e+00*/ * tanhf((g / 0x1p+2f/*4.000000e+00*/))) * (0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - g))))) * (0x1.9p+4f/*2.500000e+01*/ * tanhf((u / 0x1.9p+4f/*2.500000e+01*/)))));
}


extern "C" __global__ void k3_situ_b8_n33792_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ U);
extern "C" __global__ void __launch_bounds__(256, 1) k3_situ_b8_n33792_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ U) {
  float g = ((float)G[(((((int)blockIdx.x) * 33792) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]);
  float u = ((float)U[(((((int)blockIdx.x) * 33792) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]);
  O[(((((int)blockIdx.x) * 33792) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] = ((bfloat16_t)(((0x1p+2f/*4.000000e+00*/ * tanhf((g / 0x1p+2f/*4.000000e+00*/))) * (0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - g))))) * (0x1.9p+4f/*2.500000e+01*/ * tanhf((u / 0x1.9p+4f/*2.500000e+01*/)))));
}


extern "C" __global__ void k3_situ_b16_n33792_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ U);
extern "C" __global__ void __launch_bounds__(256, 1) k3_situ_b16_n33792_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ U) {
  float g = ((float)G[(((((int)blockIdx.x) * 33792) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]);
  float u = ((float)U[(((((int)blockIdx.x) * 33792) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]);
  O[(((((int)blockIdx.x) * 33792) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] = ((bfloat16_t)(((0x1p+2f/*4.000000e+00*/ * tanhf((g / 0x1p+2f/*4.000000e+00*/))) * (0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - g))))) * (0x1.9p+4f/*2.500000e+01*/ * tanhf((u / 0x1.9p+4f/*2.500000e+01*/)))));
}


extern "C" __global__ void k3_situ_b32_n33792_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ U);
extern "C" __global__ void __launch_bounds__(256, 1) k3_situ_b32_n33792_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ U) {
  float g = ((float)G[(((((int)blockIdx.x) * 33792) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]);
  float u = ((float)U[(((((int)blockIdx.x) * 33792) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]);
  O[(((((int)blockIdx.x) * 33792) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] = ((bfloat16_t)(((0x1p+2f/*4.000000e+00*/ * tanhf((g / 0x1p+2f/*4.000000e+00*/))) * (0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - g))))) * (0x1.9p+4f/*2.500000e+01*/ * tanhf((u / 0x1.9p+4f/*2.500000e+01*/)))));
}


extern "C" __global__ void k3_situ_b48_n33792_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ U);
extern "C" __global__ void __launch_bounds__(256, 1) k3_situ_b48_n33792_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ U) {
  float g = ((float)G[(((((int)blockIdx.x) * 33792) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]);
  float u = ((float)U[(((((int)blockIdx.x) * 33792) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]);
  O[(((((int)blockIdx.x) * 33792) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] = ((bfloat16_t)(((0x1p+2f/*4.000000e+00*/ * tanhf((g / 0x1p+2f/*4.000000e+00*/))) * (0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - g))))) * (0x1.9p+4f/*2.500000e+01*/ * tanhf((u / 0x1.9p+4f/*2.500000e+01*/)))));
}


extern "C" __global__ void k3_situ_b64_n33792_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ U);
extern "C" __global__ void __launch_bounds__(256, 1) k3_situ_b64_n33792_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ U) {
  float g = ((float)G[(((((int)blockIdx.x) * 33792) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]);
  float u = ((float)U[(((((int)blockIdx.x) * 33792) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]);
  O[(((((int)blockIdx.x) * 33792) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] = ((bfloat16_t)(((0x1p+2f/*4.000000e+00*/ * tanhf((g / 0x1p+2f/*4.000000e+00*/))) * (0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - g))))) * (0x1.9p+4f/*2.500000e+01*/ * tanhf((u / 0x1.9p+4f/*2.500000e+01*/)))));
}


extern "C" __global__ void k3_situ_b96_n33792_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ U);
extern "C" __global__ void __launch_bounds__(256, 1) k3_situ_b96_n33792_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ U) {
  float g = ((float)G[(((((int)blockIdx.x) * 33792) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]);
  float u = ((float)U[(((((int)blockIdx.x) * 33792) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]);
  O[(((((int)blockIdx.x) * 33792) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] = ((bfloat16_t)(((0x1p+2f/*4.000000e+00*/ * tanhf((g / 0x1p+2f/*4.000000e+00*/))) * (0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - g))))) * (0x1.9p+4f/*2.500000e+01*/ * tanhf((u / 0x1.9p+4f/*2.500000e+01*/)))));
}


extern "C" __global__ void k3_situ_b128_n33792_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ U);
extern "C" __global__ void __launch_bounds__(256, 1) k3_situ_b128_n33792_kernel(const bfloat16_t* __restrict__ G, bfloat16_t* __restrict__ O, const bfloat16_t* __restrict__ U) {
  float g = ((float)G[(((((int)blockIdx.x) * 33792) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]);
  float u = ((float)U[(((((int)blockIdx.x) * 33792) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))]);
  O[(((((int)blockIdx.x) * 33792) + (((int)blockIdx.y) * 256)) + ((int)threadIdx.x))] = ((bfloat16_t)(((0x1p+2f/*4.000000e+00*/ * tanhf((g / 0x1p+2f/*4.000000e+00*/))) * (0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - g))))) * (0x1.9p+4f/*2.500000e+01*/ * tanhf((u / 0x1.9p+4f/*2.500000e+01*/)))));
}



// 4*tanh(g/4)*sigmoid(g) * 25*tanh(u/25), computed in f32 and landed in
// bf16 once; the two betas are compiled in.
extern "C" int k3_situ_batched(
    const void* G,
    const void* U,
    void* O,
    int b,
    int n,
    cudaStream_t stream) {
  if (b == 1 && n == 6144) {
    k3_situ_b1_n6144_kernel<<<dim3(1, 24, 1), 256, 0, stream>>>(
        reinterpret_cast<const bfloat16_t*>(G),
        reinterpret_cast<bfloat16_t*>(O),
        reinterpret_cast<const bfloat16_t*>(U));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 2 && n == 6144) {
    k3_situ_b2_n6144_kernel<<<dim3(2, 24, 1), 256, 0, stream>>>(
        reinterpret_cast<const bfloat16_t*>(G),
        reinterpret_cast<bfloat16_t*>(O),
        reinterpret_cast<const bfloat16_t*>(U));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 4 && n == 6144) {
    k3_situ_b4_n6144_kernel<<<dim3(4, 24, 1), 256, 0, stream>>>(
        reinterpret_cast<const bfloat16_t*>(G),
        reinterpret_cast<bfloat16_t*>(O),
        reinterpret_cast<const bfloat16_t*>(U));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 8 && n == 6144) {
    k3_situ_b8_n6144_kernel<<<dim3(8, 24, 1), 256, 0, stream>>>(
        reinterpret_cast<const bfloat16_t*>(G),
        reinterpret_cast<bfloat16_t*>(O),
        reinterpret_cast<const bfloat16_t*>(U));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 16 && n == 6144) {
    k3_situ_b16_n6144_kernel<<<dim3(16, 24, 1), 256, 0, stream>>>(
        reinterpret_cast<const bfloat16_t*>(G),
        reinterpret_cast<bfloat16_t*>(O),
        reinterpret_cast<const bfloat16_t*>(U));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 32 && n == 6144) {
    k3_situ_b32_n6144_kernel<<<dim3(32, 24, 1), 256, 0, stream>>>(
        reinterpret_cast<const bfloat16_t*>(G),
        reinterpret_cast<bfloat16_t*>(O),
        reinterpret_cast<const bfloat16_t*>(U));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 48 && n == 6144) {
    k3_situ_b48_n6144_kernel<<<dim3(48, 24, 1), 256, 0, stream>>>(
        reinterpret_cast<const bfloat16_t*>(G),
        reinterpret_cast<bfloat16_t*>(O),
        reinterpret_cast<const bfloat16_t*>(U));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 64 && n == 6144) {
    k3_situ_b64_n6144_kernel<<<dim3(64, 24, 1), 256, 0, stream>>>(
        reinterpret_cast<const bfloat16_t*>(G),
        reinterpret_cast<bfloat16_t*>(O),
        reinterpret_cast<const bfloat16_t*>(U));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 96 && n == 6144) {
    k3_situ_b96_n6144_kernel<<<dim3(96, 24, 1), 256, 0, stream>>>(
        reinterpret_cast<const bfloat16_t*>(G),
        reinterpret_cast<bfloat16_t*>(O),
        reinterpret_cast<const bfloat16_t*>(U));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 128 && n == 6144) {
    k3_situ_b128_n6144_kernel<<<dim3(128, 24, 1), 256, 0, stream>>>(
        reinterpret_cast<const bfloat16_t*>(G),
        reinterpret_cast<bfloat16_t*>(O),
        reinterpret_cast<const bfloat16_t*>(U));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 1 && n == 33792) {
    k3_situ_b1_n33792_kernel<<<dim3(1, 132, 1), 256, 0, stream>>>(
        reinterpret_cast<const bfloat16_t*>(G),
        reinterpret_cast<bfloat16_t*>(O),
        reinterpret_cast<const bfloat16_t*>(U));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 2 && n == 33792) {
    k3_situ_b2_n33792_kernel<<<dim3(2, 132, 1), 256, 0, stream>>>(
        reinterpret_cast<const bfloat16_t*>(G),
        reinterpret_cast<bfloat16_t*>(O),
        reinterpret_cast<const bfloat16_t*>(U));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 4 && n == 33792) {
    k3_situ_b4_n33792_kernel<<<dim3(4, 132, 1), 256, 0, stream>>>(
        reinterpret_cast<const bfloat16_t*>(G),
        reinterpret_cast<bfloat16_t*>(O),
        reinterpret_cast<const bfloat16_t*>(U));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 8 && n == 33792) {
    k3_situ_b8_n33792_kernel<<<dim3(8, 132, 1), 256, 0, stream>>>(
        reinterpret_cast<const bfloat16_t*>(G),
        reinterpret_cast<bfloat16_t*>(O),
        reinterpret_cast<const bfloat16_t*>(U));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 16 && n == 33792) {
    k3_situ_b16_n33792_kernel<<<dim3(16, 132, 1), 256, 0, stream>>>(
        reinterpret_cast<const bfloat16_t*>(G),
        reinterpret_cast<bfloat16_t*>(O),
        reinterpret_cast<const bfloat16_t*>(U));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 32 && n == 33792) {
    k3_situ_b32_n33792_kernel<<<dim3(32, 132, 1), 256, 0, stream>>>(
        reinterpret_cast<const bfloat16_t*>(G),
        reinterpret_cast<bfloat16_t*>(O),
        reinterpret_cast<const bfloat16_t*>(U));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 48 && n == 33792) {
    k3_situ_b48_n33792_kernel<<<dim3(48, 132, 1), 256, 0, stream>>>(
        reinterpret_cast<const bfloat16_t*>(G),
        reinterpret_cast<bfloat16_t*>(O),
        reinterpret_cast<const bfloat16_t*>(U));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 64 && n == 33792) {
    k3_situ_b64_n33792_kernel<<<dim3(64, 132, 1), 256, 0, stream>>>(
        reinterpret_cast<const bfloat16_t*>(G),
        reinterpret_cast<bfloat16_t*>(O),
        reinterpret_cast<const bfloat16_t*>(U));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 96 && n == 33792) {
    k3_situ_b96_n33792_kernel<<<dim3(96, 132, 1), 256, 0, stream>>>(
        reinterpret_cast<const bfloat16_t*>(G),
        reinterpret_cast<bfloat16_t*>(O),
        reinterpret_cast<const bfloat16_t*>(U));
    return static_cast<int>(cudaGetLastError());
  }
  if (b == 128 && n == 33792) {
    k3_situ_b128_n33792_kernel<<<dim3(128, 132, 1), 256, 0, stream>>>(
        reinterpret_cast<const bfloat16_t*>(G),
        reinterpret_cast<bfloat16_t*>(O),
        reinterpret_cast<const bfloat16_t*>(U));
    return static_cast<int>(cudaGetLastError());
  }
  return static_cast<int>(cudaErrorInvalidValue);
}
