#!/usr/bin/env python3
"""Line-indexed entry points for pegainfer's TileLang K3 state kernels.

    python3 tools/k3_line_shim.py <family>.cu <out.cu> [--bucket 1]

The certified kernels take the recurrent state (`k3_kda_core`: `State` in,
`StateN` out) and the convolution window (`k3_conv_silu`: `Cs` in, `Sn` out)
as plain pointers. In kern a sequence's state is a *line* of a
`bytes_per_seq` state, addressed through a line table the runtime fills per
lease, so the kernel has to resolve `base + line * stride` itself. This
script keeps the generated kernel body byte for byte (renamed to a
`__device__` function) and emits an `extern "C"` wrapper that computes the
pointer and calls it **in place** (`State == StateN`, `Cs == Sn`): both
kernels read and write each state element from the one thread that owns it,
with every read of an element before its write, so the in-place form is the
certified two-buffer form minus the copy.

Wrapper ABI = the kernel's parameters with the two state pointers replaced by
`(Base, Line, LineStride, Off)`, in the original position of the first:
`ptr = Base + Line[0] * LineStride + Off` (elements). Only the requested
batch bucket is emitted (at B=1 there is one line per launch).
"""
import argparse
import re
import sys

STATE_PARAMS = {
    "k3_kda_core": ("State", "StateN", "float"),
    "k3_conv_silu": ("Cs", "Sn", "bfloat16_t"),
}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("src")
    ap.add_argument("out")
    ap.add_argument("--bucket", type=int, default=1)
    a = ap.parse_args()
    text = open(a.src).read().splitlines()
    family = next((f for f in STATE_PARAMS if f"/{f}_batched" in a.src or a.src.startswith(f)), None)
    if family is None:
        sys.exit(f"{a.src}: not a state kernel family ({', '.join(STATE_PARAMS)})")
    p_in, p_out, ctype = STATE_PARAMS[family]

    # Header: everything before the first kernel prototype.
    first = next(i for i, l in enumerate(text) if l.startswith('extern "C" __global__'))
    out = text[:first]
    out.append("// Line-indexed wrappers generated by tools/k3_line_shim.py; bodies verbatim.")
    head_re = re.compile(r'^extern "C" __global__ void (__launch_bounds__\([^)]*\)) (\w+)\((.*)\) \{$')
    i = first
    emitted = 0
    while i < len(text):
        m = head_re.match(text[i])
        if not m:
            i += 1
            continue
        bounds, name, params = m.groups()
        j = i + 1
        while text[j] != "}":
            j += 1
        body = text[i + 1:j]
        i = j + 1
        if f"_b{a.bucket}_" not in name:
            continue
        plist = [p.strip() for p in params.split(",")]
        names = [p.split()[-1] for p in plist]
        assert p_in in names and p_out in names, (name, names)
        out.append(f"static __device__ __forceinline__ void {name}_body({params}) {{")
        out.extend(body)
        out.append("}")
        wrapper_params = []
        call = []
        for p, n in zip(plist, names):
            if n == p_in:
                wrapper_params += [f"{ctype}* __restrict__ Base", "const int* __restrict__ Line",
                                   "long long LineStride", "long long Off"]
                call.append("st")
            elif n == p_out:
                call.append("st")
            else:
                wrapper_params.append(p)
                call.append(n)
        wname = "kern_" + name.replace("_kernel", "_line")
        out.append(f'extern "C" __global__ void {bounds} {wname}({", ".join(wrapper_params)}) {{')
        out.append(f"  {ctype}* st = Base + (long long)Line[0] * LineStride + Off;")
        out.append(f"  {name}_body({', '.join(call)});")
        out.append("}")
        emitted += 1
    if emitted == 0:
        sys.exit(f"{a.src}: no b{a.bucket} kernels found")
    open(a.out, "w").write("\n".join(out) + "\n")
    print(f"{a.out}: {emitted} line-indexed wrapper(s) for {family} b{a.bucket}", file=sys.stderr)


if __name__ == "__main__":
    main()
